<?php

namespace Database\Seeders;

use App\Domain\WameedAI\Models\AILlmModel;
use Illuminate\Database\Seeder;

class AILlmModelSeeder extends Seeder
{
    public function run(): void
    {
        $models = [
            // ─── OpenAI Models ────────────────────────────────
            [
                'provider' => 'openai',
                'model_id' => 'gpt-4o',
                'display_name' => 'GPT-4o',
                'description' => 'Most capable OpenAI model. Great for complex tasks, analysis, and creative content.',
                'supports_vision' => true,
                'supports_json_mode' => true,
                'max_context_tokens' => 128000,
                'max_output_tokens' => 16384,
                'input_price_per_1m' => 2.50,
                'output_price_per_1m' => 10.00,
                'is_enabled' => true,
                'is_default' => false,
                'sort_order' => 1,
            ],
            [
                'provider' => 'openai',
                'model_id' => 'gpt-4o-mini',
                'display_name' => 'GPT-4o Mini',
                'description' => 'Fast and affordable. Best for everyday tasks and quick responses.',
                'supports_vision' => true,
                'supports_json_mode' => true,
                'max_context_tokens' => 128000,
                'max_output_tokens' => 16384,
                'input_price_per_1m' => 0.15,
                'output_price_per_1m' => 0.60,
                'is_enabled' => true,
                'is_default' => true,
                'sort_order' => 2,
            ],
            [
                'provider' => 'openai',
                'model_id' => 'gpt-4.1',
                'display_name' => 'GPT-4.1',
                'description' => 'Latest GPT-4 series with improved coding and instruction following.',
                'supports_vision' => true,
                'supports_json_mode' => true,
                'max_context_tokens' => 1047576,
                'max_output_tokens' => 32768,
                'input_price_per_1m' => 2.00,
                'output_price_per_1m' => 8.00,
                'is_enabled' => true,
                'is_default' => false,
                'sort_order' => 3,
            ],
            [
                'provider' => 'openai',
                'model_id' => 'gpt-4.1-mini',
                'display_name' => 'GPT-4.1 Mini',
                'description' => 'Balanced performance and cost from the GPT-4.1 series.',
                'supports_vision' => true,
                'supports_json_mode' => true,
                'max_context_tokens' => 1047576,
                'max_output_tokens' => 32768,
                'input_price_per_1m' => 0.40,
                'output_price_per_1m' => 1.60,
                'is_enabled' => true,
                'is_default' => false,
                'sort_order' => 4,
            ],
            [
                'provider' => 'openai',
                'model_id' => 'gpt-4.1-nano',
                'display_name' => 'GPT-4.1 Nano',
                'description' => 'Ultra-fast, lowest cost model for simple tasks.',
                'supports_vision' => true,
                'supports_json_mode' => true,
                'max_context_tokens' => 1047576,
                'max_output_tokens' => 32768,
                'input_price_per_1m' => 0.10,
                'output_price_per_1m' => 0.40,
                'is_enabled' => true,
                'is_default' => false,
                'sort_order' => 5,
            ],
            [
                'provider' => 'openai',
                'model_id' => 'o4-mini',
                'display_name' => 'o4 Mini',
                'description' => 'OpenAI reasoning model. Best for math, coding, and complex logic.',
                'supports_vision' => true,
                'supports_json_mode' => true,
                'max_context_tokens' => 200000,
                'max_output_tokens' => 100000,
                'input_price_per_1m' => 1.10,
                'output_price_per_1m' => 4.40,
                'is_enabled' => true,
                'is_default' => false,
                'sort_order' => 6,
            ],
            [
                'provider' => 'openai',
                'model_id' => 'o3',
                'display_name' => 'o3',
                'description' => 'Advanced reasoning model for the most challenging tasks.',
                'supports_vision' => true,
                'supports_json_mode' => true,
                'max_context_tokens' => 200000,
                'max_output_tokens' => 100000,
                'input_price_per_1m' => 10.00,
                'output_price_per_1m' => 40.00,
                'is_enabled' => false,
                'is_default' => false,
                'sort_order' => 7,
            ],
            [
                'provider' => 'openai',
                'model_id' => 'o3-mini',
                'display_name' => 'o3 Mini',
                'description' => 'Cost-effective reasoning model.',
                'supports_vision' => false,
                'supports_json_mode' => true,
                'max_context_tokens' => 200000,
                'max_output_tokens' => 100000,
                'input_price_per_1m' => 1.10,
                'output_price_per_1m' => 4.40,
                'is_enabled' => false,
                'is_default' => false,
                'sort_order' => 8,
            ],
            [
                'provider' => 'openai',
                'model_id' => 'o1',
                'display_name' => 'o1',
                'description' => 'First-gen reasoning model for complex analysis.',
                'supports_vision' => true,
                'supports_json_mode' => true,
                'max_context_tokens' => 200000,
                'max_output_tokens' => 100000,
                'input_price_per_1m' => 15.00,
                'output_price_per_1m' => 60.00,
                'is_enabled' => false,
                'is_default' => false,
                'sort_order' => 9,
            ],
            [
                'provider' => 'openai',
                'model_id' => 'o1-mini',
                'display_name' => 'o1 Mini',
                'description' => 'Smaller reasoning model, good balance of speed and capability.',
                'supports_vision' => false,
                'supports_json_mode' => true,
                'max_context_tokens' => 128000,
                'max_output_tokens' => 65536,
                'input_price_per_1m' => 3.00,
                'output_price_per_1m' => 12.00,
                'is_enabled' => false,
                'is_default' => false,
                'sort_order' => 10,
            ],

            // ─── Anthropic Models ─────────────────────────────
            [
                'provider' => 'anthropic',
                'model_id' => 'claude-sonnet-4-20250514',
                'display_name' => 'Claude Sonnet 4',
                'description' => 'Latest Claude model. Excellent for analysis, writing, and coding.',
                'supports_vision' => true,
                'supports_json_mode' => false,
                'max_context_tokens' => 200000,
                'max_output_tokens' => 16384,
                'input_price_per_1m' => 3.00,
                'output_price_per_1m' => 15.00,
                'is_enabled' => true,
                'is_default' => false,
                'sort_order' => 20,
            ],
            [
                'provider' => 'anthropic',
                'model_id' => 'claude-3-7-sonnet-20250219',
                'display_name' => 'Claude 3.7 Sonnet',
                'description' => 'Hybrid reasoning model with extended thinking capability.',
                'supports_vision' => true,
                'supports_json_mode' => false,
                'max_context_tokens' => 200000,
                'max_output_tokens' => 16384,
                'input_price_per_1m' => 3.00,
                'output_price_per_1m' => 15.00,
                'is_enabled' => true,
                'is_default' => false,
                'sort_order' => 21,
            ],
            [
                'provider' => 'anthropic',
                'model_id' => 'claude-3-5-sonnet-20241022',
                'display_name' => 'Claude 3.5 Sonnet',
                'description' => 'High performance at a great price point.',
                'supports_vision' => true,
                'supports_json_mode' => false,
                'max_context_tokens' => 200000,
                'max_output_tokens' => 8192,
                'input_price_per_1m' => 3.00,
                'output_price_per_1m' => 15.00,
                'is_enabled' => true,
                'is_default' => false,
                'sort_order' => 22,
            ],
            [
                'provider' => 'anthropic',
                'model_id' => 'claude-3-5-haiku-20241022',
                'display_name' => 'Claude 3.5 Haiku',
                'description' => 'Fast and affordable Claude model for quick tasks.',
                'supports_vision' => true,
                'supports_json_mode' => false,
                'max_context_tokens' => 200000,
                'max_output_tokens' => 8192,
                'input_price_per_1m' => 0.80,
                'output_price_per_1m' => 4.00,
                'is_enabled' => true,
                'is_default' => false,
                'sort_order' => 23,
            ],
            [
                'provider' => 'anthropic',
                'model_id' => 'claude-3-opus-20240229',
                'display_name' => 'Claude 3 Opus',
                'description' => 'Most capable Claude 3 model for the hardest tasks.',
                'supports_vision' => true,
                'supports_json_mode' => false,
                'max_context_tokens' => 200000,
                'max_output_tokens' => 4096,
                'input_price_per_1m' => 15.00,
                'output_price_per_1m' => 75.00,
                'is_enabled' => false,
                'is_default' => false,
                'sort_order' => 24,
            ],
            [
                'provider' => 'anthropic',
                'model_id' => 'claude-3-haiku-20240307',
                'display_name' => 'Claude 3 Haiku',
                'description' => 'Fastest Claude model for simple tasks.',
                'supports_vision' => true,
                'supports_json_mode' => false,
                'max_context_tokens' => 200000,
                'max_output_tokens' => 4096,
                'input_price_per_1m' => 0.25,
                'output_price_per_1m' => 1.25,
                'is_enabled' => false,
                'is_default' => false,
                'sort_order' => 25,
            ],

            // ─── Google Gemini Models ─────────────────────────
            [
                'provider' => 'google',
                'model_id' => 'gemini-2.5-pro-preview-06-05',
                'display_name' => 'Gemini 2.5 Pro',
                'description' => 'Google\'s most capable model with 1M context window.',
                'supports_vision' => true,
                'supports_json_mode' => true,
                'max_context_tokens' => 1048576,
                'max_output_tokens' => 65536,
                'input_price_per_1m' => 1.25,
                'output_price_per_1m' => 10.00,
                'is_enabled' => true,
                'is_default' => false,
                'sort_order' => 40,
            ],
            [
                'provider' => 'google',
                'model_id' => 'gemini-2.5-flash-preview-05-20',
                'display_name' => 'Gemini 2.5 Flash',
                'description' => 'Fast and efficient with thinking capabilities.',
                'supports_vision' => true,
                'supports_json_mode' => true,
                'max_context_tokens' => 1048576,
                'max_output_tokens' => 65536,
                'input_price_per_1m' => 0.15,
                'output_price_per_1m' => 0.60,
                'is_enabled' => true,
                'is_default' => false,
                'sort_order' => 41,
            ],
            [
                'provider' => 'google',
                'model_id' => 'gemini-2.0-flash',
                'display_name' => 'Gemini 2.0 Flash',
                'description' => 'Next gen features with speed. Good for most tasks.',
                'supports_vision' => true,
                'supports_json_mode' => true,
                'max_context_tokens' => 1048576,
                'max_output_tokens' => 8192,
                'input_price_per_1m' => 0.10,
                'output_price_per_1m' => 0.40,
                'is_enabled' => true,
                'is_default' => false,
                'sort_order' => 42,
            ],
            [
                'provider' => 'google',
                'model_id' => 'gemini-2.0-flash-lite',
                'display_name' => 'Gemini 2.0 Flash Lite',
                'description' => 'Fastest and lowest cost Gemini model.',
                'supports_vision' => true,
                'supports_json_mode' => true,
                'max_context_tokens' => 1048576,
                'max_output_tokens' => 8192,
                'input_price_per_1m' => 0.075,
                'output_price_per_1m' => 0.30,
                'is_enabled' => true,
                'is_default' => false,
                'sort_order' => 43,
            ],
            [
                'provider' => 'google',
                'model_id' => 'gemini-1.5-pro',
                'display_name' => 'Gemini 1.5 Pro',
                'description' => 'Complex reasoning with 2M context window.',
                'supports_vision' => true,
                'supports_json_mode' => true,
                'max_context_tokens' => 2097152,
                'max_output_tokens' => 8192,
                'input_price_per_1m' => 1.25,
                'output_price_per_1m' => 5.00,
                'is_enabled' => false,
                'is_default' => false,
                'sort_order' => 44,
            ],
            [
                'provider' => 'google',
                'model_id' => 'gemini-1.5-flash',
                'display_name' => 'Gemini 1.5 Flash',
                'description' => 'Fast and versatile with 1M tokens.',
                'supports_vision' => true,
                'supports_json_mode' => true,
                'max_context_tokens' => 1048576,
                'max_output_tokens' => 8192,
                'input_price_per_1m' => 0.075,
                'output_price_per_1m' => 0.30,
                'is_enabled' => false,
                'is_default' => false,
                'sort_order' => 45,
            ],
        ];

        foreach ($models as $model) {
            AILlmModel::updateOrCreate(
                ['provider' => $model['provider'], 'model_id' => $model['model_id']],
                $model,
            );
        }

        $this->command?->info('Seeded ' . count($models) . ' LLM models across 3 providers.');
    }
}
