<?php

namespace Database\Seeders;

use App\Domain\ContentOnboarding\Enums\WidgetCategory;
use App\Domain\ContentOnboarding\Models\LayoutWidget;
use Illuminate\Database\Seeder;

class ComprehensiveWidgetSeeder extends Seeder
{
    public function run(): void
    {
        $widgets = [
            // ══════════════════ CORE (3) ══════════════════
            [
                'slug' => 'product_grid',
                'name' => 'Product Grid',
                'name_ar' => 'شبكة المنتجات',
                'description' => 'Displays products in a configurable grid layout with images, prices, and stock indicators',
                'description_ar' => 'يعرض المنتجات في شبكة قابلة للتخصيص مع الصور والأسعار ومؤشرات المخزون',
                'category' => WidgetCategory::Core,
                'icon' => 'heroicon-o-squares-2x2',
                'default_width' => 12, 'default_height' => 10,
                'min_width' => 6, 'min_height' => 4, 'max_width' => 24, 'max_height' => 16,
                'is_resizable' => true, 'is_required' => true,
                'properties_schema' => [
                    'columns' => ['type' => 'integer', 'min' => 2, 'max' => 8, 'default' => 4],
                    'show_images' => ['type' => 'boolean', 'default' => true],
                    'show_prices' => ['type' => 'boolean', 'default' => true],
                    'show_stock' => ['type' => 'boolean', 'default' => false],
                ],
                'default_properties' => ['columns' => 4, 'show_images' => true, 'show_prices' => true, 'show_stock' => false],
                'sort_order' => 1,
            ],
            [
                'slug' => 'cart_panel',
                'name' => 'Cart Panel',
                'name_ar' => 'لوحة السلة',
                'description' => 'Shopping cart with line items, quantities, discounts, and totals',
                'description_ar' => 'سلة التسوق مع العناصر والكميات والخصومات والإجماليات',
                'category' => WidgetCategory::Core,
                'icon' => 'heroicon-o-shopping-cart',
                'default_width' => 8, 'default_height' => 14,
                'min_width' => 6, 'min_height' => 6, 'max_width' => 12, 'max_height' => 16,
                'is_resizable' => true, 'is_required' => true,
                'properties_schema' => [
                    'display_mode' => ['type' => 'select', 'options' => ['compact', 'detailed'], 'default' => 'detailed'],
                    'show_discounts' => ['type' => 'boolean', 'default' => true],
                    'show_tax' => ['type' => 'boolean', 'default' => true],
                ],
                'default_properties' => ['display_mode' => 'detailed', 'show_discounts' => true, 'show_tax' => true],
                'sort_order' => 2,
            ],
            [
                'slug' => 'payment_buttons',
                'name' => 'Payment Buttons',
                'name_ar' => 'أزرار الدفع',
                'description' => 'Payment method selection buttons (cash, card, wallet, etc.)',
                'description_ar' => 'أزرار اختيار طريقة الدفع (نقد، بطاقة، محفظة، إلخ)',
                'category' => WidgetCategory::Core,
                'icon' => 'heroicon-o-credit-card',
                'default_width' => 8, 'default_height' => 2,
                'min_width' => 4, 'min_height' => 2, 'max_width' => 12, 'max_height' => 4,
                'is_resizable' => true, 'is_required' => true,
                'properties_schema' => [
                    'methods' => ['type' => 'array', 'default' => ['cash', 'card', 'wallet']],
                    'layout' => ['type' => 'select', 'options' => ['horizontal', 'vertical', 'grid'], 'default' => 'horizontal'],
                ],
                'default_properties' => ['methods' => ['cash', 'card', 'wallet'], 'layout' => 'horizontal'],
                'sort_order' => 3,
            ],

            // ══════════════════ COMMERCE (5) ══════════════════
            [
                'slug' => 'category_bar',
                'name' => 'Category Bar',
                'name_ar' => 'شريط الفئات',
                'description' => 'Horizontal or vertical category navigation bar with icons and product counts',
                'description_ar' => 'شريط تنقل الفئات أفقي أو عمودي مع الأيقونات وعدد المنتجات',
                'category' => WidgetCategory::Commerce,
                'icon' => 'heroicon-o-tag',
                'default_width' => 24, 'default_height' => 2,
                'min_width' => 6, 'min_height' => 1, 'max_width' => 24, 'max_height' => 4,
                'is_resizable' => true, 'is_required' => false,
                'properties_schema' => [
                    'style' => ['type' => 'select', 'options' => ['tabs', 'sidebar', 'icons', 'pills'], 'default' => 'tabs'],
                    'show_icons' => ['type' => 'boolean', 'default' => true],
                    'show_counts' => ['type' => 'boolean', 'default' => false],
                ],
                'default_properties' => ['style' => 'tabs', 'show_icons' => true, 'show_counts' => false],
                'sort_order' => 10,
            ],
            [
                'slug' => 'search_bar',
                'name' => 'Search Bar',
                'name_ar' => 'شريط البحث',
                'description' => 'Product search with barcode scanner integration and voice search',
                'description_ar' => 'بحث المنتجات مع دعم ماسح الباركود والبحث الصوتي',
                'category' => WidgetCategory::Commerce,
                'icon' => 'heroicon-o-magnifying-glass',
                'default_width' => 12, 'default_height' => 1,
                'min_width' => 4, 'min_height' => 1, 'max_width' => 24, 'max_height' => 2,
                'is_resizable' => true, 'is_required' => false,
                'properties_schema' => [
                    'placeholder' => ['type' => 'string', 'default' => 'Search products...'],
                    'show_barcode_button' => ['type' => 'boolean', 'default' => true],
                    'auto_focus' => ['type' => 'boolean', 'default' => false],
                ],
                'default_properties' => ['placeholder' => 'Search products...', 'show_barcode_button' => true, 'auto_focus' => false],
                'sort_order' => 11,
            ],
            [
                'slug' => 'customer_info',
                'name' => 'Customer Info',
                'name_ar' => 'معلومات العميل',
                'description' => 'Customer details panel with search, loyalty info, and purchase history',
                'description_ar' => 'لوحة تفاصيل العميل مع البحث ومعلومات الولاء وسجل المشتريات',
                'category' => WidgetCategory::Commerce,
                'icon' => 'heroicon-o-user',
                'default_width' => 8, 'default_height' => 3,
                'min_width' => 4, 'min_height' => 2, 'max_width' => 12, 'max_height' => 6,
                'is_resizable' => true, 'is_required' => false,
                'properties_schema' => [
                    'show_loyalty_points' => ['type' => 'boolean', 'default' => true],
                    'show_purchase_history' => ['type' => 'boolean', 'default' => false],
                    'compact_mode' => ['type' => 'boolean', 'default' => false],
                ],
                'default_properties' => ['show_loyalty_points' => true, 'show_purchase_history' => false, 'compact_mode' => false],
                'sort_order' => 12,
            ],
            [
                'slug' => 'order_summary',
                'name' => 'Order Summary',
                'name_ar' => 'ملخص الطلب',
                'description' => 'Compact order summary with subtotal, tax, discounts, and savings',
                'description_ar' => 'ملخص مدمج للطلب مع المجموع الفرعي والضريبة والخصومات والتوفير',
                'category' => WidgetCategory::Commerce,
                'icon' => 'heroicon-o-clipboard-document-list',
                'default_width' => 8, 'default_height' => 3,
                'min_width' => 4, 'min_height' => 2, 'max_width' => 12, 'max_height' => 6,
                'is_resizable' => true, 'is_required' => false,
                'properties_schema' => [
                    'show_item_count' => ['type' => 'boolean', 'default' => true],
                    'show_savings' => ['type' => 'boolean', 'default' => true],
                ],
                'default_properties' => ['show_item_count' => true, 'show_savings' => true],
                'sort_order' => 13,
            ],
            [
                'slug' => 'quick_actions',
                'name' => 'Quick Actions',
                'name_ar' => 'الإجراءات السريعة',
                'description' => 'Configurable quick action buttons (hold, discount, refund, void, etc.)',
                'description_ar' => 'أزرار إجراءات سريعة قابلة للتخصيص (تعليق، خصم، استرجاع، إلغاء، إلخ)',
                'category' => WidgetCategory::Commerce,
                'icon' => 'heroicon-o-bolt',
                'default_width' => 8, 'default_height' => 2,
                'min_width' => 4, 'min_height' => 1, 'max_width' => 24, 'max_height' => 4,
                'is_resizable' => true, 'is_required' => false,
                'properties_schema' => [
                    'actions' => ['type' => 'array', 'default' => ['hold', 'discount', 'refund', 'void']],
                    'layout' => ['type' => 'select', 'options' => ['horizontal', 'grid'], 'default' => 'horizontal'],
                ],
                'default_properties' => ['actions' => ['hold', 'discount', 'refund', 'void'], 'layout' => 'horizontal'],
                'sort_order' => 14,
            ],

            // ══════════════════ DISPLAY (5) ══════════════════
            [
                'slug' => 'receipt_preview',
                'name' => 'Receipt Preview',
                'name_ar' => 'معاينة الإيصال',
                'description' => 'Live receipt preview panel with selectable paper sizes',
                'description_ar' => 'لوحة معاينة الإيصال المباشر مع أحجام ورق قابلة للاختيار',
                'category' => WidgetCategory::Display,
                'icon' => 'heroicon-o-document-text',
                'default_width' => 6, 'default_height' => 8,
                'min_width' => 4, 'min_height' => 4, 'max_width' => 12, 'max_height' => 16,
                'is_resizable' => true, 'is_required' => false,
                'properties_schema' => [
                    'paper_size' => ['type' => 'select', 'options' => ['80mm', '58mm'], 'default' => '80mm'],
                ],
                'default_properties' => ['paper_size' => '80mm'],
                'sort_order' => 20,
            ],
            [
                'slug' => 'clock_widget',
                'name' => 'Clock',
                'name_ar' => 'الساعة',
                'description' => 'Digital clock with date display and optional Hijri calendar',
                'description_ar' => 'ساعة رقمية مع عرض التاريخ والتقويم الهجري الاختياري',
                'category' => WidgetCategory::Display,
                'icon' => 'heroicon-o-clock',
                'default_width' => 4, 'default_height' => 2,
                'min_width' => 2, 'min_height' => 1, 'max_width' => 8, 'max_height' => 4,
                'is_resizable' => true, 'is_required' => false,
                'properties_schema' => [
                    'format_24h' => ['type' => 'boolean', 'default' => true],
                    'show_date' => ['type' => 'boolean', 'default' => true],
                    'show_hijri' => ['type' => 'boolean', 'default' => false],
                ],
                'default_properties' => ['format_24h' => true, 'show_date' => true, 'show_hijri' => false],
                'sort_order' => 21,
            ],
            [
                'slug' => 'store_branding',
                'name' => 'Store Branding',
                'name_ar' => 'العلامة التجارية',
                'description' => 'Store logo and branding display area',
                'description_ar' => 'منطقة عرض شعار المتجر والعلامة التجارية',
                'category' => WidgetCategory::Display,
                'icon' => 'heroicon-o-building-storefront',
                'default_width' => 4, 'default_height' => 2,
                'min_width' => 2, 'min_height' => 1, 'max_width' => 12, 'max_height' => 4,
                'is_resizable' => true, 'is_required' => false,
                'properties_schema' => [
                    'show_logo' => ['type' => 'boolean', 'default' => true],
                    'show_store_name' => ['type' => 'boolean', 'default' => true],
                ],
                'default_properties' => ['show_logo' => true, 'show_store_name' => true],
                'sort_order' => 22,
            ],
            // NEW: Loyalty Points Display
            [
                'slug' => 'loyalty_points',
                'name' => 'Loyalty Points',
                'name_ar' => 'نقاط الولاء',
                'description' => 'Displays customer loyalty points balance, tier status, and available rewards',
                'description_ar' => 'يعرض رصيد نقاط ولاء العميل ومستوى العضوية والمكافآت المتاحة',
                'category' => WidgetCategory::Display,
                'icon' => 'heroicon-o-star',
                'default_width' => 6, 'default_height' => 3,
                'min_width' => 4, 'min_height' => 2, 'max_width' => 12, 'max_height' => 6,
                'is_resizable' => true, 'is_required' => false,
                'properties_schema' => [
                    'show_tier_badge' => ['type' => 'boolean', 'default' => true],
                    'show_points_expiry' => ['type' => 'boolean', 'default' => false],
                    'show_redeem_button' => ['type' => 'boolean', 'default' => true],
                    'tier_colors' => ['type' => 'object', 'default' => ['bronze' => '#CD7F32', 'silver' => '#C0C0C0', 'gold' => '#FFD700', 'platinum' => '#E5E4E2']],
                ],
                'default_properties' => ['show_tier_badge' => true, 'show_points_expiry' => false, 'show_redeem_button' => true, 'tier_colors' => ['bronze' => '#CD7F32', 'silver' => '#C0C0C0', 'gold' => '#FFD700', 'platinum' => '#E5E4E2']],
                'sort_order' => 23,
            ],
            // NEW: Promotional Banner
            [
                'slug' => 'promotional_banner',
                'name' => 'Promotional Banner',
                'name_ar' => 'لافتة ترويجية',
                'description' => 'Rotating promotional banners for in-store offers, seasonal deals, and announcements',
                'description_ar' => 'لافتات ترويجية متحركة للعروض الداخلية والصفقات الموسمية والإعلانات',
                'category' => WidgetCategory::Display,
                'icon' => 'heroicon-o-megaphone',
                'default_width' => 12, 'default_height' => 3,
                'min_width' => 6, 'min_height' => 2, 'max_width' => 24, 'max_height' => 6,
                'is_resizable' => true, 'is_required' => false,
                'properties_schema' => [
                    'rotation_interval_seconds' => ['type' => 'integer', 'min' => 3, 'max' => 30, 'default' => 8],
                    'animation' => ['type' => 'select', 'options' => ['fade', 'slide', 'none'], 'default' => 'fade'],
                    'auto_rotate' => ['type' => 'boolean', 'default' => true],
                    'show_indicators' => ['type' => 'boolean', 'default' => true],
                ],
                'default_properties' => ['rotation_interval_seconds' => 8, 'animation' => 'fade', 'auto_rotate' => true, 'show_indicators' => true],
                'sort_order' => 24,
            ],

            // ══════════════════ UTILITY (4) ══════════════════
            [
                'slug' => 'numpad',
                'name' => 'Numpad',
                'name_ar' => 'لوحة الأرقام',
                'description' => 'Numeric keypad for quantity and price entry with decimal support',
                'description_ar' => 'لوحة مفاتيح رقمية لإدخال الكمية والسعر مع دعم الكسور العشرية',
                'category' => WidgetCategory::Utility,
                'icon' => 'heroicon-o-calculator',
                'default_width' => 4, 'default_height' => 5,
                'min_width' => 3, 'min_height' => 4, 'max_width' => 8, 'max_height' => 8,
                'is_resizable' => true, 'is_required' => false,
                'properties_schema' => [
                    'show_decimal' => ['type' => 'boolean', 'default' => true],
                    'show_backspace' => ['type' => 'boolean', 'default' => true],
                ],
                'default_properties' => ['show_decimal' => true, 'show_backspace' => true],
                'sort_order' => 30,
            ],
            [
                'slug' => 'custom_html',
                'name' => 'Custom HTML',
                'name_ar' => 'HTML مخصص',
                'description' => 'Custom HTML content block for notices, ads, or informational content',
                'description_ar' => 'كتلة محتوى HTML مخصصة للإشعارات أو الإعلانات أو المعلومات',
                'category' => WidgetCategory::Utility,
                'icon' => 'heroicon-o-code-bracket',
                'default_width' => 6, 'default_height' => 3,
                'min_width' => 2, 'min_height' => 1, 'max_width' => 24, 'max_height' => 16,
                'is_resizable' => true, 'is_required' => false,
                'properties_schema' => [
                    'html_content' => ['type' => 'text', 'default' => ''],
                ],
                'default_properties' => ['html_content' => ''],
                'sort_order' => 31,
            ],
            [
                'slug' => 'held_orders',
                'name' => 'Held Orders',
                'name_ar' => 'الطلبات المعلقة',
                'description' => 'List of held/parked orders for quick recall with age indicator',
                'description_ar' => 'قائمة الطلبات المعلقة للاسترجاع السريع مع مؤشر الوقت',
                'category' => WidgetCategory::Utility,
                'icon' => 'heroicon-o-pause-circle',
                'default_width' => 6, 'default_height' => 4,
                'min_width' => 4, 'min_height' => 3, 'max_width' => 12, 'max_height' => 8,
                'is_resizable' => true, 'is_required' => false,
                'properties_schema' => [
                    'max_display' => ['type' => 'integer', 'min' => 3, 'max' => 20, 'default' => 5],
                    'show_age' => ['type' => 'boolean', 'default' => true],
                ],
                'default_properties' => ['max_display' => 5, 'show_age' => true],
                'sort_order' => 32,
            ],
            // NEW: Staff Notes
            [
                'slug' => 'staff_notes',
                'name' => 'Staff Notes',
                'name_ar' => 'ملاحظات الموظفين',
                'description' => 'Internal staff notes and shift messages visible only to cashiers on the POS',
                'description_ar' => 'ملاحظات داخلية للموظفين ورسائل الوردية مرئية فقط للكاشير',
                'category' => WidgetCategory::Utility,
                'icon' => 'heroicon-o-chat-bubble-left-right',
                'default_width' => 6, 'default_height' => 4,
                'min_width' => 4, 'min_height' => 3, 'max_width' => 12, 'max_height' => 8,
                'is_resizable' => true, 'is_required' => false,
                'properties_schema' => [
                    'max_notes' => ['type' => 'integer', 'min' => 1, 'max' => 50, 'default' => 10],
                    'show_author' => ['type' => 'boolean', 'default' => true],
                    'show_timestamp' => ['type' => 'boolean', 'default' => true],
                    'allow_add' => ['type' => 'boolean', 'default' => true],
                ],
                'default_properties' => ['max_notes' => 10, 'show_author' => true, 'show_timestamp' => true, 'allow_add' => true],
                'sort_order' => 33,
            ],

            // ══════════════════ CUSTOM (3) ══════════════════
            // NEW: Recent Transactions
            [
                'slug' => 'recent_transactions',
                'name' => 'Recent Transactions',
                'name_ar' => 'المعاملات الأخيرة',
                'description' => 'Live feed of recent sales for the current shift with quick reprint and refund',
                'description_ar' => 'تغذية مباشرة لعمليات البيع الأخيرة للوردية الحالية مع إعادة الطباعة والاسترجاع',
                'category' => WidgetCategory::Custom,
                'icon' => 'heroicon-o-arrow-path',
                'default_width' => 8, 'default_height' => 6,
                'min_width' => 6, 'min_height' => 4, 'max_width' => 12, 'max_height' => 10,
                'is_resizable' => true, 'is_required' => false,
                'properties_schema' => [
                    'max_rows' => ['type' => 'integer', 'min' => 5, 'max' => 50, 'default' => 10],
                    'show_payment_method' => ['type' => 'boolean', 'default' => true],
                    'show_reprint_button' => ['type' => 'boolean', 'default' => true],
                    'show_refund_button' => ['type' => 'boolean', 'default' => false],
                ],
                'default_properties' => ['max_rows' => 10, 'show_payment_method' => true, 'show_reprint_button' => true, 'show_refund_button' => false],
                'sort_order' => 40,
            ],
            // NEW: Weather Widget
            [
                'slug' => 'weather_widget',
                'name' => 'Weather Widget',
                'name_ar' => 'أداة الطقس',
                'description' => 'Current weather display for the store location – useful for customer-facing screens',
                'description_ar' => 'عرض الطقس الحالي لموقع المتجر – مفيد لشاشات العملاء',
                'category' => WidgetCategory::Custom,
                'icon' => 'heroicon-o-sun',
                'default_width' => 4, 'default_height' => 2,
                'min_width' => 3, 'min_height' => 2, 'max_width' => 8, 'max_height' => 4,
                'is_resizable' => true, 'is_required' => false,
                'properties_schema' => [
                    'unit' => ['type' => 'select', 'options' => ['celsius', 'fahrenheit'], 'default' => 'celsius'],
                    'show_forecast' => ['type' => 'boolean', 'default' => false],
                    'show_humidity' => ['type' => 'boolean', 'default' => true],
                ],
                'default_properties' => ['unit' => 'celsius', 'show_forecast' => false, 'show_humidity' => true],
                'sort_order' => 41,
            ],
            // NEW: Table Map (restaurant)
            [
                'slug' => 'table_map',
                'name' => 'Table Map',
                'name_ar' => 'خريطة الطاولات',
                'description' => 'Interactive restaurant table map with real-time occupancy status and order linking',
                'description_ar' => 'خريطة تفاعلية لطاولات المطعم مع حالة الإشغال المباشرة وربط الطلبات',
                'category' => WidgetCategory::Custom,
                'icon' => 'heroicon-o-map',
                'default_width' => 10, 'default_height' => 8,
                'min_width' => 6, 'min_height' => 4, 'max_width' => 24, 'max_height' => 16,
                'is_resizable' => true, 'is_required' => false,
                'properties_schema' => [
                    'floor_plan_id' => ['type' => 'string', 'default' => ''],
                    'show_order_total' => ['type' => 'boolean', 'default' => true],
                    'show_timer' => ['type' => 'boolean', 'default' => true],
                    'status_colors' => ['type' => 'object', 'default' => ['available' => '#22C55E', 'occupied' => '#EF4444', 'reserved' => '#F59E0B', 'cleaning' => '#3B82F6']],
                ],
                'default_properties' => ['floor_plan_id' => '', 'show_order_total' => true, 'show_timer' => true, 'status_colors' => ['available' => '#22C55E', 'occupied' => '#EF4444', 'reserved' => '#F59E0B', 'cleaning' => '#3B82F6']],
                'sort_order' => 42,
            ],
        ];

        foreach ($widgets as $data) {
            LayoutWidget::updateOrCreate(['slug' => $data['slug']], $data);
        }
    }
}
