<?php

namespace Database\Seeders;

use App\Domain\ContentOnboarding\Models\ReceiptLayoutTemplate;
use Illuminate\Database\Seeder;

class ComprehensiveReceiptTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            // ── 1. Standard 80mm (existing, enhanced) ──
            [
                'name'       => 'Standard 80mm',
                'name_ar'    => 'قياسي 80 مم',
                'slug'       => 'standard_80mm',
                'paper_width' => 80,
                'header_config' => [
                    'logo_max_height'      => 60,
                    'store_name_font_size' => 18,
                    'store_name_bold'      => true,
                    'address_font_size'    => 12,
                    'show_vat_number'      => true,
                    'separator_style'      => 'dashes',
                    'show_phone'           => true,
                    'show_cr_number'       => false,
                ],
                'body_config' => [
                    'item_font_size'   => 12,
                    'price_alignment'  => 'right',
                    'show_sku'         => false,
                    'show_barcode'     => false,
                    'col_width_name'   => 50,
                    'col_width_qty'    => 15,
                    'col_width_price'  => 35,
                    'row_separator'    => false,
                    'totals_bold'      => true,
                    'show_discount_line' => true,
                    'show_vat_breakdown' => true,
                ],
                'footer_config' => [
                    'zatca_qr_size'       => 120,
                    'show_receipt_number'  => true,
                    'show_cashier_name'   => true,
                    'custom_footer_en'    => 'Thank you for your purchase!',
                    'custom_footer_ar'    => 'شكراً لتسوقكم!',
                    'thank_you_en'        => 'Visit us again!',
                    'thank_you_ar'        => 'نتشرف بزيارتكم مجدداً!',
                    'show_social_handles' => false,
                    'show_return_policy'  => true,
                    'return_policy_en'    => 'Returns accepted within 14 days with receipt.',
                    'return_policy_ar'    => 'يقبل الإرجاع خلال 14 يوم مع الإيصال.',
                ],
                'zatca_qr_position' => 'footer',
                'show_bilingual'    => true,
                'is_active'         => true,
                'sort_order'        => 0,
            ],
            // ── 2. Compact 58mm (existing, enhanced) ──
            [
                'name'       => 'Compact 58mm',
                'name_ar'    => 'مدمج 58 مم',
                'slug'       => 'compact_58mm',
                'paper_width' => 58,
                'header_config' => [
                    'logo_max_height'      => 40,
                    'store_name_font_size' => 14,
                    'store_name_bold'      => true,
                    'address_font_size'    => 10,
                    'show_vat_number'      => true,
                    'separator_style'      => 'line',
                    'show_phone'           => false,
                    'show_cr_number'       => false,
                ],
                'body_config' => [
                    'item_font_size'   => 10,
                    'price_alignment'  => 'right',
                    'show_sku'         => false,
                    'show_barcode'     => false,
                    'col_width_name'   => 50,
                    'col_width_qty'    => 15,
                    'col_width_price'  => 35,
                    'row_separator'    => false,
                    'totals_bold'      => true,
                    'show_discount_line' => false,
                    'show_vat_breakdown' => false,
                ],
                'footer_config' => [
                    'zatca_qr_size'       => 80,
                    'show_receipt_number'  => true,
                    'show_cashier_name'   => false,
                    'custom_footer_en'    => '',
                    'custom_footer_ar'    => '',
                    'thank_you_en'        => 'Thank you!',
                    'thank_you_ar'        => 'شكراً!',
                    'show_social_handles' => false,
                    'show_return_policy'  => false,
                ],
                'zatca_qr_position' => 'footer',
                'show_bilingual'    => false,
                'is_active'         => true,
                'sort_order'        => 1,
            ],
            // ── 3. Premium 80mm – full-featured luxury receipt ──
            [
                'name'       => 'Premium Branded',
                'name_ar'    => 'متميز بعلامة تجارية',
                'slug'       => 'premium_branded_80mm',
                'paper_width' => 80,
                'header_config' => [
                    'logo_max_height'      => 80,
                    'store_name_font_size' => 22,
                    'store_name_bold'      => true,
                    'address_font_size'    => 11,
                    'show_vat_number'      => true,
                    'separator_style'      => 'double_line',
                    'show_phone'           => true,
                    'show_cr_number'       => true,
                    'show_website'         => true,
                    'header_alignment'     => 'center',
                    'tagline_en'           => 'Quality you can trust',
                    'tagline_ar'           => 'جودة يمكنك الوثوق بها',
                ],
                'body_config' => [
                    'item_font_size'   => 12,
                    'price_alignment'  => 'right',
                    'show_sku'         => true,
                    'show_barcode'     => true,
                    'col_width_name'   => 45,
                    'col_width_qty'    => 15,
                    'col_width_price'  => 40,
                    'row_separator'    => true,
                    'totals_bold'      => true,
                    'show_discount_line' => true,
                    'show_vat_breakdown' => true,
                    'show_savings_total' => true,
                    'show_item_discount' => true,
                ],
                'footer_config' => [
                    'zatca_qr_size'       => 150,
                    'show_receipt_number'  => true,
                    'show_cashier_name'   => true,
                    'custom_footer_en'    => 'We appreciate your business!',
                    'custom_footer_ar'    => 'نقدر تعاملكم معنا!',
                    'thank_you_en'        => 'Thank you for choosing us!',
                    'thank_you_ar'        => 'شكراً لاختياركم لنا!',
                    'show_social_handles' => true,
                    'social_instagram'    => '@storename',
                    'social_twitter'      => '@storename',
                    'show_return_policy'  => true,
                    'return_policy_en'    => 'Full refund within 30 days. Exchange within 60 days.',
                    'return_policy_ar'    => 'استرداد كامل خلال 30 يوم. استبدال خلال 60 يوم.',
                    'show_loyalty_points' => true,
                    'loyalty_label_en'    => 'Points earned this visit',
                    'loyalty_label_ar'    => 'النقاط المكتسبة في هذه الزيارة',
                ],
                'zatca_qr_position' => 'footer',
                'show_bilingual'    => true,
                'is_active'         => true,
                'sort_order'        => 2,
            ],
            // ── 4. Bilingual Deluxe – Arabic-first with English ──
            [
                'name'       => 'Bilingual Deluxe',
                'name_ar'    => 'ثنائي اللغة فاخر',
                'slug'       => 'bilingual_deluxe_80mm',
                'paper_width' => 80,
                'header_config' => [
                    'logo_max_height'      => 70,
                    'store_name_font_size' => 20,
                    'store_name_bold'      => true,
                    'address_font_size'    => 12,
                    'show_vat_number'      => true,
                    'separator_style'      => 'dashes',
                    'show_phone'           => true,
                    'show_cr_number'       => true,
                    'primary_language'     => 'ar',
                    'header_alignment'     => 'center',
                ],
                'body_config' => [
                    'item_font_size'   => 12,
                    'price_alignment'  => 'left',
                    'show_sku'         => false,
                    'show_barcode'     => false,
                    'col_width_name'   => 50,
                    'col_width_qty'    => 15,
                    'col_width_price'  => 35,
                    'row_separator'    => false,
                    'totals_bold'      => true,
                    'show_discount_line' => true,
                    'show_vat_breakdown' => true,
                    'bilingual_item_names' => true,
                    'arabic_font_size' => 14,
                ],
                'footer_config' => [
                    'zatca_qr_size'       => 120,
                    'show_receipt_number'  => true,
                    'show_cashier_name'   => true,
                    'custom_footer_en'    => 'Thank you for shopping with us!',
                    'custom_footer_ar'    => 'شكراً لتسوقكم معنا!',
                    'thank_you_en'        => 'See you soon!',
                    'thank_you_ar'        => 'نراكم قريباً!',
                    'show_social_handles' => false,
                    'show_return_policy'  => true,
                    'return_policy_en'    => 'Returns within 14 days.',
                    'return_policy_ar'    => 'الإرجاع خلال 14 يوم.',
                ],
                'zatca_qr_position' => 'footer',
                'show_bilingual'    => true,
                'is_active'         => true,
                'sort_order'        => 3,
            ],
            // ── 5. Thermal Express – lightning-fast minimal ──
            [
                'name'       => 'Thermal Express',
                'name_ar'    => 'إيصال سريع حراري',
                'slug'       => 'thermal_express_58mm',
                'paper_width' => 58,
                'header_config' => [
                    'logo_max_height'      => 30,
                    'store_name_font_size' => 12,
                    'store_name_bold'      => true,
                    'address_font_size'    => 9,
                    'show_vat_number'      => true,
                    'separator_style'      => 'none',
                    'show_phone'           => false,
                    'show_cr_number'       => false,
                ],
                'body_config' => [
                    'item_font_size'   => 9,
                    'price_alignment'  => 'right',
                    'show_sku'         => false,
                    'show_barcode'     => false,
                    'col_width_name'   => 55,
                    'col_width_qty'    => 10,
                    'col_width_price'  => 35,
                    'row_separator'    => false,
                    'totals_bold'      => true,
                    'show_discount_line' => false,
                    'show_vat_breakdown' => false,
                    'compact_items'      => true,
                ],
                'footer_config' => [
                    'zatca_qr_size'       => 60,
                    'show_receipt_number'  => true,
                    'show_cashier_name'   => false,
                    'custom_footer_en'    => '',
                    'custom_footer_ar'    => '',
                    'thank_you_en'        => 'Thanks!',
                    'thank_you_ar'        => 'شكراً!',
                    'show_social_handles' => false,
                    'show_return_policy'  => false,
                ],
                'zatca_qr_position' => 'footer',
                'show_bilingual'    => false,
                'is_active'         => true,
                'sort_order'        => 4,
            ],
            // ── 6. Luxury Gift Receipt – elegant gift-wrap style ──
            [
                'name'       => 'Luxury Gift Receipt',
                'name_ar'    => 'إيصال هدية فاخر',
                'slug'       => 'luxury_gift_receipt_80mm',
                'paper_width' => 80,
                'header_config' => [
                    'logo_max_height'      => 90,
                    'store_name_font_size' => 24,
                    'store_name_bold'      => true,
                    'address_font_size'    => 11,
                    'show_vat_number'      => false,
                    'separator_style'      => 'decorative',
                    'show_phone'           => false,
                    'show_cr_number'       => false,
                    'gift_mode'            => true,
                    'header_alignment'     => 'center',
                ],
                'body_config' => [
                    'item_font_size'   => 12,
                    'price_alignment'  => 'right',
                    'show_sku'         => false,
                    'show_barcode'     => false,
                    'col_width_name'   => 70,
                    'col_width_qty'    => 10,
                    'col_width_price'  => 20,
                    'row_separator'    => false,
                    'totals_bold'      => true,
                    'hide_prices'      => true,
                    'show_gift_message' => true,
                ],
                'footer_config' => [
                    'zatca_qr_size'        => 0,
                    'show_receipt_number'   => false,
                    'show_cashier_name'    => false,
                    'custom_footer_en'     => 'A gift for someone special',
                    'custom_footer_ar'     => 'هدية لشخص مميز',
                    'thank_you_en'         => 'With love ♥',
                    'thank_you_ar'         => 'مع الحب ♥',
                    'show_social_handles'  => false,
                    'show_return_policy'   => true,
                    'return_policy_en'     => 'Gift exchanges accepted within 30 days.',
                    'return_policy_ar'     => 'يقبل استبدال الهدايا خلال 30 يوم.',
                    'show_exchange_barcode' => true,
                ],
                'zatca_qr_position' => 'footer',
                'show_bilingual'    => true,
                'is_active'         => true,
                'sort_order'        => 5,
            ],
            // ── 7. Restaurant Dine-in – table/server/tip focused ──
            [
                'name'       => 'Restaurant Dine-in',
                'name_ar'    => 'مطعم - طلب داخلي',
                'slug'       => 'restaurant_dinein_80mm',
                'paper_width' => 80,
                'header_config' => [
                    'logo_max_height'      => 60,
                    'store_name_font_size' => 20,
                    'store_name_bold'      => true,
                    'address_font_size'    => 11,
                    'show_vat_number'      => true,
                    'separator_style'      => 'dashes',
                    'show_phone'           => true,
                    'show_cr_number'       => false,
                    'show_table_number'    => true,
                    'show_server_name'     => true,
                    'show_guest_count'     => true,
                ],
                'body_config' => [
                    'item_font_size'   => 13,
                    'price_alignment'  => 'right',
                    'show_sku'         => false,
                    'show_barcode'     => false,
                    'col_width_name'   => 50,
                    'col_width_qty'    => 15,
                    'col_width_price'  => 35,
                    'row_separator'    => true,
                    'totals_bold'      => true,
                    'show_discount_line'  => true,
                    'show_vat_breakdown'  => true,
                    'show_modifiers'      => true,
                    'show_course_headers' => true,
                    'show_tip_line'       => true,
                    'tip_suggestions'     => [10, 15, 20],
                ],
                'footer_config' => [
                    'zatca_qr_size'       => 100,
                    'show_receipt_number'  => true,
                    'show_cashier_name'   => true,
                    'custom_footer_en'    => 'Thank you for dining with us!',
                    'custom_footer_ar'    => 'شكراً لتناول الطعام معنا!',
                    'thank_you_en'        => 'Bon appétit!',
                    'thank_you_ar'        => 'بالعافية!',
                    'show_social_handles' => true,
                    'show_return_policy'  => false,
                    'show_wifi_info'      => true,
                    'wifi_name'           => 'Guest-WiFi',
                    'wifi_password'       => 'welcome2024',
                ],
                'zatca_qr_position' => 'footer',
                'show_bilingual'    => true,
                'is_active'         => true,
                'sort_order'        => 6,
            ],
            // ── 8. Pharmacy Prescription – drug/dosage focused ──
            [
                'name'       => 'Pharmacy Prescription',
                'name_ar'    => 'وصفة صيدلية',
                'slug'       => 'pharmacy_prescription_80mm',
                'paper_width' => 80,
                'header_config' => [
                    'logo_max_height'      => 50,
                    'store_name_font_size' => 16,
                    'store_name_bold'      => true,
                    'address_font_size'    => 11,
                    'show_vat_number'      => true,
                    'separator_style'      => 'line',
                    'show_phone'           => true,
                    'show_cr_number'       => true,
                    'show_pharmacist_name' => true,
                    'show_license_number'  => true,
                ],
                'body_config' => [
                    'item_font_size'   => 12,
                    'price_alignment'  => 'right',
                    'show_sku'         => true,
                    'show_barcode'     => true,
                    'col_width_name'   => 45,
                    'col_width_qty'    => 15,
                    'col_width_price'  => 40,
                    'row_separator'    => true,
                    'totals_bold'      => true,
                    'show_discount_line' => true,
                    'show_vat_breakdown' => true,
                    'show_dosage'        => true,
                    'show_drug_schedule' => true,
                    'show_expiry_date'   => true,
                    'show_batch_number'  => true,
                    'show_interactions_warning' => true,
                ],
                'footer_config' => [
                    'zatca_qr_size'       => 120,
                    'show_receipt_number'  => true,
                    'show_cashier_name'   => true,
                    'custom_footer_en'    => 'Follow your doctor\'s instructions. | Emergency: 911',
                    'custom_footer_ar'    => 'اتبع تعليمات طبيبك. | الطوارئ: 911',
                    'thank_you_en'        => 'Get well soon!',
                    'thank_you_ar'        => 'سلامتك!',
                    'show_social_handles' => false,
                    'show_return_policy'  => true,
                    'return_policy_en'    => 'Medications cannot be returned once dispensed.',
                    'return_policy_ar'    => 'لا يمكن إرجاع الأدوية بعد صرفها.',
                ],
                'zatca_qr_position' => 'footer',
                'show_bilingual'    => true,
                'is_active'         => true,
                'sort_order'        => 7,
            ],
            // ── 9. E-Receipt Digital – QR-heavy paperless style ──
            [
                'name'       => 'E-Receipt Digital',
                'name_ar'    => 'إيصال رقمي إلكتروني',
                'slug'       => 'e_receipt_digital_80mm',
                'paper_width' => 80,
                'header_config' => [
                    'logo_max_height'      => 50,
                    'store_name_font_size' => 16,
                    'store_name_bold'      => true,
                    'address_font_size'    => 10,
                    'show_vat_number'      => true,
                    'separator_style'      => 'line',
                    'show_phone'           => false,
                    'show_cr_number'       => false,
                    'digital_mode'         => true,
                    'show_digital_qr'      => true,
                    'digital_qr_label_en'  => 'Scan for digital copy',
                    'digital_qr_label_ar'  => 'امسح للنسخة الرقمية',
                ],
                'body_config' => [
                    'item_font_size'   => 11,
                    'price_alignment'  => 'right',
                    'show_sku'         => false,
                    'show_barcode'     => false,
                    'col_width_name'   => 50,
                    'col_width_qty'    => 15,
                    'col_width_price'  => 35,
                    'row_separator'    => false,
                    'totals_bold'      => true,
                    'show_discount_line' => true,
                    'show_vat_breakdown' => true,
                    'compact_items'      => true,
                ],
                'footer_config' => [
                    'zatca_qr_size'       => 140,
                    'show_receipt_number'  => true,
                    'show_cashier_name'   => false,
                    'custom_footer_en'    => 'Go paperless! Scan QR for your digital receipt.',
                    'custom_footer_ar'    => 'بدون ورق! امسح QR لإيصالك الرقمي.',
                    'thank_you_en'        => 'Thank you for going green!',
                    'thank_you_ar'        => 'شكراً لاهتمامك بالبيئة!',
                    'show_social_handles' => true,
                    'show_return_policy'  => false,
                    'show_app_download'   => true,
                    'app_qr_label_en'     => 'Download our app',
                    'app_qr_label_ar'     => 'حمل تطبيقنا',
                ],
                'zatca_qr_position' => 'footer',
                'show_bilingual'    => true,
                'is_active'         => true,
                'sort_order'        => 8,
            ],
            // ── 10. A4 Full Page – formal invoice-style receipt ──
            [
                'name'       => 'A4 Full Page Invoice',
                'name_ar'    => 'فاتورة بحجم A4 كاملة',
                'slug'       => 'a4_full_page_invoice',
                'paper_width' => 210,
                'header_config' => [
                    'logo_max_height'      => 100,
                    'store_name_font_size' => 28,
                    'store_name_bold'      => true,
                    'address_font_size'    => 12,
                    'show_vat_number'      => true,
                    'separator_style'      => 'double_line',
                    'show_phone'           => true,
                    'show_cr_number'       => true,
                    'show_website'         => true,
                    'header_alignment'     => 'left',
                    'show_invoice_title'   => true,
                    'invoice_title_en'     => 'TAX INVOICE',
                    'invoice_title_ar'     => 'فاتورة ضريبية',
                    'show_customer_info'   => true,
                    'show_date_time'       => true,
                ],
                'body_config' => [
                    'item_font_size'   => 11,
                    'price_alignment'  => 'right',
                    'show_sku'         => true,
                    'show_barcode'     => false,
                    'col_width_name'   => 40,
                    'col_width_qty'    => 10,
                    'col_width_price'  => 15,
                    'col_width_unit_price' => 15,
                    'col_width_total'  => 20,
                    'row_separator'    => true,
                    'totals_bold'      => true,
                    'show_discount_line' => true,
                    'show_vat_breakdown' => true,
                    'show_line_totals'   => true,
                    'show_payment_method' => true,
                    'show_amount_in_words' => true,
                    'table_style'        => 'bordered',
                ],
                'footer_config' => [
                    'zatca_qr_size'       => 180,
                    'show_receipt_number'  => true,
                    'show_cashier_name'   => true,
                    'custom_footer_en'    => 'This is a computer-generated invoice.',
                    'custom_footer_ar'    => 'هذه فاتورة مولدة إلكترونياً.',
                    'thank_you_en'        => 'Thank you for your business.',
                    'thank_you_ar'        => 'شكراً لتعاملكم.',
                    'show_social_handles' => false,
                    'show_return_policy'  => true,
                    'return_policy_en'    => 'Terms & conditions apply. See store policy.',
                    'return_policy_ar'    => 'تطبق الشروط والأحكام. راجع سياسة المتجر.',
                    'show_signature_line' => true,
                    'signature_label_en'  => 'Authorized Signature',
                    'signature_label_ar'  => 'التوقيع المعتمد',
                    'show_stamp_area'     => true,
                ],
                'zatca_qr_position' => 'footer',
                'show_bilingual'    => true,
                'is_active'         => true,
                'sort_order'        => 9,
            ],
        ];

        foreach ($templates as $tpl) {
            ReceiptLayoutTemplate::updateOrCreate(['slug' => $tpl['slug']], $tpl);
        }
    }
}
