<?php

namespace Database\Seeders;

use App\Domain\ContentOnboarding\Enums\MarketplaceListingStatus;
use App\Domain\ContentOnboarding\Enums\MarketplacePricingType;
use App\Domain\ContentOnboarding\Enums\SubscriptionInterval;
use App\Domain\ContentOnboarding\Models\MarketplaceCategory;
use App\Domain\ContentOnboarding\Models\PosLayoutTemplate;
use App\Domain\ContentOnboarding\Models\TemplateMarketplaceListing;
use App\Domain\ContentOnboarding\Models\Theme;
use Illuminate\Database\Seeder;

class ComprehensiveMarketplaceListingSeeder extends Seeder
{
    public function run(): void
    {
        $cat   = fn (string $slug) => MarketplaceCategory::where('slug', $slug)->first()?->id;
        $theme = fn (string $slug) => Theme::where('slug', $slug)->first()?->id;
        $layout = fn (string $key) => PosLayoutTemplate::where('layout_key', $key)->first()?->id;

        $listings = [
            // ── 1. Free retail grid – approved ──
            [
                'pos_layout_template_id' => $layout('grocery_standard_grid'),
                'theme_id'               => $theme('light_classic'),
                'publisher_name'         => 'Thawani Official',
                'publisher_avatar_url'   => null,
                'title'                  => 'Classic Retail Grid',
                'title_ar'               => 'شبكة التجزئة الكلاسيكية',
                'description'            => 'A clean, optimized grid layout for retail stores. Features product images, category tabs, and a right-side cart panel. Ideal for general merchandise and clothing stores.',
                'description_ar'         => 'تخطيط شبكي نظيف ومحسّن لمتاجر التجزئة. يتميز بصور المنتجات وعلامات الفئات ولوحة السلة على الجانب الأيمن. مثالي لمتاجر البضائع العامة والملابس.',
                'short_description'      => 'Default retail grid with product images and categories',
                'short_description_ar'   => 'شبكة تجزئة افتراضية مع صور المنتجات والفئات',
                'preview_images'         => ['retail_grid_preview_1.jpg', 'retail_grid_preview_2.jpg'],
                'pricing_type'           => MarketplacePricingType::Free,
                'price_amount'           => 0,
                'price_currency'         => 'SAR',
                'subscription_interval'  => null,
                'category_id'            => $cat('retail'),
                'tags'                   => ['retail', 'grid', 'free', 'classic', 'beginner'],
                'version'                => '1.0.0',
                'changelog'              => 'Initial release',
                'download_count'         => 342,
                'average_rating'         => 4.5,
                'review_count'           => 28,
                'is_featured'            => true,
                'is_verified'            => true,
                'status'                 => MarketplaceListingStatus::Approved,
                'approved_at'            => now()->subDays(90),
                'published_at'           => now()->subDays(90),
            ],
            // ── 2. Restaurant table mgmt – one-time paid, approved ──
            [
                'pos_layout_template_id' => $layout('restaurant_table_management'),
                'theme_id'               => $theme('dark_mode'),
                'publisher_name'         => 'Thawani Official',
                'title'                  => 'Restaurant Table Manager Pro',
                'title_ar'               => 'مدير طاولات المطعم الاحترافي',
                'description'            => 'Interactive table management layout with drag-and-drop floor planning, real-time occupancy tracking, kitchen order integration, and split-bill support. Perfect for dine-in restaurants and cafés.',
                'description_ar'         => 'تخطيط إدارة طاولات تفاعلي مع تصميم أرضية بالسحب والإفلات وتتبع الإشغال في الوقت الفعلي وتكامل طلبات المطبخ ودعم تقسيم الفاتورة. مثالي للمطاعم والمقاهي.',
                'short_description'      => 'Pro table management with floor plan and kitchen integration',
                'short_description_ar'   => 'إدارة طاولات احترافية مع تصميم أرضي وتكامل المطبخ',
                'preview_images'         => ['restaurant_table_1.jpg', 'restaurant_table_2.jpg', 'restaurant_table_3.jpg'],
                'pricing_type'           => MarketplacePricingType::OneTime,
                'price_amount'           => 49.99,
                'price_currency'         => 'SAR',
                'subscription_interval'  => null,
                'category_id'            => $cat('restaurant'),
                'tags'                   => ['restaurant', 'table', 'dine-in', 'kitchen', 'floor-plan'],
                'version'                => '2.1.0',
                'changelog'              => 'v2.1: Added split-bill, improved floor editor',
                'download_count'         => 156,
                'average_rating'         => 4.8,
                'review_count'           => 42,
                'is_featured'            => true,
                'is_verified'            => true,
                'status'                 => MarketplaceListingStatus::Approved,
                'approved_at'            => now()->subDays(60),
                'published_at'           => now()->subDays(60),
            ],
            // ── 3. Pharmacy prescription – subscription, approved ──
            [
                'pos_layout_template_id' => $layout('pharmacy_prescription'),
                'theme_id'               => $theme('thawani_brand'),
                'publisher_name'         => 'HealthTech Solutions',
                'title'                  => 'PharmaCare Prescription Suite',
                'title_ar'               => 'مجموعة فارماكير للوصفات الطبية',
                'description'            => 'Comprehensive pharmacy layout with drug schedule tracking, patient management, prescription lookups, expiry alerts, and SFDA compliance features. Includes dark mode support.',
                'description_ar'         => 'تخطيط صيدلية شامل مع تتبع جداول الأدوية وإدارة المرضى والبحث في الوصفات وتنبيهات الانتهاء وميزات الامتثال لهيئة الغذاء والدواء. يتضمن دعم الوضع الداكن.',
                'short_description'      => 'Full pharmacy POS with SFDA compliance and drug tracking',
                'short_description_ar'   => 'نقطة بيع صيدلية كاملة مع الامتثال لهيئة الغذاء والدواء',
                'preview_images'         => ['pharmacy_suite_1.jpg', 'pharmacy_suite_2.jpg'],
                'pricing_type'           => MarketplacePricingType::Subscription,
                'price_amount'           => 29.99,
                'price_currency'         => 'SAR',
                'subscription_interval'  => SubscriptionInterval::Monthly,
                'category_id'            => $cat('pharmacy'),
                'tags'                   => ['pharmacy', 'prescription', 'SFDA', 'healthcare', 'compliance'],
                'version'                => '3.0.0',
                'changelog'              => 'v3.0: SFDA compliance updates, new drug schedule widget',
                'download_count'         => 89,
                'average_rating'         => 4.9,
                'review_count'           => 18,
                'is_featured'            => true,
                'is_verified'            => true,
                'status'                 => MarketplaceListingStatus::Approved,
                'approved_at'            => now()->subDays(30),
                'published_at'           => now()->subDays(30),
            ],
            // ── 4. Jewelry showcase – one-time, approved ──
            [
                'pos_layout_template_id' => $layout('jewelry_showcase'),
                'theme_id'               => $theme('royal_purple'),
                'publisher_name'         => 'LuxDesign Studio',
                'title'                  => 'Luxury Jewellery Showcase',
                'title_ar'               => 'معرض المجوهرات الفاخرة',
                'description'            => 'Elegant jewellery POS layout with gold rate integration, large product imagery, karat details, weight display, and certificate generation. Designed for high-end jewellery stores.',
                'description_ar'         => 'تخطيط نقطة بيع مجوهرات أنيق مع تكامل أسعار الذهب وصور كبيرة للمنتجات وتفاصيل العيار وعرض الوزن وإنشاء الشهادات. مصمم لمتاجر المجوهرات الراقية.',
                'short_description'      => 'Luxury jewellery POS with gold rate and karat tracking',
                'short_description_ar'   => 'نقطة بيع مجوهرات فاخرة مع أسعار الذهب وتتبع العيار',
                'preview_images'         => ['jewelry_showcase_1.jpg', 'jewelry_showcase_2.jpg'],
                'pricing_type'           => MarketplacePricingType::OneTime,
                'price_amount'           => 79.99,
                'price_currency'         => 'SAR',
                'subscription_interval'  => null,
                'category_id'            => $cat('premium'),
                'tags'                   => ['jewelry', 'luxury', 'gold', 'karat', 'premium'],
                'version'                => '1.2.0',
                'changelog'              => 'v1.2: Added making charge calculator',
                'download_count'         => 67,
                'average_rating'         => 4.7,
                'review_count'           => 12,
                'is_featured'            => false,
                'is_verified'            => true,
                'status'                 => MarketplaceListingStatus::Approved,
                'approved_at'            => now()->subDays(45),
                'published_at'           => now()->subDays(45),
            ],
            // ── 5. Grocery weight scale – free, approved ──
            [
                'pos_layout_template_id' => $layout('grocery_weight_scale'),
                'theme_id'               => $theme('forest_green'),
                'publisher_name'         => 'Thawani Official',
                'title'                  => 'Grocery Scale Integration',
                'title_ar'               => 'تكامل ميزان البقالة',
                'description'            => 'Grocery store layout with built-in weight scale widget, produce lookup by PLU code, and automatic price-by-weight calculation. Supports both metric and imperial units.',
                'description_ar'         => 'تخطيط محل بقالة مع أداة ميزان مدمجة والبحث عن المنتجات برمز PLU والحساب التلقائي للسعر بالوزن. يدعم الوحدات المترية والإمبراطورية.',
                'short_description'      => 'Scale-integrated grocery POS with PLU code support',
                'short_description_ar'   => 'نقطة بيع بقالة مع ميزان مدمج ودعم رمز PLU',
                'preview_images'         => ['grocery_scale_1.jpg'],
                'pricing_type'           => MarketplacePricingType::Free,
                'price_amount'           => 0,
                'price_currency'         => 'SAR',
                'subscription_interval'  => null,
                'category_id'            => $cat('grocery'),
                'tags'                   => ['grocery', 'scale', 'weight', 'produce', 'free'],
                'version'                => '1.0.0',
                'changelog'              => 'Initial release',
                'download_count'         => 210,
                'average_rating'         => 4.3,
                'review_count'           => 15,
                'is_featured'            => false,
                'is_verified'            => true,
                'status'                 => MarketplaceListingStatus::Approved,
                'approved_at'            => now()->subDays(75),
                'published_at'           => now()->subDays(75),
            ],
            // ── 6. Mobile IMEI tracker – subscription, approved ──
            [
                'pos_layout_template_id' => $layout('electronics_standard_grid'),
                'theme_id'               => $theme('midnight_blue'),
                'publisher_name'         => 'TechRetail Pro',
                'title'                  => 'IMEI Device Tracker',
                'title_ar'               => 'متتبع أجهزة IMEI',
                'description'            => 'Mobile phone shop layout with IMEI scanning, device history tracking, buyback valuation, warranty management, and accessory cross-sell suggestions.',
                'description_ar'         => 'تخطيط محل هواتف مع مسح IMEI وتتبع تاريخ الجهاز وتقييم إعادة الشراء وإدارة الضمان واقتراحات البيع المتقاطع للملحقات.',
                'short_description'      => 'Mobile shop POS with IMEI tracking and buyback',
                'short_description_ar'   => 'نقطة بيع محل هواتف مع تتبع IMEI وإعادة الشراء',
                'preview_images'         => ['imei_tracker_1.jpg', 'imei_tracker_2.jpg'],
                'pricing_type'           => MarketplacePricingType::Subscription,
                'price_amount'           => 19.99,
                'price_currency'         => 'SAR',
                'subscription_interval'  => SubscriptionInterval::Monthly,
                'category_id'            => $cat('electronics'),
                'tags'                   => ['mobile', 'IMEI', 'device', 'tracking', 'warranty'],
                'version'                => '2.0.0',
                'changelog'              => 'v2.0: Buyback module, accessory suggestions',
                'download_count'         => 124,
                'average_rating'         => 4.6,
                'review_count'           => 22,
                'is_featured'            => false,
                'is_verified'            => true,
                'status'                 => MarketplaceListingStatus::Approved,
                'approved_at'            => now()->subDays(40),
                'published_at'           => now()->subDays(40),
            ],
            // ── 7. Bakery custom orders – one-time, approved ──
            [
                'pos_layout_template_id' => $layout('bakery_custom_orders'),
                'theme_id'               => $theme('sunset_warmth'),
                'publisher_name'         => 'BakeSoft',
                'title'                  => 'Custom Cake Order Builder',
                'title_ar'               => 'منشئ طلبات الكيك المخصصة',
                'description'            => 'Bakery POS with custom cake configurator, production queue board, daily batch tracking, and held order management for pre-orders and walk-ins.',
                'description_ar'         => 'نقطة بيع مخبز مع أداة تصميم كيك مخصصة ولوحة طابور الإنتاج وتتبع الدفعات اليومية وإدارة الطلبات المعلقة للطلبات المسبقة والزيارات.',
                'short_description'      => 'Bakery POS with cake builder and production queue',
                'short_description_ar'   => 'نقطة بيع مخبز مع أداة تصميم الكيك وطابور الإنتاج',
                'preview_images'         => ['bakery_builder_1.jpg', 'bakery_builder_2.jpg'],
                'pricing_type'           => MarketplacePricingType::OneTime,
                'price_amount'           => 39.99,
                'price_currency'         => 'SAR',
                'subscription_interval'  => null,
                'category_id'            => $cat('restaurant'),
                'tags'                   => ['bakery', 'cake', 'custom', 'production', 'orders'],
                'version'                => '1.5.0',
                'changelog'              => 'v1.5: Improved production queue, added batch tracking',
                'download_count'         => 78,
                'average_rating'         => 4.4,
                'review_count'           => 9,
                'is_featured'            => false,
                'is_verified'            => true,
                'status'                 => MarketplaceListingStatus::Approved,
                'approved_at'            => now()->subDays(20),
                'published_at'           => now()->subDays(20),
            ],
            // ── 8. Ramadan seasonal – one-time, approved ──
            [
                'pos_layout_template_id' => $layout('fashion_compact_list'),
                'theme_id'               => $theme('desert_sand'),
                'publisher_name'         => 'Thawani Official',
                'title'                  => 'Ramadan Special Theme',
                'title_ar'               => 'سمة رمضان الخاصة',
                'description'            => 'Seasonal Ramadan layout with crescent moon branding, Iftar countdown timer, special offers banner, and bilingual Arabic-first display. Available for a limited time.',
                'description_ar'         => 'تخطيط رمضان الموسمي مع علامة الهلال ومؤقت العد التنازلي للإفطار ولافتة العروض الخاصة والعرض ثنائي اللغة بالعربية أولاً. متاح لفترة محدودة.',
                'short_description'      => 'Ramadan-themed layout with Iftar countdown',
                'short_description_ar'   => 'تخطيط بطابع رمضاني مع العد التنازلي للإفطار',
                'preview_images'         => ['ramadan_theme_1.jpg', 'ramadan_theme_2.jpg'],
                'pricing_type'           => MarketplacePricingType::OneTime,
                'price_amount'           => 14.99,
                'price_currency'         => 'SAR',
                'subscription_interval'  => null,
                'category_id'            => $cat('seasonal'),
                'tags'                   => ['ramadan', 'seasonal', 'arabic', 'iftar', 'limited'],
                'version'                => '1.0.0',
                'changelog'              => 'Ramadan 2025 edition',
                'download_count'         => 445,
                'average_rating'         => 4.9,
                'review_count'           => 67,
                'is_featured'            => true,
                'is_verified'            => true,
                'status'                 => MarketplaceListingStatus::Approved,
                'approved_at'            => now()->subDays(15),
                'published_at'           => now()->subDays(15),
            ],
            // ── 9. Flower shop – one-time, pending review ──
            [
                'pos_layout_template_id' => $layout('florist_standard_grid'),
                'theme_id'               => $theme('ocean_breeze'),
                'publisher_name'         => 'FloralTech',
                'title'                  => 'Floral Arrangement Studio',
                'title_ar'               => 'استوديو تنسيق الزهور',
                'description'            => 'Beautiful flower shop layout with arrangement builder, freshness indicators, gift messaging, delivery scheduling, and weather-aware recommendations.',
                'description_ar'         => 'تخطيط جميل لمحل الزهور مع منشئ التنسيقات ومؤشرات النضارة ورسائل الهدايا وجدولة التوصيل والتوصيات المرتبطة بالطقس.',
                'short_description'      => 'Flower shop POS with arrangement builder',
                'short_description_ar'   => 'نقطة بيع محل زهور مع منشئ التنسيقات',
                'preview_images'         => ['floral_studio_1.jpg'],
                'pricing_type'           => MarketplacePricingType::OneTime,
                'price_amount'           => 34.99,
                'price_currency'         => 'SAR',
                'subscription_interval'  => null,
                'category_id'            => $cat('services'),
                'tags'                   => ['flower', 'floral', 'arrangement', 'gift', 'delivery'],
                'version'                => '1.0.0',
                'changelog'              => 'Initial submission',
                'download_count'         => 0,
                'average_rating'         => 0,
                'review_count'           => 0,
                'is_featured'            => false,
                'is_verified'            => false,
                'status'                 => MarketplaceListingStatus::PendingReview,
                'approved_at'            => null,
                'published_at'           => null,
            ],
            // ── 10. Service appointment – subscription, draft ──
            [
                'pos_layout_template_id' => $layout('fashion_standard_grid'),
                'theme_id'               => $theme('high_contrast'),
                'publisher_name'         => 'ServicePro Labs',
                'title'                  => 'Appointment Booking Suite',
                'title_ar'               => 'مجموعة حجز المواعيد',
                'description'            => 'Complete service business POS with appointment calendar, customer history, staff scheduling, no-show tracking, and automated reminders. Ideal for salons and clinics.',
                'description_ar'         => 'نقطة بيع كاملة للأعمال الخدمية مع تقويم المواعيد وسجل العملاء وجدولة الموظفين وتتبع عدم الحضور والتذكيرات الآلية. مثالي للصالونات والعيادات.',
                'short_description'      => 'Service POS with booking and staff scheduling',
                'short_description_ar'   => 'نقطة بيع خدمات مع الحجز وجدولة الموظفين',
                'preview_images'         => [],
                'pricing_type'           => MarketplacePricingType::Subscription,
                'price_amount'           => 24.99,
                'price_currency'         => 'SAR',
                'subscription_interval'  => SubscriptionInterval::Monthly,
                'category_id'            => $cat('services'),
                'tags'                   => ['service', 'appointment', 'booking', 'salon', 'clinic'],
                'version'                => '0.9.0',
                'changelog'              => 'Beta release',
                'download_count'         => 0,
                'average_rating'         => 0,
                'review_count'           => 0,
                'is_featured'            => false,
                'is_verified'            => false,
                'status'                 => MarketplaceListingStatus::Draft,
                'approved_at'            => null,
                'published_at'           => null,
            ],
        ];

        foreach ($listings as $data) {
            TemplateMarketplaceListing::updateOrCreate(
                [
                    'pos_layout_template_id' => $data['pos_layout_template_id'],
                    'title' => $data['title'],
                ],
                $data,
            );
        }
    }
}
