<?php

namespace Database\Seeders;

use App\Domain\ContentOnboarding\Models\BusinessType;
use App\Domain\ContentOnboarding\Models\LayoutWidget;
use App\Domain\ContentOnboarding\Models\LayoutWidgetPlacement;
use App\Domain\ContentOnboarding\Models\PosLayoutTemplate;
use Illuminate\Database\Seeder;

class CreativePosLayoutSeeder extends Seeder
{
    /**
     * 60 creative POS layout templates — at least 20 for left-handed users.
     *
     * Business types (8): grocery, restaurant, pharmacy, bakery,
     *                      electronics, florist, jewelry, fashion
     *
     * Widget slugs (20): product_grid, cart_panel, payment_buttons,
     *     category_bar, search_bar, customer_info, order_summary,
     *     quick_actions, receipt_preview, clock_widget, store_branding,
     *     loyalty_points, promotional_banner, numpad, custom_html,
     *     held_orders, staff_notes, recent_transactions, weather_widget,
     *     table_map
     */
    public function run(): void
    {
        $bts     = BusinessType::where('is_active', true)->get()->keyBy('slug');
        $widgets = LayoutWidget::all()->keyBy('slug');
        $wid     = fn (string $slug) => $widgets->get($slug)?->id;

        $sortBase = 10; // start above existing sort_order values

        foreach ($this->layouts() as $i => $def) {
            $bt = $bts->get($def['bt']);
            if (! $bt) {
                continue;
            }

            $layout = PosLayoutTemplate::updateOrCreate(
                ['layout_key' => $def['key']],
                [
                    'business_type_id'  => $bt->id,
                    'name'              => $def['name'],
                    'name_ar'           => $def['name_ar'],
                    'description'       => $def['desc'],
                    'config'            => $def['config'],
                    'is_default'        => false,
                    'is_active'         => true,
                    'sort_order'        => $sortBase + $i,
                    'canvas_columns'    => $def['canvas'][0] ?? 24,
                    'canvas_rows'       => $def['canvas'][1] ?? 16,
                    'canvas_gap_px'     => $def['canvas'][2] ?? 4,
                    'canvas_padding_px' => $def['canvas'][3] ?? 8,
                    'breakpoints'       => $def['breakpoints'] ?? ['tablet' => ['columns' => 12, 'rows' => 12]],
                    'version'           => '1.0.0',
                    'is_locked'         => false,
                    'published_at'      => now(),
                ],
            );

            $this->syncPlacements($layout, $def['widgets'], $wid);
        }
    }

    // ─── Placement Sync ──────────────────────────────────────

    private function syncPlacements(PosLayoutTemplate $layout, array $placements, \Closure $wid): void
    {
        LayoutWidgetPlacement::where('pos_layout_template_id', $layout->id)->delete();

        foreach ($placements as $i => $p) {
            [$slug, $x, $y, $w, $h, $props, $z] = $p;
            $widgetId = $wid($slug);
            if (! $widgetId) {
                continue;
            }

            LayoutWidgetPlacement::create([
                'pos_layout_template_id' => $layout->id,
                'layout_widget_id'       => $widgetId,
                'instance_key'           => $slug . '_' . $i,
                'grid_x'                 => $x,
                'grid_y'                 => $y,
                'grid_w'                 => $w,
                'grid_h'                 => $h,
                'z_index'                => $z,
                'properties'             => ! empty($props) ? $props : [],
                'is_visible'             => true,
            ]);
        }
    }

    // ─── 60 Layout Definitions ───────────────────────────────

    private function layouts(): array
    {
        return [
            // ================================================================
            // LEFT-HANDED LAYOUTS (24 total — 3 per business type)
            // Cart on LEFT, products on RIGHT, quick actions left-side
            // ================================================================

            // ── Grocery Left-Handed (3) ──────────────────────
            [
                'bt'      => 'grocery',
                'key'     => 'grocery_lefty_express',
                'name'    => 'Left-Hand Express Checkout',
                'name_ar' => 'الدفع السريع لليد اليسرى',
                'desc'    => 'Fast-scan grocery layout with cart and payment on the left for left-handed cashiers',
                'config'  => ['layout_type' => 'grid', 'cart_position' => 'left', 'cart_width' => 35, 'show_categories' => true, 'category_style' => 'tabs', 'product_display' => 'grid', 'product_columns' => 4, 'show_images' => true, 'quick_actions' => ['discount', 'hold', 'void', 'weigh'], 'payment_buttons' => ['cash', 'card', 'wallet']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['cart_panel',       0, 0, 8, 10, [], 2],
                    ['order_summary',    0, 10, 8, 2, [], 2],
                    ['payment_buttons',  0, 12, 8, 2, [], 2],
                    ['quick_actions',    0, 14, 8, 2, [], 2],
                    ['search_bar',       8, 0, 16, 1, ['show_barcode_button' => true], 1],
                    ['category_bar',     8, 1, 16, 2, [], 1],
                    ['product_grid',     8, 3, 16, 13, ['columns' => 4], 1],
                ],
            ],
            [
                'bt'      => 'grocery',
                'key'     => 'grocery_lefty_scale',
                'name'    => 'Left-Hand Scale & Weigh',
                'name_ar' => 'الميزان لليد اليسرى',
                'desc'    => 'Grocery layout with left-side cart and integrated scale display for left-handed operators',
                'config'  => ['layout_type' => 'weight_integrated', 'cart_position' => 'left', 'cart_width' => 35, 'show_categories' => true, 'category_style' => 'tabs', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['discount', 'hold', 'void', 'weigh'], 'payment_buttons' => ['cash', 'card'], 'scale_integration' => true],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['cart_panel',       0, 0, 8, 8, [], 2],
                    ['numpad',           0, 8, 4, 4, [], 2],
                    ['custom_html',      4, 8, 4, 4, ['html_content' => '<div class="scale-display text-center"><strong>Scale</strong><br>0.000 kg</div>'], 2],
                    ['payment_buttons',  0, 12, 8, 2, [], 2],
                    ['quick_actions',    0, 14, 8, 2, [], 2],
                    ['search_bar',       8, 0, 16, 1, ['show_barcode_button' => true], 1],
                    ['category_bar',     8, 1, 16, 2, [], 1],
                    ['product_grid',     8, 3, 16, 11, ['columns' => 3], 1],
                    ['order_summary',    8, 14, 16, 2, [], 1],
                ],
            ],
            [
                'bt'      => 'grocery',
                'key'     => 'grocery_lefty_loyalty',
                'name'    => 'Left-Hand Loyalty Checkout',
                'name_ar' => 'الدفع بالولاء لليد اليسرى',
                'desc'    => 'Left-handed grocery layout with prominent loyalty points display and member pricing',
                'config'  => ['layout_type' => 'grid', 'cart_position' => 'left', 'cart_width' => 35, 'show_categories' => true, 'category_style' => 'icons', 'product_display' => 'grid', 'product_columns' => 4, 'show_images' => true, 'quick_actions' => ['discount', 'hold', 'refund'], 'payment_buttons' => ['cash', 'card', 'wallet', 'loyalty_redeem']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['cart_panel',       0, 0, 8, 8, [], 2],
                    ['loyalty_points',   0, 8, 8, 2, [], 2],
                    ['order_summary',    0, 10, 8, 2, [], 2],
                    ['payment_buttons',  0, 12, 8, 2, [], 2],
                    ['quick_actions',    0, 14, 8, 2, [], 2],
                    ['search_bar',       8, 0, 16, 1, [], 1],
                    ['category_bar',     8, 1, 16, 2, ['style' => 'icons'], 1],
                    ['product_grid',     8, 3, 16, 11, ['columns' => 4], 1],
                    ['promotional_banner', 8, 14, 16, 2, [], 1],
                ],
            ],

            // ── Restaurant Left-Handed (3) ───────────────────
            [
                'bt'      => 'restaurant',
                'key'     => 'restaurant_lefty_quick_service',
                'name'    => 'Left-Hand Quick Service',
                'name_ar' => 'الخدمة السريعة لليد اليسرى',
                'desc'    => 'Fast food / quick-service restaurant layout with left-side order panel',
                'config'  => ['layout_type' => 'quick_service', 'cart_position' => 'left', 'cart_width' => 35, 'show_categories' => true, 'category_style' => 'icons', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['hold', 'void', 'split_bill', 'print_kitchen'], 'payment_buttons' => ['cash', 'card', 'wallet']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['cart_panel',       0, 0, 8, 9, [], 2],
                    ['order_summary',    0, 9, 8, 2, [], 2],
                    ['payment_buttons',  0, 11, 8, 2, [], 2],
                    ['quick_actions',    0, 13, 8, 3, [], 2],
                    ['search_bar',       8, 0, 16, 1, [], 1],
                    ['category_bar',     8, 1, 16, 2, ['style' => 'icons'], 1],
                    ['product_grid',     8, 3, 16, 13, ['columns' => 3], 1],
                ],
            ],
            [
                'bt'      => 'restaurant',
                'key'     => 'restaurant_lefty_table_map',
                'name'    => 'Left-Hand Table Service',
                'name_ar' => 'خدمة الطاولات لليد اليسرى',
                'desc'    => 'Dine-in table management with left-side cart for left-handed waiters using tablets',
                'config'  => ['layout_type' => 'table_management', 'cart_position' => 'left', 'cart_width' => 30, 'show_categories' => true, 'category_style' => 'tabs', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['hold', 'split_bill', 'void', 'print_kitchen']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['cart_panel',       0, 0, 7, 10, [], 2],
                    ['payment_buttons',  0, 10, 7, 2, [], 2],
                    ['quick_actions',    0, 12, 7, 2, [], 2],
                    ['held_orders',      0, 14, 7, 2, [], 2],
                    ['table_map',        7, 0, 9, 8, [], 1],
                    ['search_bar',       16, 0, 8, 1, [], 1],
                    ['category_bar',     7, 8, 9, 2, [], 1],
                    ['product_grid',     7, 10, 9, 6, ['columns' => 3], 1],
                    ['order_summary',    16, 1, 8, 5, [], 1],
                    ['customer_info',    16, 6, 8, 5, [], 1],
                    ['staff_notes',      16, 11, 8, 5, [], 1],
                ],
            ],
            [
                'bt'      => 'restaurant',
                'key'     => 'restaurant_lefty_kitchen_display',
                'name'    => 'Left-Hand Kitchen Display',
                'name_ar' => 'شاشة المطبخ لليد اليسرى',
                'desc'    => 'Kitchen-facing layout with left-side order queue and prominent held orders for left-handed chefs',
                'config'  => ['layout_type' => 'kitchen_display', 'cart_position' => 'left', 'cart_width' => 35, 'show_categories' => true, 'category_style' => 'tabs', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['hold', 'void', 'print_kitchen', 'rush']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['cart_panel',       0, 0, 8, 7, [], 2],
                    ['held_orders',      0, 7, 8, 5, ['max_display' => 10], 2],
                    ['payment_buttons',  0, 12, 8, 2, [], 2],
                    ['quick_actions',    0, 14, 8, 2, [], 2],
                    ['search_bar',       8, 0, 16, 1, [], 1],
                    ['category_bar',     8, 1, 16, 2, [], 1],
                    ['product_grid',     8, 3, 16, 9, ['columns' => 3], 1],
                    ['clock_widget',     8, 12, 8, 2, [], 1],
                    ['staff_notes',      16, 12, 8, 4, [], 1],
                    ['order_summary',    8, 14, 8, 2, [], 1],
                ],
            ],

            // ── Pharmacy Left-Handed (3) ─────────────────────
            [
                'bt'      => 'pharmacy',
                'key'     => 'pharmacy_lefty_prescription',
                'name'    => 'Left-Hand Prescription',
                'name_ar' => 'الوصفات لليد اليسرى',
                'desc'    => 'Pharmacy counter optimized for left-handed pharmacists with cart and patient info on the left',
                'config'  => ['layout_type' => 'prescription', 'cart_position' => 'left', 'cart_width' => 35, 'show_categories' => true, 'category_style' => 'tabs', 'product_display' => 'list', 'product_columns' => 1, 'show_images' => true, 'quick_actions' => ['discount', 'hold', 'refund', 'print_label'], 'payment_buttons' => ['cash', 'card', 'insurance'], 'show_drug_schedule' => true],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['cart_panel',       0, 0, 8, 8, [], 2],
                    ['customer_info',    0, 8, 8, 4, ['show_purchase_history' => true], 2],
                    ['payment_buttons',  0, 12, 8, 2, [], 2],
                    ['quick_actions',    0, 14, 8, 2, [], 2],
                    ['search_bar',       8, 0, 16, 2, ['placeholder' => 'Search medicine, barcode, generic...', 'auto_focus' => true], 1],
                    ['category_bar',     8, 2, 16, 2, ['style' => 'pills'], 1],
                    ['product_grid',     8, 4, 16, 8, ['columns' => 1, 'show_stock' => true], 1],
                    ['staff_notes',      8, 12, 8, 4, [], 1],
                    ['order_summary',    16, 12, 8, 4, [], 1],
                ],
            ],
            [
                'bt'      => 'pharmacy',
                'key'     => 'pharmacy_lefty_otc',
                'name'    => 'Left-Hand OTC Counter',
                'name_ar' => 'عداد OTC لليد اليسرى',
                'desc'    => 'Over-the-counter sales layout for left-handed staff with fast product lookup',
                'config'  => ['layout_type' => 'grid', 'cart_position' => 'left', 'cart_width' => 35, 'show_categories' => true, 'category_style' => 'icons', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['discount', 'hold', 'refund'], 'payment_buttons' => ['cash', 'card']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['cart_panel',       0, 0, 8, 10, [], 2],
                    ['order_summary',    0, 10, 8, 2, [], 2],
                    ['payment_buttons',  0, 12, 8, 2, [], 2],
                    ['quick_actions',    0, 14, 8, 2, [], 2],
                    ['search_bar',       8, 0, 16, 1, ['auto_focus' => true], 1],
                    ['category_bar',     8, 1, 16, 2, ['style' => 'icons'], 1],
                    ['product_grid',     8, 3, 16, 13, ['columns' => 3], 1],
                ],
            ],
            [
                'bt'      => 'pharmacy',
                'key'     => 'pharmacy_lefty_insurance_billing',
                'name'    => 'Left-Hand Insurance Billing',
                'name_ar' => 'فواتير التأمين لليد اليسرى',
                'desc'    => 'Pharmacy layout focused on insurance claim processing with left-side cart for left-handed pharmacists',
                'config'  => ['layout_type' => 'insurance_billing', 'cart_position' => 'left', 'cart_width' => 40, 'show_categories' => true, 'category_style' => 'tabs', 'product_display' => 'list', 'product_columns' => 1, 'show_images' => false, 'quick_actions' => ['discount', 'hold', 'print_label', 'insurance_claim'], 'payment_buttons' => ['cash', 'card', 'insurance']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['cart_panel',       0, 0, 10, 7, [], 2],
                    ['customer_info',    0, 7, 10, 3, ['show_purchase_history' => true, 'show_insurance' => true], 2],
                    ['order_summary',    0, 10, 10, 2, [], 2],
                    ['payment_buttons',  0, 12, 10, 2, [], 2],
                    ['quick_actions',    0, 14, 10, 2, [], 2],
                    ['search_bar',       10, 0, 14, 2, ['auto_focus' => true], 1],
                    ['category_bar',     10, 2, 14, 2, [], 1],
                    ['product_grid',     10, 4, 14, 8, ['columns' => 1], 1],
                    ['recent_transactions', 10, 12, 14, 4, ['max_rows' => 6], 1],
                ],
            ],

            // ── Bakery Left-Handed (3) ───────────────────────
            [
                'bt'      => 'bakery',
                'key'     => 'bakery_lefty_counter',
                'name'    => 'Left-Hand Bakery Counter',
                'name_ar' => 'كاونتر المخبز لليد اليسرى',
                'desc'    => 'Walk-in bakery counter with left-side cart and large product images for left-handed cashiers',
                'config'  => ['layout_type' => 'grid', 'cart_position' => 'left', 'cart_width' => 35, 'show_categories' => true, 'category_style' => 'icons', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['discount', 'hold', 'gift_box', 'custom_cake'], 'payment_buttons' => ['cash', 'card']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['cart_panel',       0, 0, 8, 10, [], 2],
                    ['order_summary',    0, 10, 8, 2, [], 2],
                    ['payment_buttons',  0, 12, 8, 2, [], 2],
                    ['quick_actions',    0, 14, 8, 2, [], 2],
                    ['search_bar',       8, 0, 16, 1, [], 1],
                    ['category_bar',     8, 1, 16, 2, ['style' => 'icons'], 1],
                    ['product_grid',     8, 3, 16, 13, ['columns' => 3, 'show_images' => true], 1],
                ],
            ],
            [
                'bt'      => 'bakery',
                'key'     => 'bakery_lefty_production',
                'name'    => 'Left-Hand Production Queue',
                'name_ar' => 'قائمة الإنتاج لليد اليسرى',
                'desc'    => 'Bakery layout with left-side order queue and production tracking for left-handed bakers',
                'config'  => ['layout_type' => 'production_queue', 'cart_position' => 'left', 'cart_width' => 35, 'show_categories' => true, 'category_style' => 'tabs', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['discount', 'hold', 'custom_cake', 'gift_box']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['cart_panel',       0, 0, 8, 7, [], 2],
                    ['held_orders',      0, 7, 8, 5, ['max_display' => 8], 2],
                    ['payment_buttons',  0, 12, 8, 2, [], 2],
                    ['quick_actions',    0, 14, 8, 2, [], 2],
                    ['search_bar',       8, 0, 12, 1, [], 1],
                    ['clock_widget',     20, 0, 4, 1, [], 1],
                    ['category_bar',     8, 1, 16, 2, [], 1],
                    ['product_grid',     8, 3, 16, 9, ['columns' => 3], 1],
                    ['staff_notes',      8, 12, 8, 4, [], 1],
                    ['order_summary',    16, 12, 8, 4, [], 1],
                ],
            ],
            [
                'bt'      => 'bakery',
                'key'     => 'bakery_lefty_cake_builder',
                'name'    => 'Left-Hand Cake Builder',
                'name_ar' => 'منشئ الكيك لليد اليسرى',
                'desc'    => 'Custom cake order builder with left-side configuration panel for left-handed decorators',
                'config'  => ['layout_type' => 'custom_order', 'cart_position' => 'left', 'cart_width' => 40, 'show_categories' => true, 'category_style' => 'tabs', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['hold', 'custom_cake', 'gift_box', 'delivery']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['cart_panel',       0, 0, 10, 8, [], 2],
                    ['customer_info',    0, 8, 10, 4, [], 2],
                    ['payment_buttons',  0, 12, 10, 2, [], 2],
                    ['quick_actions',    0, 14, 10, 2, [], 2],
                    ['search_bar',       10, 0, 14, 1, [], 1],
                    ['category_bar',     10, 1, 14, 2, [], 1],
                    ['product_grid',     10, 3, 14, 9, ['columns' => 3], 1],
                    ['staff_notes',      10, 12, 7, 4, [], 1],
                    ['order_summary',    17, 12, 7, 4, [], 1],
                ],
            ],

            // ── Electronics Left-Handed (3) ──────────────────
            [
                'bt'      => 'electronics',
                'key'     => 'electronics_lefty_imei',
                'name'    => 'Left-Hand IMEI Tracker',
                'name_ar' => 'تتبع IMEI لليد اليسرى',
                'desc'    => 'IMEI / serial number scanning layout with left-side cart for left-handed staff',
                'config'  => ['layout_type' => 'imei_focused', 'cart_position' => 'left', 'cart_width' => 35, 'show_categories' => true, 'category_style' => 'tabs', 'product_display' => 'list', 'product_columns' => 1, 'show_images' => true, 'quick_actions' => ['discount', 'hold', 'warranty_check', 'buyback'], 'payment_buttons' => ['cash', 'card', 'installment'], 'imei_tracking' => true],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['cart_panel',       0, 0, 8, 8, [], 2],
                    ['customer_info',    0, 8, 8, 4, ['show_purchase_history' => true], 2],
                    ['payment_buttons',  0, 12, 8, 2, [], 2],
                    ['quick_actions',    0, 14, 8, 2, [], 2],
                    ['search_bar',       8, 0, 16, 2, ['placeholder' => 'Scan IMEI, barcode, or model...', 'auto_focus' => true], 1],
                    ['category_bar',     8, 2, 16, 2, [], 1],
                    ['product_grid',     8, 4, 16, 8, ['columns' => 1], 1],
                    ['recent_transactions', 8, 12, 16, 4, ['max_rows' => 5], 1],
                ],
            ],
            [
                'bt'      => 'electronics',
                'key'     => 'electronics_lefty_showroom',
                'name'    => 'Left-Hand Showroom',
                'name_ar' => 'صالة العرض لليد اليسرى',
                'desc'    => 'Large-image showroom layout for electronics demos with left-side checkout panel',
                'config'  => ['layout_type' => 'showroom', 'cart_position' => 'left', 'cart_width' => 30, 'show_categories' => true, 'category_style' => 'icons', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['discount', 'hold', 'warranty_check', 'compare'], 'payment_buttons' => ['cash', 'card', 'installment']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['cart_panel',       0, 0, 7, 10, [], 2],
                    ['order_summary',    0, 10, 7, 2, [], 2],
                    ['payment_buttons',  0, 12, 7, 2, [], 2],
                    ['quick_actions',    0, 14, 7, 2, [], 2],
                    ['store_branding',   7, 0, 5, 2, [], 1],
                    ['search_bar',       12, 0, 12, 2, [], 1],
                    ['category_bar',     7, 2, 17, 2, ['style' => 'icons'], 1],
                    ['product_grid',     7, 4, 17, 12, ['columns' => 3, 'show_images' => true], 1],
                ],
            ],
            [
                'bt'      => 'electronics',
                'key'     => 'electronics_lefty_repair',
                'name'    => 'Left-Hand Repair Counter',
                'name_ar' => 'كاونتر الصيانة لليد اليسرى',
                'desc'    => 'Repair intake and parts lookup layout with left-side order panel for left-handed technicians',
                'config'  => ['layout_type' => 'repair_counter', 'cart_position' => 'left', 'cart_width' => 40, 'show_categories' => true, 'category_style' => 'sidebar', 'product_display' => 'list', 'product_columns' => 1, 'show_images' => false, 'quick_actions' => ['hold', 'refund', 'warranty_check', 'print_label']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['cart_panel',       0, 0, 10, 7, [], 2],
                    ['staff_notes',      0, 7, 10, 3, [], 2],
                    ['customer_info',    0, 10, 10, 2, ['show_purchase_history' => true], 2],
                    ['payment_buttons',  0, 12, 10, 2, [], 2],
                    ['quick_actions',    0, 14, 10, 2, [], 2],
                    ['search_bar',       10, 0, 14, 2, ['auto_focus' => true], 1],
                    ['category_bar',     10, 2, 4, 14, ['style' => 'sidebar'], 1],
                    ['product_grid',     14, 2, 10, 10, ['columns' => 1, 'show_images' => false], 1],
                    ['order_summary',    14, 12, 10, 4, [], 1],
                ],
            ],

            // ── Florist Left-Handed (3) ──────────────────────
            [
                'bt'      => 'florist',
                'key'     => 'florist_lefty_arrangement',
                'name'    => 'Left-Hand Floral Studio',
                'name_ar' => 'استوديو الزهور لليد اليسرى',
                'desc'    => 'Floral arrangement and bouquet builder with left-side cart for left-handed florists',
                'config'  => ['layout_type' => 'arrangement_builder', 'cart_position' => 'left', 'cart_width' => 35, 'show_categories' => true, 'category_style' => 'icons', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['discount', 'gift_card', 'delivery', 'custom_message'], 'payment_buttons' => ['cash', 'card'], 'show_freshness' => true],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['cart_panel',       0, 0, 8, 8, [], 2],
                    ['customer_info',    0, 8, 8, 4, [], 2],
                    ['payment_buttons',  0, 12, 8, 2, [], 2],
                    ['quick_actions',    0, 14, 8, 2, [], 2],
                    ['store_branding',   8, 0, 6, 2, [], 1],
                    ['search_bar',       14, 0, 10, 1, [], 1],
                    ['weather_widget',   14, 1, 10, 1, [], 1],
                    ['category_bar',     8, 2, 16, 2, ['style' => 'icons'], 1],
                    ['product_grid',     8, 4, 16, 12, ['columns' => 3], 1],
                ],
            ],
            [
                'bt'      => 'florist',
                'key'     => 'florist_lefty_delivery',
                'name'    => 'Left-Hand Delivery Hub',
                'name_ar' => 'مركز التوصيل لليد اليسرى',
                'desc'    => 'Left-handed delivery management layout with order tracking and scheduling on the left',
                'config'  => ['layout_type' => 'delivery_hub', 'cart_position' => 'left', 'cart_width' => 40, 'show_categories' => true, 'category_style' => 'tabs', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['hold', 'delivery', 'custom_message', 'gift_card']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['cart_panel',       0, 0, 10, 6, [], 2],
                    ['held_orders',      0, 6, 10, 4, ['max_display' => 6], 2],
                    ['order_summary',    0, 10, 10, 2, [], 2],
                    ['payment_buttons',  0, 12, 10, 2, [], 2],
                    ['quick_actions',    0, 14, 10, 2, [], 2],
                    ['search_bar',       10, 0, 14, 1, [], 1],
                    ['category_bar',     10, 1, 14, 2, [], 1],
                    ['product_grid',     10, 3, 14, 9, ['columns' => 3], 1],
                    ['clock_widget',     10, 12, 7, 2, [], 1],
                    ['customer_info',    17, 12, 7, 4, [], 1],
                    ['staff_notes',      10, 14, 7, 2, [], 1],
                ],
            ],
            [
                'bt'      => 'florist',
                'key'     => 'florist_lefty_event',
                'name'    => 'Left-Hand Event Planner',
                'name_ar' => 'مخطط المناسبات لليد اليسرى',
                'desc'    => 'Event / wedding floral planning with left-side cart and customer notes for left-handed planners',
                'config'  => ['layout_type' => 'event_planner', 'cart_position' => 'left', 'cart_width' => 35, 'show_categories' => true, 'category_style' => 'icons', 'product_display' => 'grid', 'product_columns' => 4, 'show_images' => true, 'quick_actions' => ['hold', 'delivery', 'custom_message', 'gift_card']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['cart_panel',       0, 0, 8, 7, [], 2],
                    ['customer_info',    0, 7, 8, 3, ['show_purchase_history' => true], 2],
                    ['staff_notes',      0, 10, 8, 2, [], 2],
                    ['payment_buttons',  0, 12, 8, 2, [], 2],
                    ['quick_actions',    0, 14, 8, 2, [], 2],
                    ['search_bar',       8, 0, 16, 1, [], 1],
                    ['category_bar',     8, 1, 16, 2, ['style' => 'icons'], 1],
                    ['product_grid',     8, 3, 16, 13, ['columns' => 4], 1],
                ],
            ],

            // ── Jewelry Left-Handed (3) ──────────────────────
            [
                'bt'      => 'jewelry',
                'key'     => 'jewelry_lefty_luxury',
                'name'    => 'Left-Hand Luxury Counter',
                'name_ar' => 'كاونتر الفخامة لليد اليسرى',
                'desc'    => 'Premium jewelry counter with gold rate display and left-side cart for left-handed jewelers',
                'config'  => ['layout_type' => 'luxury_grid', 'cart_position' => 'left', 'cart_width' => 30, 'show_categories' => true, 'category_style' => 'icons', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['discount', 'hold', 'gift_wrap', 'certificate'], 'payment_buttons' => ['cash', 'card', 'bank_transfer'], 'show_gold_rate' => true],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['store_branding',   0, 0, 7, 2, [], 2],
                    ['cart_panel',       0, 2, 7, 8, [], 2],
                    ['order_summary',    0, 10, 7, 2, [], 2],
                    ['payment_buttons',  0, 12, 7, 2, [], 2],
                    ['quick_actions',    0, 14, 7, 2, [], 2],
                    ['custom_html',      7, 0, 17, 1, ['html_content' => '<div class="gold-rate text-center">Gold 24K: --- SAR/g | 22K: --- SAR/g | 21K: --- SAR/g</div>'], 1],
                    ['search_bar',       7, 1, 17, 1, [], 1],
                    ['category_bar',     7, 2, 17, 2, ['style' => 'icons'], 1],
                    ['product_grid',     7, 4, 17, 12, ['columns' => 3, 'show_images' => true], 1],
                ],
            ],
            [
                'bt'      => 'jewelry',
                'key'     => 'jewelry_lefty_appraisal',
                'name'    => 'Left-Hand Appraisal Desk',
                'name_ar' => 'مكتب التقييم لليد اليسرى',
                'desc'    => 'Jewelry appraisal and buyback layout with customer history and left-side panel',
                'config'  => ['layout_type' => 'appraisal', 'cart_position' => 'left', 'cart_width' => 40, 'show_categories' => true, 'category_style' => 'tabs', 'product_display' => 'list', 'product_columns' => 1, 'show_images' => true, 'quick_actions' => ['hold', 'certificate', 'buyback', 'gift_wrap'], 'show_gold_rate' => true, 'show_weight' => true],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['cart_panel',       0, 0, 10, 6, [], 2],
                    ['customer_info',    0, 6, 10, 4, ['show_purchase_history' => true, 'show_loyalty_points' => true], 2],
                    ['order_summary',    0, 10, 10, 2, [], 2],
                    ['payment_buttons',  0, 12, 10, 2, [], 2],
                    ['quick_actions',    0, 14, 10, 2, [], 2],
                    ['search_bar',       10, 0, 14, 1, [], 1],
                    ['custom_html',      10, 1, 14, 1, ['html_content' => '<div class="gold-rate">Gold 24K: --- SAR/g</div>'], 1],
                    ['category_bar',     10, 2, 14, 2, [], 1],
                    ['product_grid',     10, 4, 14, 8, ['columns' => 1], 1],
                    ['recent_transactions', 10, 12, 14, 4, ['max_rows' => 6], 1],
                ],
            ],

            // ── Fashion Left-Handed (3) ──────────────────────
            [
                'bt'      => 'fashion',
                'key'     => 'fashion_lefty_boutique',
                'name'    => 'Left-Hand Boutique',
                'name_ar' => 'البوتيك لليد اليسرى',
                'desc'    => 'Fashion boutique checkout with left-side cart and large product imagery for left-handed staff',
                'config'  => ['layout_type' => 'grid', 'cart_position' => 'left', 'cart_width' => 30, 'show_categories' => true, 'category_style' => 'icons', 'product_display' => 'grid', 'product_columns' => 4, 'show_images' => true, 'quick_actions' => ['discount', 'hold', 'gift_wrap', 'exchange'], 'payment_buttons' => ['cash', 'card', 'wallet']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['cart_panel',       0, 0, 7, 10, [], 2],
                    ['loyalty_points',   0, 10, 7, 2, [], 2],
                    ['payment_buttons',  0, 12, 7, 2, [], 2],
                    ['quick_actions',    0, 14, 7, 2, [], 2],
                    ['store_branding',   7, 0, 5, 2, [], 1],
                    ['search_bar',       12, 0, 12, 2, [], 1],
                    ['category_bar',     7, 2, 17, 2, ['style' => 'icons'], 1],
                    ['product_grid',     7, 4, 17, 12, ['columns' => 4, 'show_images' => true], 1],
                ],
            ],
            [
                'bt'      => 'fashion',
                'key'     => 'fashion_lefty_fitting',
                'name'    => 'Left-Hand Fitting Room',
                'name_ar' => 'غرفة القياس لليد اليسرى',
                'desc'    => 'Fitting room management with held items tracking and left-side cart for left-handed assistants',
                'config'  => ['layout_type' => 'fitting_room', 'cart_position' => 'left', 'cart_width' => 35, 'show_categories' => true, 'category_style' => 'tabs', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['hold', 'exchange', 'gift_wrap', 'discount']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['cart_panel',       0, 0, 8, 7, [], 2],
                    ['held_orders',      0, 7, 8, 5, ['max_display' => 8], 2],
                    ['payment_buttons',  0, 12, 8, 2, [], 2],
                    ['quick_actions',    0, 14, 8, 2, [], 2],
                    ['search_bar',       8, 0, 16, 1, [], 1],
                    ['category_bar',     8, 1, 16, 2, [], 1],
                    ['product_grid',     8, 3, 16, 9, ['columns' => 3], 1],
                    ['customer_info',    8, 12, 8, 4, [], 1],
                    ['order_summary',    16, 12, 8, 4, [], 1],
                ],
            ],
            [
                'bt'      => 'fashion',
                'key'     => 'fashion_lefty_returns',
                'name'    => 'Left-Hand Returns Desk',
                'name_ar' => 'مكتب المرتجعات لليد اليسرى',
                'desc'    => 'Fashion return/exchange counter with left-side cart and recent transaction lookup',
                'config'  => ['layout_type' => 'returns_desk', 'cart_position' => 'left', 'cart_width' => 40, 'show_categories' => false, 'product_display' => 'list', 'product_columns' => 1, 'show_images' => true, 'quick_actions' => ['refund', 'exchange', 'hold', 'gift_card'], 'payment_buttons' => ['cash', 'card']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['cart_panel',       0, 0, 10, 7, [], 2],
                    ['customer_info',    0, 7, 10, 3, ['show_purchase_history' => true], 2],
                    ['order_summary',    0, 10, 10, 2, [], 2],
                    ['payment_buttons',  0, 12, 10, 2, [], 2],
                    ['quick_actions',    0, 14, 10, 2, [], 2],
                    ['search_bar',       10, 0, 14, 2, ['placeholder' => 'Scan receipt or search transaction...', 'auto_focus' => true], 1],
                    ['recent_transactions', 10, 2, 14, 8, ['max_rows' => 12], 1],
                    ['product_grid',     10, 10, 14, 6, ['columns' => 1], 1],
                ],
            ],

            // ================================================================
            // RIGHT-HANDED & CREATIVE LAYOUTS (36 total)
            // ================================================================

            // ── Grocery Creative (5) ─────────────────────────
            [
                'bt'      => 'grocery',
                'key'     => 'grocery_self_checkout',
                'name'    => 'Self-Checkout Kiosk',
                'name_ar' => 'كشك الدفع الذاتي',
                'desc'    => 'Customer-facing self-checkout kiosk with large product tiles, numpad, and minimal UI',
                'config'  => ['layout_type' => 'self_checkout', 'cart_position' => 'right', 'cart_width' => 40, 'show_categories' => true, 'category_style' => 'icons', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['void'], 'payment_buttons' => ['card', 'wallet']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['store_branding',   0, 0, 14, 2, [], 1],
                    ['category_bar',     0, 2, 14, 2, ['style' => 'icons'], 1],
                    ['product_grid',     0, 4, 14, 12, ['columns' => 3, 'show_images' => true], 1],
                    ['cart_panel',       14, 0, 10, 8, ['display_mode' => 'kiosk'], 2],
                    ['numpad',           14, 8, 5, 4, [], 2],
                    ['order_summary',    19, 8, 5, 4, [], 2],
                    ['payment_buttons',  14, 12, 10, 4, [], 2],
                ],
            ],
            [
                'bt'      => 'grocery',
                'key'     => 'grocery_bottom_cart',
                'name'    => 'Bottom Cart Panoramic',
                'name_ar' => 'سلة سفلية بانورامية',
                'desc'    => 'Full-width product grid with cart at the bottom — ideal for wide touchscreens and tablets',
                'config'  => ['layout_type' => 'panoramic', 'cart_position' => 'bottom', 'cart_width' => 30, 'show_categories' => true, 'category_style' => 'tabs', 'product_display' => 'grid', 'product_columns' => 6, 'show_images' => true, 'quick_actions' => ['discount', 'hold', 'void'], 'payment_buttons' => ['cash', 'card', 'wallet']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['search_bar',       0, 0, 18, 1, ['show_barcode_button' => true], 1],
                    ['clock_widget',     18, 0, 6, 1, [], 1],
                    ['category_bar',     0, 1, 24, 2, [], 1],
                    ['product_grid',     0, 3, 24, 8, ['columns' => 6], 1],
                    ['cart_panel',       0, 11, 12, 5, [], 2],
                    ['order_summary',    12, 11, 4, 3, [], 2],
                    ['payment_buttons',  16, 11, 8, 3, [], 2],
                    ['quick_actions',    12, 14, 12, 2, [], 2],
                ],
            ],
            [
                'bt'      => 'grocery',
                'key'     => 'grocery_dual_screen',
                'name'    => 'Dual-Screen Express',
                'name_ar' => 'شاشة مزدوجة سريعة',
                'desc'    => 'Optimized for dual-monitor setup: cashier sees compact list, customer sees grid',
                'config'  => ['layout_type' => 'dual_screen', 'cart_position' => 'right', 'cart_width' => 35, 'show_categories' => false, 'product_display' => 'list', 'product_columns' => 1, 'show_images' => false, 'quick_actions' => ['discount', 'hold', 'void', 'refund'], 'payment_buttons' => ['cash', 'card', 'wallet', 'loyalty_redeem'], 'barcode_auto_submit' => true],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['search_bar',       0, 0, 16, 2, ['auto_focus' => true, 'show_barcode_button' => true], 1],
                    ['product_grid',     0, 2, 16, 6, ['columns' => 1, 'show_images' => false], 1],
                    ['numpad',           0, 8, 8, 4, [], 1],
                    ['recent_transactions', 8, 8, 8, 4, ['max_rows' => 5], 1],
                    ['quick_actions',    0, 12, 16, 2, [], 1],
                    ['promotional_banner', 0, 14, 16, 2, [], 1],
                    ['cart_panel',       16, 0, 8, 10, ['display_mode' => 'compact'], 2],
                    ['order_summary',    16, 10, 8, 2, [], 2],
                    ['payment_buttons',  16, 12, 8, 4, [], 2],
                ],
            ],
            [
                'bt'      => 'grocery',
                'key'     => 'grocery_senior_friendly',
                'name'    => 'Senior-Friendly Large Text',
                'name_ar' => 'نص كبير لكبار السن',
                'desc'    => 'Accessibility-focused layout with extra-large buttons, high contrast, and simplified navigation',
                'config'  => ['layout_type' => 'accessible', 'cart_position' => 'right', 'cart_width' => 40, 'show_categories' => true, 'category_style' => 'icons', 'product_display' => 'grid', 'product_columns' => 2, 'show_images' => true, 'quick_actions' => ['void', 'hold'], 'payment_buttons' => ['cash', 'card'], 'font_scale' => 1.5],
                'canvas'  => [24, 16, 4, 10],
                'widgets' => [
                    ['search_bar',       0, 0, 14, 2, ['auto_focus' => true], 1],
                    ['category_bar',     0, 2, 14, 3, ['style' => 'icons'], 1],
                    ['product_grid',     0, 5, 14, 11, ['columns' => 2, 'show_images' => true], 1],
                    ['cart_panel',       14, 0, 10, 10, ['display_mode' => 'large_text'], 2],
                    ['order_summary',    14, 10, 10, 2, [], 2],
                    ['payment_buttons',  14, 12, 10, 4, [], 2],
                ],
            ],
            [
                'bt'      => 'grocery',
                'key'     => 'grocery_night_shift',
                'name'    => 'Night Shift Dark Mode',
                'name_ar' => 'الوضع الليلي',
                'desc'    => 'Dark UI grocery layout for night-shift cashiers — reduced eye strain with high-contrast buttons',
                'config'  => ['layout_type' => 'grid', 'cart_position' => 'right', 'cart_width' => 35, 'show_categories' => true, 'category_style' => 'tabs', 'product_display' => 'grid', 'product_columns' => 4, 'show_images' => true, 'quick_actions' => ['discount', 'hold', 'void'], 'payment_buttons' => ['cash', 'card'], 'theme_override' => 'dark', 'special_features' => ['dark_mode' => true, 'high_contrast_buttons' => true]],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['search_bar',       0, 0, 16, 1, ['show_barcode_button' => true], 1],
                    ['category_bar',     0, 1, 16, 2, [], 1],
                    ['product_grid',     0, 3, 16, 13, ['columns' => 4], 1],
                    ['cart_panel',       16, 0, 8, 10, [], 2],
                    ['order_summary',    16, 10, 8, 2, [], 2],
                    ['payment_buttons',  16, 12, 8, 2, [], 2],
                    ['quick_actions',    16, 14, 8, 2, [], 2],
                ],
            ],

            // ── Restaurant Creative (5) ──────────────────────
            [
                'bt'      => 'restaurant',
                'key'     => 'restaurant_drive_through',
                'name'    => 'Drive-Through Lane',
                'name_ar' => 'مسار الطلب من السيارة',
                'desc'    => 'Drive-through lane layout with order timer, large item buttons, and quick combo selection',
                'config'  => ['layout_type' => 'drive_through', 'cart_position' => 'right', 'cart_width' => 35, 'show_categories' => true, 'category_style' => 'icons', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['void', 'hold', 'combo', 'upsell'], 'payment_buttons' => ['cash', 'card']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['clock_widget',     0, 0, 4, 2, ['show_timer' => true], 1],
                    ['search_bar',       4, 0, 12, 2, [], 1],
                    ['category_bar',     0, 2, 16, 3, ['style' => 'icons'], 1],
                    ['product_grid',     0, 5, 16, 11, ['columns' => 3, 'show_images' => true], 1],
                    ['cart_panel',       16, 0, 8, 10, [], 2],
                    ['order_summary',    16, 10, 8, 2, [], 2],
                    ['payment_buttons',  16, 12, 8, 4, [], 2],
                ],
            ],
            [
                'bt'      => 'restaurant',
                'key'     => 'restaurant_buffet_counter',
                'name'    => 'Buffet / Weight-Based',
                'name_ar' => 'بوفيه / حسب الوزن',
                'desc'    => 'Buffet-style restaurant where pricing is by weight or per-item with numpad for manual entry',
                'config'  => ['layout_type' => 'buffet', 'cart_position' => 'right', 'cart_width' => 40, 'show_categories' => false, 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['void', 'discount'], 'payment_buttons' => ['cash', 'card', 'wallet']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['search_bar',       0, 0, 14, 1, [], 1],
                    ['product_grid',     0, 1, 14, 9, ['columns' => 3, 'show_images' => true], 1],
                    ['numpad',           0, 10, 7, 6, [], 1],
                    ['custom_html',      7, 10, 7, 3, ['html_content' => '<div class="text-center"><strong>Weight</strong><br><span class="text-3xl">0.000</span> kg</div>'], 1],
                    ['quick_actions',    7, 13, 7, 3, [], 1],
                    ['cart_panel',       14, 0, 10, 10, [], 2],
                    ['order_summary',    14, 10, 10, 2, [], 2],
                    ['payment_buttons',  14, 12, 10, 4, [], 2],
                ],
            ],
            [
                'bt'      => 'restaurant',
                'key'     => 'restaurant_bar_tabs',
                'name'    => 'Bar Tabs Manager',
                'name_ar' => 'مدير حسابات البار',
                'desc'    => 'Bar and lounge layout with multiple open tabs, drink categories, and age verification prompt',
                'config'  => ['layout_type' => 'bar_tabs', 'cart_position' => 'right', 'cart_width' => 30, 'show_categories' => true, 'category_style' => 'tabs', 'product_display' => 'grid', 'product_columns' => 4, 'show_images' => true, 'quick_actions' => ['hold', 'split_bill', 'void', 'transfer_tab'], 'payment_buttons' => ['cash', 'card']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['search_bar',       0, 0, 16, 1, [], 1],
                    ['category_bar',     0, 1, 16, 2, [], 1],
                    ['product_grid',     0, 3, 16, 7, ['columns' => 4], 1],
                    ['held_orders',      0, 10, 16, 6, ['max_display' => 12, 'label' => 'Open Tabs'], 1],
                    ['cart_panel',       16, 0, 8, 10, [], 2],
                    ['order_summary',    16, 10, 8, 2, [], 2],
                    ['payment_buttons',  16, 12, 8, 2, [], 2],
                    ['quick_actions',    16, 14, 8, 2, [], 2],
                ],
            ],
            [
                'bt'      => 'restaurant',
                'key'     => 'restaurant_catering',
                'name'    => 'Catering & Bulk Orders',
                'name_ar' => 'التموين والطلبات الكبيرة',
                'desc'    => 'Large-quantity catering order layout with customer info, delivery scheduling, and staff notes',
                'config'  => ['layout_type' => 'catering', 'cart_position' => 'right', 'cart_width' => 40, 'show_categories' => true, 'category_style' => 'sidebar', 'product_display' => 'list', 'product_columns' => 1, 'show_images' => true, 'quick_actions' => ['hold', 'discount', 'delivery', 'print_invoice']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['search_bar',       0, 0, 14, 1, [], 1],
                    ['category_bar',     0, 1, 4, 15, ['style' => 'sidebar'], 1],
                    ['product_grid',     4, 1, 10, 9, ['columns' => 1], 1],
                    ['customer_info',    4, 10, 5, 3, ['show_purchase_history' => true], 1],
                    ['staff_notes',      9, 10, 5, 3, [], 1],
                    ['clock_widget',     4, 13, 5, 3, ['show_hijri' => true], 1],
                    ['numpad',           9, 13, 5, 3, [], 1],
                    ['cart_panel',       14, 0, 10, 10, [], 2],
                    ['order_summary',    14, 10, 10, 2, [], 2],
                    ['payment_buttons',  14, 12, 10, 2, [], 2],
                    ['quick_actions',    14, 14, 10, 2, [], 2],
                ],
            ],
            [
                'bt'      => 'restaurant',
                'key'     => 'restaurant_food_truck',
                'name'    => 'Food Truck Compact',
                'name_ar' => 'عربة الطعام المدمجة',
                'desc'    => 'Ultra-compact layout for small food truck tablets — minimal widgets, big buttons',
                'config'  => ['layout_type' => 'compact', 'cart_position' => 'bottom', 'cart_width' => 35, 'show_categories' => true, 'category_style' => 'tabs', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['void'], 'payment_buttons' => ['cash', 'card']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['store_branding',   0, 0, 6, 2, [], 1],
                    ['search_bar',       6, 0, 18, 2, [], 1],
                    ['category_bar',     0, 2, 24, 2, [], 1],
                    ['product_grid',     0, 4, 24, 6, ['columns' => 4, 'show_images' => true], 1],
                    ['cart_panel',       0, 10, 14, 6, [], 2],
                    ['order_summary',    14, 10, 5, 3, [], 2],
                    ['payment_buttons',  14, 13, 10, 3, [], 2],
                    ['quick_actions',    19, 10, 5, 3, [], 2],
                ],
            ],

            // ── Pharmacy Creative (4) ────────────────────────
            [
                'bt'      => 'pharmacy',
                'key'     => 'pharmacy_clinical_consultation',
                'name'    => 'Clinical Consultation',
                'name_ar' => 'الاستشارة السريرية',
                'desc'    => 'Consultation room layout with patient info, prescription history, and drug interaction notes',
                'config'  => ['layout_type' => 'consultation', 'cart_position' => 'right', 'cart_width' => 30, 'show_categories' => true, 'category_style' => 'sidebar', 'product_display' => 'list', 'product_columns' => 1, 'show_images' => false, 'quick_actions' => ['hold', 'refund', 'print_label'], 'show_drug_schedule' => true, 'show_interaction_warnings' => true],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['customer_info',    0, 0, 10, 5, ['show_purchase_history' => true, 'show_insurance' => true], 1],
                    ['staff_notes',      0, 5, 10, 5, [], 1],
                    ['recent_transactions', 0, 10, 10, 6, ['max_rows' => 8], 1],
                    ['search_bar',       10, 0, 7, 2, ['auto_focus' => true], 1],
                    ['category_bar',     10, 2, 3, 14, ['style' => 'sidebar'], 1],
                    ['product_grid',     13, 2, 4, 14, ['columns' => 1, 'show_stock' => true], 1],
                    ['cart_panel',       17, 0, 7, 10, [], 2],
                    ['order_summary',    17, 10, 7, 2, [], 2],
                    ['payment_buttons',  17, 12, 7, 2, [], 2],
                    ['quick_actions',    17, 14, 7, 2, [], 2],
                ],
            ],
            [
                'bt'      => 'pharmacy',
                'key'     => 'pharmacy_drive_through',
                'name'    => 'Pharmacy Drive-Through',
                'name_ar' => 'صيدلية من السيارة',
                'desc'    => 'Drive-through pharmacy window with quick prescription lookup and fast payment',
                'config'  => ['layout_type' => 'drive_through', 'cart_position' => 'right', 'cart_width' => 40, 'show_categories' => false, 'product_display' => 'list', 'product_columns' => 1, 'show_images' => false, 'quick_actions' => ['hold', 'print_label'], 'payment_buttons' => ['cash', 'card', 'insurance']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['search_bar',       0, 0, 14, 3, ['auto_focus' => true, 'placeholder' => 'Scan prescription barcode...'], 1],
                    ['product_grid',     0, 3, 14, 7, ['columns' => 1, 'show_stock' => true], 1],
                    ['customer_info',    0, 10, 7, 3, [], 1],
                    ['clock_widget',     7, 10, 7, 3, [], 1],
                    ['quick_actions',    0, 13, 14, 3, [], 1],
                    ['cart_panel',       14, 0, 10, 10, ['display_mode' => 'compact'], 2],
                    ['order_summary',    14, 10, 10, 2, [], 2],
                    ['payment_buttons',  14, 12, 10, 4, [], 2],
                ],
            ],
            [
                'bt'      => 'pharmacy',
                'key'     => 'pharmacy_cosmetics_aisle',
                'name'    => 'Cosmetics & Beauty',
                'name_ar' => 'مستحضرات التجميل',
                'desc'    => 'Pharmacy beauty counter layout with large product images, loyalty points, and promotions',
                'config'  => ['layout_type' => 'grid', 'cart_position' => 'right', 'cart_width' => 30, 'show_categories' => true, 'category_style' => 'icons', 'product_display' => 'grid', 'product_columns' => 4, 'show_images' => true, 'quick_actions' => ['discount', 'hold', 'gift_wrap'], 'payment_buttons' => ['cash', 'card', 'wallet']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['store_branding',   0, 0, 6, 2, [], 1],
                    ['search_bar',       6, 0, 11, 2, [], 1],
                    ['category_bar',     0, 2, 17, 2, ['style' => 'icons'], 1],
                    ['product_grid',     0, 4, 17, 10, ['columns' => 4, 'show_images' => true], 1],
                    ['promotional_banner', 0, 14, 17, 2, [], 1],
                    ['cart_panel',       17, 0, 7, 8, [], 2],
                    ['loyalty_points',   17, 8, 7, 2, [], 2],
                    ['order_summary',    17, 10, 7, 2, [], 2],
                    ['payment_buttons',  17, 12, 7, 2, [], 2],
                    ['quick_actions',    17, 14, 7, 2, [], 2],
                ],
            ],
            [
                'bt'      => 'pharmacy',
                'key'     => 'pharmacy_veterinary',
                'name'    => 'Veterinary Pharmacy',
                'name_ar' => 'صيدلية بيطرية',
                'desc'    => 'Vet pharmacy layout with animal type categories, weight-based dosing, and prescription fields',
                'config'  => ['layout_type' => 'veterinary', 'cart_position' => 'right', 'cart_width' => 35, 'show_categories' => true, 'category_style' => 'icons', 'product_display' => 'list', 'product_columns' => 1, 'show_images' => true, 'quick_actions' => ['discount', 'hold', 'print_label'], 'show_dosage_calculator' => true],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['search_bar',       0, 0, 16, 1, ['auto_focus' => true], 1],
                    ['category_bar',     0, 1, 16, 3, ['style' => 'icons'], 1],
                    ['product_grid',     0, 4, 16, 8, ['columns' => 1], 1],
                    ['customer_info',    0, 12, 8, 4, [], 1],
                    ['staff_notes',      8, 12, 8, 4, [], 1],
                    ['cart_panel',       16, 0, 8, 10, [], 2],
                    ['order_summary',    16, 10, 8, 2, [], 2],
                    ['payment_buttons',  16, 12, 8, 2, [], 2],
                    ['quick_actions',    16, 14, 8, 2, [], 2],
                ],
            ],

            // ── Bakery Creative (4) ──────────────────────────
            [
                'bt'      => 'bakery',
                'key'     => 'bakery_morning_rush',
                'name'    => 'Morning Rush Express',
                'name_ar' => 'الذروة الصباحية السريعة',
                'desc'    => 'Speed-optimized bakery layout for morning rush with favorites grid and one-tap combos',
                'config'  => ['layout_type' => 'express', 'cart_position' => 'right', 'cart_width' => 30, 'show_categories' => false, 'product_display' => 'grid', 'product_columns' => 4, 'show_images' => true, 'quick_actions' => ['void'], 'payment_buttons' => ['cash', 'card'], 'show_favorites' => true],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['search_bar',       0, 0, 17, 2, ['show_barcode_button' => true], 1],
                    ['product_grid',     0, 2, 17, 14, ['columns' => 4, 'show_images' => true, 'show_favorites_first' => true], 1],
                    ['cart_panel',       17, 0, 7, 10, ['display_mode' => 'compact'], 2],
                    ['order_summary',    17, 10, 7, 2, [], 2],
                    ['payment_buttons',  17, 12, 7, 4, [], 2],
                ],
            ],
            [
                'bt'      => 'bakery',
                'key'     => 'bakery_wholesale',
                'name'    => 'Wholesale / Bulk Orders',
                'name_ar' => 'طلبات الجملة',
                'desc'    => 'Wholesale bakery orders with quantity multiplier, numpad, and customer account management',
                'config'  => ['layout_type' => 'wholesale', 'cart_position' => 'right', 'cart_width' => 40, 'show_categories' => true, 'category_style' => 'sidebar', 'product_display' => 'list', 'product_columns' => 1, 'show_images' => false, 'quick_actions' => ['discount', 'hold', 'print_invoice'], 'payment_buttons' => ['cash', 'card', 'bank_transfer', 'credit_account']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['search_bar',       0, 0, 14, 1, ['auto_focus' => true], 1],
                    ['category_bar',     0, 1, 4, 11, ['style' => 'sidebar'], 1],
                    ['product_grid',     4, 1, 10, 7, ['columns' => 1, 'show_stock' => true], 1],
                    ['numpad',           4, 8, 5, 4, [], 1],
                    ['customer_info',    9, 8, 5, 4, ['show_credit_balance' => true], 1],
                    ['quick_actions',    0, 12, 14, 2, [], 1],
                    ['recent_transactions', 0, 14, 14, 2, ['max_rows' => 3], 1],
                    ['cart_panel',       14, 0, 10, 10, [], 2],
                    ['order_summary',    14, 10, 10, 2, [], 2],
                    ['payment_buttons',  14, 12, 10, 4, [], 2],
                ],
            ],
            [
                'bt'      => 'bakery',
                'key'     => 'bakery_display_case',
                'name'    => 'Display Case Visual',
                'name_ar' => 'علبة العرض المرئية',
                'desc'    => 'Visually rich layout mimicking a display case with large zoomable product photos',
                'config'  => ['layout_type' => 'visual', 'cart_position' => 'right', 'cart_width' => 25, 'show_categories' => true, 'category_style' => 'icons', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['discount', 'hold', 'gift_box'], 'payment_buttons' => ['cash', 'card']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['store_branding',   0, 0, 6, 2, [], 1],
                    ['search_bar',       6, 0, 12, 2, [], 1],
                    ['category_bar',     0, 2, 18, 2, ['style' => 'icons'], 1],
                    ['product_grid',     0, 4, 18, 12, ['columns' => 3, 'show_images' => true], 1],
                    ['cart_panel',       18, 0, 6, 10, ['display_mode' => 'compact'], 2],
                    ['order_summary',    18, 10, 6, 2, [], 2],
                    ['payment_buttons',  18, 12, 6, 2, [], 2],
                    ['quick_actions',    18, 14, 6, 2, [], 2],
                ],
            ],
            [
                'bt'      => 'bakery',
                'key'     => 'bakery_cafe_combo',
                'name'    => 'Bakery + Café Combo',
                'name_ar' => 'مخبز + مقهى مدمج',
                'desc'    => 'Combined bakery and café layout with separate food/drink category columns and held orders for dine-in',
                'config'  => ['layout_type' => 'split', 'cart_position' => 'right', 'cart_width' => 35, 'show_categories' => true, 'category_style' => 'tabs', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['discount', 'hold', 'dine_in', 'takeaway']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['search_bar',       0, 0, 16, 1, [], 1],
                    ['category_bar',     0, 1, 16, 2, [], 1],
                    ['product_grid',     0, 3, 16, 9, ['columns' => 3], 1],
                    ['held_orders',      0, 12, 8, 4, ['max_display' => 6, 'label' => 'Dine-In Orders'], 1],
                    ['staff_notes',      8, 12, 8, 4, [], 1],
                    ['cart_panel',       16, 0, 8, 10, [], 2],
                    ['order_summary',    16, 10, 8, 2, [], 2],
                    ['payment_buttons',  16, 12, 8, 2, [], 2],
                    ['quick_actions',    16, 14, 8, 2, [], 2],
                ],
            ],

            // ── Electronics Creative (4) ─────────────────────
            [
                'bt'      => 'electronics',
                'key'     => 'electronics_comparison_grid',
                'name'    => 'Product Comparison Grid',
                'name_ar' => 'شبكة مقارنة المنتجات',
                'desc'    => 'Side-by-side product comparison layout for smartphones, laptops, and accessories',
                'config'  => ['layout_type' => 'comparison', 'cart_position' => 'right', 'cart_width' => 30, 'show_categories' => true, 'category_style' => 'tabs', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['discount', 'hold', 'warranty_check', 'compare'], 'payment_buttons' => ['cash', 'card', 'installment']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['search_bar',       0, 0, 17, 1, [], 1],
                    ['category_bar',     0, 1, 17, 2, [], 1],
                    ['product_grid',     0, 3, 17, 13, ['columns' => 3, 'show_images' => true, 'show_specs' => true], 1],
                    ['cart_panel',       17, 0, 7, 10, [], 2],
                    ['order_summary',    17, 10, 7, 2, [], 2],
                    ['payment_buttons',  17, 12, 7, 2, [], 2],
                    ['quick_actions',    17, 14, 7, 2, [], 2],
                ],
            ],
            [
                'bt'      => 'electronics',
                'key'     => 'electronics_trade_in',
                'name'    => 'Trade-In & Buyback',
                'name_ar' => 'استبدال وإعادة شراء',
                'desc'    => 'Device buyback and trade-in layout with condition grading, IMEI check, and buyback pricing',
                'config'  => ['layout_type' => 'trade_in', 'cart_position' => 'right', 'cart_width' => 40, 'show_categories' => false, 'product_display' => 'list', 'product_columns' => 1, 'show_images' => true, 'quick_actions' => ['hold', 'buyback', 'warranty_check', 'print_label'], 'payment_buttons' => ['cash', 'bank_transfer']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['search_bar',       0, 0, 14, 2, ['placeholder' => 'Scan IMEI or search device...', 'auto_focus' => true], 1],
                    ['product_grid',     0, 2, 14, 6, ['columns' => 1, 'show_images' => true], 1],
                    ['customer_info',    0, 8, 7, 4, ['show_purchase_history' => true], 1],
                    ['staff_notes',      7, 8, 7, 4, [], 1],
                    ['recent_transactions', 0, 12, 14, 4, ['max_rows' => 6], 1],
                    ['cart_panel',       14, 0, 10, 10, [], 2],
                    ['order_summary',    14, 10, 10, 2, [], 2],
                    ['payment_buttons',  14, 12, 10, 4, [], 2],
                ],
            ],
            [
                'bt'      => 'electronics',
                'key'     => 'electronics_gaming_corner',
                'name'    => 'Gaming Corner',
                'name_ar' => 'ركن الألعاب',
                'desc'    => 'Gaming accessories and console sales layout with large visual tiles and promo banners',
                'config'  => ['layout_type' => 'visual', 'cart_position' => 'right', 'cart_width' => 30, 'show_categories' => true, 'category_style' => 'icons', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['discount', 'hold', 'gift_card'], 'payment_buttons' => ['cash', 'card', 'wallet']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['promotional_banner', 0, 0, 17, 3, [], 1],
                    ['search_bar',       0, 3, 17, 1, [], 1],
                    ['category_bar',     0, 4, 17, 2, ['style' => 'icons'], 1],
                    ['product_grid',     0, 6, 17, 10, ['columns' => 3, 'show_images' => true], 1],
                    ['cart_panel',       17, 0, 7, 10, [], 2],
                    ['loyalty_points',   17, 10, 7, 2, [], 2],
                    ['payment_buttons',  17, 12, 7, 2, [], 2],
                    ['quick_actions',    17, 14, 7, 2, [], 2],
                ],
            ],
            [
                'bt'      => 'electronics',
                'key'     => 'electronics_accessory_wall',
                'name'    => 'Accessory Wall Express',
                'name_ar' => 'جدار الإكسسوارات السريع',
                'desc'    => 'Fast-checkout layout for phone cases, chargers, and accessories with wide product grid',
                'config'  => ['layout_type' => 'express', 'cart_position' => 'right', 'cart_width' => 25, 'show_categories' => true, 'category_style' => 'tabs', 'product_display' => 'grid', 'product_columns' => 5, 'show_images' => true, 'quick_actions' => ['discount', 'hold'], 'payment_buttons' => ['cash', 'card']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['search_bar',       0, 0, 18, 1, ['show_barcode_button' => true], 1],
                    ['category_bar',     0, 1, 18, 2, [], 1],
                    ['product_grid',     0, 3, 18, 13, ['columns' => 5, 'show_images' => true], 1],
                    ['cart_panel',       18, 0, 6, 10, ['display_mode' => 'compact'], 2],
                    ['order_summary',    18, 10, 6, 2, [], 2],
                    ['payment_buttons',  18, 12, 6, 2, [], 2],
                    ['quick_actions',    18, 14, 6, 2, [], 2],
                ],
            ],

            // ── Florist Creative (4) ─────────────────────────
            [
                'bt'      => 'florist',
                'key'     => 'florist_subscription_manager',
                'name'    => 'Subscription Manager',
                'name_ar' => 'مدير الاشتراكات',
                'desc'    => 'Weekly/monthly flower subscription management with recurring order tracking',
                'config'  => ['layout_type' => 'subscription', 'cart_position' => 'right', 'cart_width' => 35, 'show_categories' => true, 'category_style' => 'tabs', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['hold', 'delivery', 'custom_message', 'renew_subscription']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['search_bar',       0, 0, 16, 1, [], 1],
                    ['category_bar',     0, 1, 16, 2, [], 1],
                    ['product_grid',     0, 3, 16, 7, ['columns' => 3], 1],
                    ['customer_info',    0, 10, 8, 3, ['show_purchase_history' => true], 1],
                    ['held_orders',      8, 10, 8, 3, ['max_display' => 5, 'label' => 'Active Subscriptions'], 1],
                    ['clock_widget',     0, 13, 8, 3, [], 1],
                    ['staff_notes',      8, 13, 8, 3, [], 1],
                    ['cart_panel',       16, 0, 8, 10, [], 2],
                    ['order_summary',    16, 10, 8, 2, [], 2],
                    ['payment_buttons',  16, 12, 8, 2, [], 2],
                    ['quick_actions',    16, 14, 8, 2, [], 2],
                ],
            ],
            [
                'bt'      => 'florist',
                'key'     => 'florist_seasonal_showcase',
                'name'    => 'Seasonal Showcase',
                'name_ar' => 'عروض الموسم',
                'desc'    => 'Seasonal promotion layout with hero banner, weather-aware suggestions, and gift cards',
                'config'  => ['layout_type' => 'showcase', 'cart_position' => 'right', 'cart_width' => 30, 'show_categories' => true, 'category_style' => 'icons', 'product_display' => 'grid', 'product_columns' => 4, 'show_images' => true, 'quick_actions' => ['discount', 'gift_card', 'delivery', 'custom_message']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['promotional_banner', 0, 0, 17, 3, [], 1],
                    ['weather_widget',   0, 3, 5, 2, [], 1],
                    ['search_bar',       5, 3, 12, 2, [], 1],
                    ['category_bar',     0, 5, 17, 2, ['style' => 'icons'], 1],
                    ['product_grid',     0, 7, 17, 9, ['columns' => 4, 'show_images' => true], 1],
                    ['cart_panel',       17, 0, 7, 10, [], 2],
                    ['order_summary',    17, 10, 7, 2, [], 2],
                    ['payment_buttons',  17, 12, 7, 2, [], 2],
                    ['quick_actions',    17, 14, 7, 2, [], 2],
                ],
            ],
            [
                'bt'      => 'florist',
                'key'     => 'florist_garden_center',
                'name'    => 'Garden Center',
                'name_ar' => 'مركز الحدائق',
                'desc'    => 'Outdoor garden center layout with plant care tips, weather awareness, and seasonal stock',
                'config'  => ['layout_type' => 'garden', 'cart_position' => 'right', 'cart_width' => 35, 'show_categories' => true, 'category_style' => 'sidebar', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['discount', 'hold', 'delivery'], 'payment_buttons' => ['cash', 'card']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['search_bar',       0, 0, 16, 1, [], 1],
                    ['weather_widget',   0, 1, 4, 2, [], 1],
                    ['category_bar',     0, 3, 4, 13, ['style' => 'sidebar'], 1],
                    ['product_grid',     4, 1, 12, 15, ['columns' => 3, 'show_images' => true], 1],
                    ['cart_panel',       16, 0, 8, 10, [], 2],
                    ['order_summary',    16, 10, 8, 2, [], 2],
                    ['payment_buttons',  16, 12, 8, 2, [], 2],
                    ['quick_actions',    16, 14, 8, 2, [], 2],
                ],
            ],
            [
                'bt'      => 'florist',
                'key'     => 'florist_funeral_sympathy',
                'name'    => 'Funeral & Sympathy',
                'name_ar' => 'باقات التعزية',
                'desc'    => 'Subdued, respectful layout for funeral and sympathy arrangements with delivery scheduling',
                'config'  => ['layout_type' => 'grid', 'cart_position' => 'right', 'cart_width' => 35, 'show_categories' => true, 'category_style' => 'tabs', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['hold', 'delivery', 'custom_message'], 'payment_buttons' => ['cash', 'card']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['search_bar',       0, 0, 16, 1, [], 1],
                    ['category_bar',     0, 1, 16, 2, [], 1],
                    ['product_grid',     0, 3, 16, 9, ['columns' => 3, 'show_images' => true], 1],
                    ['customer_info',    0, 12, 8, 4, ['show_purchase_history' => true], 1],
                    ['staff_notes',      8, 12, 8, 4, [], 1],
                    ['cart_panel',       16, 0, 8, 10, [], 2],
                    ['order_summary',    16, 10, 8, 2, [], 2],
                    ['payment_buttons',  16, 12, 8, 2, [], 2],
                    ['quick_actions',    16, 14, 8, 2, [], 2],
                ],
            ],

            // ── Jewelry Creative (4) ─────────────────────────
            [
                'bt'      => 'jewelry',
                'key'     => 'jewelry_bridal_registry',
                'name'    => 'Bridal Registry',
                'name_ar' => 'سجل العرائس',
                'desc'    => 'Bridal and engagement ring selection with customer wishlist, sizing, and engraving notes',
                'config'  => ['layout_type' => 'registry', 'cart_position' => 'right', 'cart_width' => 35, 'show_categories' => true, 'category_style' => 'icons', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['hold', 'gift_wrap', 'certificate', 'engraving'], 'show_gold_rate' => true],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['search_bar',       0, 0, 16, 1, [], 1],
                    ['custom_html',      0, 1, 16, 1, ['html_content' => '<div class="gold-rate text-center">Gold 24K: --- SAR/g | 21K: --- SAR/g | 18K: --- SAR/g</div>'], 1],
                    ['category_bar',     0, 2, 16, 2, ['style' => 'icons'], 1],
                    ['product_grid',     0, 4, 16, 8, ['columns' => 3, 'show_images' => true], 1],
                    ['customer_info',    0, 12, 8, 4, ['show_purchase_history' => true, 'show_loyalty_points' => true], 1],
                    ['staff_notes',      8, 12, 8, 4, [], 1],
                    ['cart_panel',       16, 0, 8, 10, [], 2],
                    ['order_summary',    16, 10, 8, 2, [], 2],
                    ['payment_buttons',  16, 12, 8, 2, [], 2],
                    ['quick_actions',    16, 14, 8, 2, [], 2],
                ],
            ],
            [
                'bt'      => 'jewelry',
                'key'     => 'jewelry_watch_counter',
                'name'    => 'Luxury Watch Counter',
                'name_ar' => 'كاونتر الساعات الفاخرة',
                'desc'    => 'Luxury watch showroom counter with large detail views, brand filtering, and warranty registration',
                'config'  => ['layout_type' => 'luxury_grid', 'cart_position' => 'right', 'cart_width' => 30, 'show_categories' => true, 'category_style' => 'icons', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['hold', 'gift_wrap', 'certificate', 'warranty_register']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['store_branding',   0, 0, 6, 2, [], 1],
                    ['search_bar',       6, 0, 11, 2, [], 1],
                    ['category_bar',     0, 2, 17, 2, ['style' => 'icons'], 1],
                    ['product_grid',     0, 4, 17, 12, ['columns' => 3, 'show_images' => true], 1],
                    ['cart_panel',       17, 0, 7, 8, [], 2],
                    ['customer_info',    17, 8, 7, 4, ['show_loyalty_points' => true], 2],
                    ['payment_buttons',  17, 12, 7, 2, [], 2],
                    ['quick_actions',    17, 14, 7, 2, [], 2],
                ],
            ],
            [
                'bt'      => 'jewelry',
                'key'     => 'jewelry_gold_souk',
                'name'    => 'Gold Souk Traditional',
                'name_ar' => 'سوق الذهب التقليدي',
                'desc'    => 'Traditional gold souk layout with weight calculator, numpad, and live gold rate for souks',
                'config'  => ['layout_type' => 'souk', 'cart_position' => 'right', 'cart_width' => 35, 'show_categories' => false, 'product_display' => 'list', 'product_columns' => 1, 'show_images' => false, 'quick_actions' => ['discount', 'hold', 'certificate'], 'show_gold_rate' => true, 'show_weight' => true],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['custom_html',      0, 0, 16, 2, ['html_content' => '<div class="gold-rates grid grid-cols-4 text-center"><div>24K<br>--- SAR</div><div>22K<br>--- SAR</div><div>21K<br>--- SAR</div><div>18K<br>--- SAR</div></div>'], 1],
                    ['search_bar',       0, 2, 16, 1, [], 1],
                    ['product_grid',     0, 3, 16, 7, ['columns' => 1, 'show_images' => false], 1],
                    ['numpad',           0, 10, 8, 6, [], 1],
                    ['custom_html',      8, 10, 8, 3, ['html_content' => '<div class="weight-calc text-center"><strong>Weight Calculator</strong><br>0.000 g</div>'], 1],
                    ['quick_actions',    8, 13, 8, 3, [], 1],
                    ['cart_panel',       16, 0, 8, 10, [], 2],
                    ['order_summary',    16, 10, 8, 2, [], 2],
                    ['payment_buttons',  16, 12, 8, 4, [], 2],
                ],
            ],
            [
                'bt'      => 'jewelry',
                'key'     => 'jewelry_repair_workshop',
                'name'    => 'Repair Workshop',
                'name_ar' => 'ورشة الإصلاح',
                'desc'    => 'Jewelry repair intake and tracking with job cards, customer history, and parts inventory',
                'config'  => ['layout_type' => 'repair', 'cart_position' => 'right', 'cart_width' => 35, 'show_categories' => true, 'category_style' => 'sidebar', 'product_display' => 'list', 'product_columns' => 1, 'show_images' => false, 'quick_actions' => ['hold', 'print_label', 'certificate']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['search_bar',       0, 0, 16, 1, [], 1],
                    ['category_bar',     0, 1, 4, 15, ['style' => 'sidebar'], 1],
                    ['product_grid',     4, 1, 12, 7, ['columns' => 1, 'show_images' => false], 1],
                    ['customer_info',    4, 8, 6, 4, ['show_purchase_history' => true], 1],
                    ['staff_notes',      10, 8, 6, 4, [], 1],
                    ['held_orders',      4, 12, 12, 4, ['max_display' => 8, 'label' => 'Active Repairs'], 1],
                    ['cart_panel',       16, 0, 8, 10, [], 2],
                    ['order_summary',    16, 10, 8, 2, [], 2],
                    ['payment_buttons',  16, 12, 8, 2, [], 2],
                    ['quick_actions',    16, 14, 8, 2, [], 2],
                ],
            ],

            // ── Fashion Creative (5) ─────────────────────────
            [
                'bt'      => 'fashion',
                'key'     => 'fashion_personal_shopper',
                'name'    => 'Personal Shopper',
                'name_ar' => 'المتسوق الشخصي',
                'desc'    => 'Personal shopping assistant layout with customer preferences, outfit suggestions, and wish lists',
                'config'  => ['layout_type' => 'personal_shopper', 'cart_position' => 'right', 'cart_width' => 30, 'show_categories' => true, 'category_style' => 'icons', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['hold', 'gift_wrap', 'discount', 'exchange'], 'payment_buttons' => ['cash', 'card', 'wallet']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['customer_info',    0, 0, 8, 4, ['show_purchase_history' => true, 'show_loyalty_points' => true], 1],
                    ['search_bar',       8, 0, 9, 1, [], 1],
                    ['category_bar',     8, 1, 9, 2, ['style' => 'icons'], 1],
                    ['product_grid',     0, 4, 17, 12, ['columns' => 4, 'show_images' => true], 1],
                    ['staff_notes',      8, 3, 9, 1, [], 1],
                    ['cart_panel',       17, 0, 7, 10, [], 2],
                    ['loyalty_points',   17, 10, 7, 2, [], 2],
                    ['payment_buttons',  17, 12, 7, 2, [], 2],
                    ['quick_actions',    17, 14, 7, 2, [], 2],
                ],
            ],
            [
                'bt'      => 'fashion',
                'key'     => 'fashion_seasonal_sale',
                'name'    => 'Seasonal Sale Blitz',
                'name_ar' => 'عروض الموسم',
                'desc'    => 'High-volume seasonal sale layout with promo banners, fast scan, and discount quick actions',
                'config'  => ['layout_type' => 'sale', 'cart_position' => 'right', 'cart_width' => 30, 'show_categories' => true, 'category_style' => 'tabs', 'product_display' => 'grid', 'product_columns' => 4, 'show_images' => true, 'quick_actions' => ['discount', 'void', 'hold'], 'payment_buttons' => ['cash', 'card', 'wallet']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['promotional_banner', 0, 0, 17, 3, [], 1],
                    ['search_bar',       0, 3, 17, 1, ['show_barcode_button' => true], 1],
                    ['category_bar',     0, 4, 17, 2, [], 1],
                    ['product_grid',     0, 6, 17, 10, ['columns' => 4, 'show_images' => true], 1],
                    ['cart_panel',       17, 0, 7, 10, ['display_mode' => 'compact'], 2],
                    ['order_summary',    17, 10, 7, 2, [], 2],
                    ['payment_buttons',  17, 12, 7, 2, [], 2],
                    ['quick_actions',    17, 14, 7, 2, [], 2],
                ],
            ],
            [
                'bt'      => 'fashion',
                'key'     => 'fashion_pop_up_shop',
                'name'    => 'Pop-Up Shop Mobile',
                'name_ar' => 'المتجر المؤقت',
                'desc'    => 'Ultra-portable layout for pop-up shops and fashion markets — works great on tablets',
                'config'  => ['layout_type' => 'compact', 'cart_position' => 'bottom', 'cart_width' => 35, 'show_categories' => true, 'category_style' => 'tabs', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['discount', 'void'], 'payment_buttons' => ['cash', 'card']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['store_branding',   0, 0, 6, 2, [], 1],
                    ['search_bar',       6, 0, 18, 2, [], 1],
                    ['category_bar',     0, 2, 24, 2, [], 1],
                    ['product_grid',     0, 4, 24, 6, ['columns' => 4, 'show_images' => true], 1],
                    ['cart_panel',       0, 10, 14, 6, [], 2],
                    ['order_summary',    14, 10, 5, 3, [], 2],
                    ['payment_buttons',  14, 13, 10, 3, [], 2],
                    ['quick_actions',    19, 10, 5, 3, [], 2],
                ],
            ],
            [
                'bt'      => 'fashion',
                'key'     => 'fashion_vip_lounge',
                'name'    => 'VIP Lounge Experience',
                'name_ar' => 'تجربة صالة كبار الشخصيات',
                'desc'    => 'Premium VIP shopping experience with customer history, loyalty rewards, and dedicated branding',
                'config'  => ['layout_type' => 'vip', 'cart_position' => 'right', 'cart_width' => 35, 'show_categories' => true, 'category_style' => 'icons', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['discount', 'hold', 'gift_wrap', 'exchange'], 'payment_buttons' => ['cash', 'card', 'wallet', 'loyalty_redeem']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['store_branding',   0, 0, 7, 3, [], 1],
                    ['search_bar',       7, 0, 9, 1, [], 1],
                    ['customer_info',    7, 1, 9, 2, ['show_purchase_history' => true, 'show_loyalty_points' => true], 1],
                    ['category_bar',     0, 3, 16, 2, ['style' => 'icons'], 1],
                    ['product_grid',     0, 5, 16, 11, ['columns' => 3, 'show_images' => true], 1],
                    ['cart_panel',       16, 0, 8, 8, [], 2],
                    ['loyalty_points',   16, 8, 8, 2, [], 2],
                    ['order_summary',    16, 10, 8, 2, [], 2],
                    ['payment_buttons',  16, 12, 8, 2, [], 2],
                    ['quick_actions',    16, 14, 8, 2, [], 2],
                ],
            ],
            [
                'bt'      => 'fashion',
                'key'     => 'fashion_outlet_clearance',
                'name'    => 'Outlet Clearance',
                'name_ar' => 'تصفية المنفذ',
                'desc'    => 'High-speed outlet checkout with barcode scanning focus and minimal browsing — scan and go',
                'config'  => ['layout_type' => 'scan_focused', 'cart_position' => 'right', 'cart_width' => 40, 'show_categories' => false, 'product_display' => 'list', 'product_columns' => 1, 'show_images' => false, 'quick_actions' => ['discount', 'void', 'refund'], 'payment_buttons' => ['cash', 'card'], 'barcode_auto_submit' => true],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['search_bar',       0, 0, 14, 2, ['auto_focus' => true, 'show_barcode_button' => true], 1],
                    ['product_grid',     0, 2, 14, 8, ['columns' => 1, 'show_images' => false], 1],
                    ['numpad',           0, 10, 7, 6, [], 1],
                    ['quick_actions',    7, 10, 7, 3, [], 1],
                    ['recent_transactions', 7, 13, 7, 3, ['max_rows' => 4], 1],
                    ['cart_panel',       14, 0, 10, 10, ['display_mode' => 'compact'], 2],
                    ['order_summary',    14, 10, 10, 2, [], 2],
                    ['payment_buttons',  14, 12, 10, 4, [], 2],
                ],
            ],

            // ── Cross-Business Universal (5) ─────────────────
            [
                'bt'      => 'grocery',
                'key'     => 'universal_receipt_preview',
                'name'    => 'Receipt Preview Mode',
                'name_ar' => 'وضع معاينة الإيصال',
                'desc'    => 'Layout with live receipt preview alongside the cart — ideal for training and verification',
                'config'  => ['layout_type' => 'receipt_preview', 'cart_position' => 'right', 'cart_width' => 25, 'show_categories' => true, 'category_style' => 'tabs', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['discount', 'hold', 'void'], 'payment_buttons' => ['cash', 'card']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['search_bar',       0, 0, 12, 1, [], 1],
                    ['category_bar',     0, 1, 12, 2, [], 1],
                    ['product_grid',     0, 3, 12, 13, ['columns' => 3], 1],
                    ['receipt_preview',  12, 0, 6, 16, [], 1],
                    ['cart_panel',       18, 0, 6, 10, ['display_mode' => 'compact'], 2],
                    ['order_summary',    18, 10, 6, 2, [], 2],
                    ['payment_buttons',  18, 12, 6, 2, [], 2],
                    ['quick_actions',    18, 14, 6, 2, [], 2],
                ],
            ],
            [
                'bt'      => 'restaurant',
                'key'     => 'universal_training_mode',
                'name'    => 'Training Mode Layout',
                'name_ar' => 'وضع التدريب',
                'desc'    => 'Training layout with all widgets visible, labeled, and a staff notes area for supervisors',
                'config'  => ['layout_type' => 'training', 'cart_position' => 'right', 'cart_width' => 35, 'show_categories' => true, 'category_style' => 'tabs', 'product_display' => 'grid', 'product_columns' => 3, 'show_images' => true, 'quick_actions' => ['discount', 'hold', 'void', 'refund'], 'payment_buttons' => ['cash', 'card', 'wallet'], 'training_mode' => true],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['store_branding',   0, 0, 4, 2, [], 1],
                    ['search_bar',       4, 0, 12, 1, [], 1],
                    ['clock_widget',     4, 1, 4, 1, [], 1],
                    ['weather_widget',   8, 1, 4, 1, [], 1],
                    ['promotional_banner', 12, 1, 4, 1, [], 1],
                    ['category_bar',     0, 2, 16, 2, [], 1],
                    ['product_grid',     0, 4, 16, 6, ['columns' => 3], 1],
                    ['numpad',           0, 10, 4, 3, [], 1],
                    ['customer_info',    4, 10, 4, 3, [], 1],
                    ['loyalty_points',   8, 10, 4, 3, [], 1],
                    ['staff_notes',      12, 10, 4, 3, [], 1],
                    ['held_orders',      0, 13, 8, 3, ['max_display' => 4], 1],
                    ['recent_transactions', 8, 13, 8, 3, ['max_rows' => 4], 1],
                    ['cart_panel',       16, 0, 8, 10, [], 2],
                    ['order_summary',    16, 10, 8, 2, [], 2],
                    ['payment_buttons',  16, 12, 8, 2, [], 2],
                    ['quick_actions',    16, 14, 8, 2, [], 2],
                ],
            ],
            [
                'bt'      => 'electronics',
                'key'     => 'universal_numpad_heavy',
                'name'    => 'Numpad-Heavy Data Entry',
                'name_ar' => 'إدخال بيانات بلوحة الأرقام',
                'desc'    => 'Data-entry focused layout with prominent numpad for manual price/quantity entry',
                'config'  => ['layout_type' => 'data_entry', 'cart_position' => 'right', 'cart_width' => 35, 'show_categories' => false, 'product_display' => 'list', 'product_columns' => 1, 'show_images' => false, 'quick_actions' => ['discount', 'hold', 'void'], 'payment_buttons' => ['cash', 'card']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['search_bar',       0, 0, 16, 2, ['auto_focus' => true], 1],
                    ['product_grid',     0, 2, 8, 6, ['columns' => 1, 'show_images' => false], 1],
                    ['numpad',           8, 2, 8, 8, [], 1],
                    ['recent_transactions', 0, 8, 8, 4, ['max_rows' => 5], 1],
                    ['quick_actions',    0, 12, 16, 2, [], 1],
                    ['custom_html',      0, 14, 16, 2, ['html_content' => '<div class="text-center text-gray-400 text-sm">Quick Entry Mode — Type amount and press Enter</div>'], 1],
                    ['cart_panel',       16, 0, 8, 10, [], 2],
                    ['order_summary',    16, 10, 8, 2, [], 2],
                    ['payment_buttons',  16, 12, 8, 4, [], 2],
                ],
            ],
            [
                'bt'      => 'fashion',
                'key'     => 'universal_minimal_zen',
                'name'    => 'Minimal Zen',
                'name_ar' => 'الحد الأدنى زن',
                'desc'    => 'Ultra-clean minimal layout — only product search, cart, and payment. Zero distractions',
                'config'  => ['layout_type' => 'minimal', 'cart_position' => 'right', 'cart_width' => 40, 'show_categories' => false, 'product_display' => 'list', 'product_columns' => 1, 'show_images' => false, 'quick_actions' => ['void'], 'payment_buttons' => ['cash', 'card'], 'minimal_mode' => true],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['search_bar',       0, 0, 14, 2, ['auto_focus' => true, 'show_barcode_button' => true], 1],
                    ['product_grid',     0, 2, 14, 14, ['columns' => 1, 'show_images' => false], 1],
                    ['cart_panel',       14, 0, 10, 12, ['display_mode' => 'compact'], 2],
                    ['payment_buttons',  14, 12, 10, 4, [], 2],
                ],
            ],
            [
                'bt'      => 'bakery',
                'key'     => 'universal_split_screen',
                'name'    => 'Split-Screen Dual View',
                'name_ar' => 'عرض مزدوج مقسم',
                'desc'    => 'Split-screen layout with grid on top and list below — great for comparing products while building orders',
                'config'  => ['layout_type' => 'split_screen', 'cart_position' => 'right', 'cart_width' => 35, 'show_categories' => true, 'category_style' => 'tabs', 'product_display' => 'grid', 'product_columns' => 4, 'show_images' => true, 'quick_actions' => ['discount', 'hold', 'void'], 'payment_buttons' => ['cash', 'card']],
                'canvas'  => [24, 16, 4, 8],
                'widgets' => [
                    ['search_bar',       0, 0, 16, 1, ['show_barcode_button' => true], 1],
                    ['category_bar',     0, 1, 16, 2, [], 1],
                    ['product_grid',     0, 3, 16, 6, ['columns' => 4, 'show_images' => true], 1],
                    ['held_orders',      0, 9, 8, 4, ['max_display' => 6], 1],
                    ['recent_transactions', 8, 9, 8, 4, ['max_rows' => 5], 1],
                    ['quick_actions',    0, 13, 16, 3, [], 1],
                    ['cart_panel',       16, 0, 8, 10, [], 2],
                    ['order_summary',    16, 10, 8, 2, [], 2],
                    ['payment_buttons',  16, 12, 8, 4, [], 2],
                ],
            ],
        ];
    }
}
