<?php

namespace Database\Seeders;

use App\Domain\ContentOnboarding\Enums\MarketplaceListingStatus;
use App\Domain\ContentOnboarding\Enums\MarketplacePricingType;
use App\Domain\ContentOnboarding\Enums\SubscriptionInterval;
use App\Domain\ContentOnboarding\Models\MarketplaceCategory;
use App\Domain\ContentOnboarding\Models\PosLayoutTemplate;
use App\Domain\ContentOnboarding\Models\TemplateMarketplaceListing;
use App\Domain\ContentOnboarding\Models\Theme;
use Illuminate\Database\Seeder;

class CreativeMarketplaceListingSeeder extends Seeder
{
    /**
     * Marketplace listings for the 74 POS layouts that do not have one yet.
     * (84 total layouts − 10 already listed in ComprehensiveMarketplaceListingSeeder)
     */
    public function run(): void
    {
        $cat    = fn (string $slug) => MarketplaceCategory::where('slug', $slug)->first()?->id;
        $theme  = fn (string $slug) => Theme::where('slug', $slug)->first()?->id;
        $layout = fn (string $key)  => PosLayoutTemplate::where('layout_key', $key)->first()?->id;

        foreach ($this->listings() as $data) {
            $data['pos_layout_template_id'] = $layout($data['_layout_key']);
            $data['theme_id']               = $theme($data['_theme_slug']);
            $data['category_id']            = $cat($data['_category_slug']);

            unset($data['_layout_key'], $data['_theme_slug'], $data['_category_slug']);

            if (! $data['pos_layout_template_id']) {
                continue;
            }

            TemplateMarketplaceListing::updateOrCreate(
                [
                    'pos_layout_template_id' => $data['pos_layout_template_id'],
                    'title'                  => $data['title'],
                ],
                $data,
            );
        }
    }

    private function listings(): array
    {
        $F = MarketplacePricingType::Free;
        $O = MarketplacePricingType::OneTime;
        $S = MarketplacePricingType::Subscription;

        $A = MarketplaceListingStatus::Approved;
        $P = MarketplaceListingStatus::PendingReview;
        $D = MarketplaceListingStatus::Draft;

        $M = SubscriptionInterval::Monthly;

        return [
            // ══════════════════════════════════════════════════
            // ORIGINAL 21 – remaining 11 without a listing
            // ══════════════════════════════════════════════════

            // 1. grocery_compact_list
            $this->l('grocery_compact_list', 'forest_green', 'grocery',
                'Thawani Official', 'Grocery Compact List',
                'قائمة البقالة المدمجة',
                'Compact list layout for small grocery stores with barcode scanning and fast checkout flow.',
                'تخطيط قائمة مدمج لمتاجر البقالة الصغيرة مع مسح الباركود وتدفق دفع سريع.',
                'Compact grocery list with barcode support',
                'قائمة بقالة مدمجة مع دعم الباركود',
                $F, 0, null,
                ['grocery', 'compact', 'list', 'free', 'barcode'],
                '1.0.0', 'Initial release',
                198, 4.2, 14, false, true, $A, 80),

            // 2. restaurant_standard_grid
            $this->l('restaurant_standard_grid', 'sunset_warmth', 'restaurant',
                'Thawani Official', 'Restaurant Standard Grid',
                'شبكة المطعم القياسية',
                'Standard restaurant grid with food categories, image-rich product tiles, and right-side cart panel.',
                'شبكة مطعم قياسية مع فئات الطعام وبلاطات المنتجات الغنية بالصور ولوحة السلة على الجانب الأيمن.',
                'Standard restaurant grid layout',
                'تخطيط شبكة المطعم القياسي',
                $F, 0, null,
                ['restaurant', 'grid', 'free', 'standard'],
                '1.0.0', 'Initial release',
                267, 4.4, 21, false, true, $A, 85),

            // 3. restaurant_compact_list
            $this->l('restaurant_compact_list', 'dark_mode', 'restaurant',
                'FoodTech Arabia', 'Restaurant Quick List',
                'قائمة المطعم السريعة',
                'Fast compact list layout for quick-service restaurants with minimal browsing and rapid order entry.',
                'تخطيط قائمة مدمج سريع لمطاعم الخدمة السريعة مع حد أدنى من التصفح وإدخال سريع للطلبات.',
                'Quick-service restaurant list layout',
                'تخطيط قائمة المطعم للخدمة السريعة',
                $F, 0, null,
                ['restaurant', 'compact', 'quick-service', 'free'],
                '1.0.0', 'Initial release',
                145, 4.1, 11, false, true, $A, 70),

            // 4. pharmacy_standard_grid
            $this->l('pharmacy_standard_grid', 'high_contrast', 'pharmacy',
                'Thawani Official', 'Pharmacy Standard Grid',
                'شبكة الصيدلية القياسية',
                'Standard pharmacy grid with product categories, stock indicators, and clear pricing display.',
                'شبكة صيدلية قياسية مع فئات المنتجات ومؤشرات المخزون وعرض واضح للأسعار.',
                'Standard pharmacy grid layout',
                'تخطيط شبكة الصيدلية القياسي',
                $F, 0, null,
                ['pharmacy', 'grid', 'free', 'standard'],
                '1.0.0', 'Initial release',
                178, 4.3, 16, false, true, $A, 75),

            // 5. pharmacy_compact_list
            $this->l('pharmacy_compact_list', 'thawani_brand', 'pharmacy',
                'HealthTech Solutions', 'Pharmacy Quick Lookup',
                'البحث السريع في الصيدلية',
                'Compact searchable list for fast medicine lookup with auto-complete and drug schedule indicators.',
                'قائمة بحث مدمجة للبحث السريع عن الأدوية مع الإكمال التلقائي ومؤشرات جدول الأدوية.',
                'Fast medicine lookup list',
                'قائمة بحث سريع عن الأدوية',
                $F, 0, null,
                ['pharmacy', 'compact', 'search', 'free'],
                '1.0.0', 'Initial release',
                112, 4.0, 8, false, true, $A, 65),

            // 6. bakery_standard_grid
            $this->l('bakery_standard_grid', 'sunset_warmth', 'restaurant',
                'Thawani Official', 'Bakery Standard Grid',
                'شبكة المخبز القياسية',
                'Standard bakery layout with product images, category navigation, and order management.',
                'تخطيط مخبز قياسي مع صور المنتجات والتنقل بين الفئات وإدارة الطلبات.',
                'Standard bakery grid layout',
                'تخطيط شبكة المخبز القياسي',
                $F, 0, null,
                ['bakery', 'grid', 'free', 'standard'],
                '1.0.0', 'Initial release',
                134, 4.2, 10, false, true, $A, 72),

            // 7. bakery_compact_list
            $this->l('bakery_compact_list', 'desert_sand', 'restaurant',
                'BakeSoft', 'Bakery Express List',
                'قائمة المخبز السريعة',
                'Fast compact bakery list for high-volume morning rush with quick-tap ordering.',
                'قائمة مخبز مدمجة سريعة لذروة الصباح مع طلب بلمسة واحدة.',
                'Fast bakery list for morning rush',
                'قائمة مخبز سريعة لذروة الصباح',
                $F, 0, null,
                ['bakery', 'compact', 'express', 'free'],
                '1.0.0', 'Initial release',
                98, 4.1, 7, false, true, $A, 60),

            // 8. electronics_compact_list
            $this->l('electronics_compact_list', 'midnight_blue', 'electronics',
                'TechRetail Pro', 'Electronics Compact List',
                'قائمة الإلكترونيات المدمجة',
                'Compact list view for electronics stores with SKU, serial tracking, and warranty indicators.',
                'عرض قائمة مدمج لمتاجر الإلكترونيات مع SKU وتتبع الرقم التسلسلي ومؤشرات الضمان.',
                'Compact electronics list with serial tracking',
                'قائمة إلكترونيات مدمجة مع تتبع المسلسل',
                $F, 0, null,
                ['electronics', 'compact', 'serial', 'free'],
                '1.0.0', 'Initial release',
                87, 4.0, 6, false, true, $A, 55),

            // 9. florist_compact_list
            $this->l('florist_compact_list', 'ocean_breeze', 'services',
                'FloralTech', 'Florist Quick List',
                'قائمة الزهور السريعة',
                'Compact flower shop list with freshness markers, seasonal filters, and delivery options.',
                'قائمة محل زهور مدمجة مع علامات النضارة والفلاتر الموسمية وخيارات التوصيل.',
                'Quick florist list with freshness tracking',
                'قائمة زهور سريعة مع تتبع النضارة',
                $F, 0, null,
                ['florist', 'compact', 'freshness', 'free'],
                '1.0.0', 'Initial release',
                56, 4.1, 4, false, true, $A, 50),

            // 10. jewelry_standard_grid
            $this->l('jewelry_standard_grid', 'royal_purple', 'premium',
                'LuxDesign Studio', 'Jewellery Standard Grid',
                'شبكة المجوهرات القياسية',
                'Standard jewellery grid with product images, karat indicators, and weight display.',
                'شبكة مجوهرات قياسية مع صور المنتجات ومؤشرات العيار وعرض الوزن.',
                'Standard jewellery grid layout',
                'تخطيط شبكة المجوهرات القياسي',
                $F, 0, null,
                ['jewelry', 'grid', 'free', 'standard'],
                '1.0.0', 'Initial release',
                92, 4.3, 8, false, true, $A, 68),

            // 11. jewelry_compact_list
            $this->l('jewelry_compact_list', 'royal_purple', 'premium',
                'LuxDesign Studio', 'Jewellery Quick Lookup',
                'البحث السريع في المجوهرات',
                'Compact jewellery list for fast item lookup by SKU, karat, or weight with gold rate display.',
                'قائمة مجوهرات مدمجة للبحث السريع عن القطع بالـ SKU أو العيار أو الوزن مع عرض سعر الذهب.',
                'Quick jewellery lookup with gold rates',
                'بحث سريع عن المجوهرات مع أسعار الذهب',
                $O, 19.99, null,
                ['jewelry', 'compact', 'gold', 'lookup'],
                '1.1.0', 'v1.1: Added gold rate ticker',
                45, 4.2, 5, false, true, $A, 55),

            // ══════════════════════════════════════════════════
            // LEFT-HANDED LAYOUTS (23 listings)
            // ══════════════════════════════════════════════════

            // ── Grocery Left-Handed ──
            $this->l('grocery_lefty_express', 'forest_green', 'grocery',
                'AccessPOS', 'Left-Hand Express Grocery',
                'بقالة سريعة لليد اليسرى',
                'Fast-scan grocery checkout designed for left-handed cashiers. Cart and payment panel on the left side, product grid on the right. Optimized for natural left-hand workflow.',
                'دفع بقالة سريع مصمم للكاشير الأعسر. لوحة السلة والدفع على الجانب الأيسر وشبكة المنتجات على الأيمن. محسّن لسير العمل الطبيعي لليد اليسرى.',
                'Left-handed express grocery checkout',
                'دفع بقالة سريع لليد اليسرى',
                $O, 24.99, null,
                ['grocery', 'left-handed', 'express', 'accessibility'],
                '1.0.0', 'Initial release',
                89, 4.6, 12, true, true, $A, 30),

            $this->l('grocery_lefty_scale', 'forest_green', 'grocery',
                'AccessPOS', 'Left-Hand Scale & Weigh',
                'ميزان لليد اليسرى',
                'Left-handed grocery layout with integrated scale display widget and numpad on the left side for natural weigh-and-price workflow.',
                'تخطيط بقالة لليد اليسرى مع عرض الميزان المدمج ولوحة الأرقام على الجانب الأيسر لسير العمل الطبيعي للوزن والسعر.',
                'Left-handed grocery with scale integration',
                'بقالة لليد اليسرى مع تكامل الميزان',
                $O, 29.99, null,
                ['grocery', 'left-handed', 'scale', 'weight'],
                '1.0.0', 'Initial release',
                52, 4.5, 7, false, true, $A, 25),

            $this->l('grocery_lefty_loyalty', 'light_classic', 'grocery',
                'AccessPOS', 'Left-Hand Loyalty Checkout',
                'دفع بالولاء لليد اليسرى',
                'Left-handed grocery layout with prominent loyalty points display, member pricing, and redemption options on the left-side panel.',
                'تخطيط بقالة لليد اليسرى مع عرض بارز لنقاط الولاء وتسعير الأعضاء وخيارات الاستبدال على لوحة الجانب الأيسر.',
                'Left-handed grocery with loyalty integration',
                'بقالة لليد اليسرى مع تكامل الولاء',
                $O, 29.99, null,
                ['grocery', 'left-handed', 'loyalty', 'rewards'],
                '1.0.0', 'Initial release',
                41, 4.4, 6, false, true, $A, 22),

            // ── Restaurant Left-Handed ──
            $this->l('restaurant_lefty_quick_service', 'dark_mode', 'restaurant',
                'FoodTech Arabia', 'Left-Hand Quick Service',
                'خدمة سريعة لليد اليسرى',
                'Fast food / QSR layout with left-side order panel for left-handed staff. Big menu icons, rapid add-to-order, and streamlined payment flow.',
                'تخطيط وجبات سريعة مع لوحة طلبات على الجانب الأيسر للموظفين العسر. أيقونات قائمة كبيرة وإضافة سريعة للطلب وتدفق دفع مبسط.',
                'Left-handed QSR layout',
                'تخطيط خدمة سريعة لليد اليسرى',
                $O, 24.99, null,
                ['restaurant', 'left-handed', 'quick-service', 'fast-food'],
                '1.0.0', 'Initial release',
                67, 4.5, 9, false, true, $A, 28),

            $this->l('restaurant_lefty_table_map', 'sunset_warmth', 'restaurant',
                'FoodTech Arabia', 'Left-Hand Table Service',
                'خدمة طاولات لليد اليسرى',
                'Dine-in table management with left-side cart for left-handed waiters on tablets. Includes table map, customer info panel, and split-bill support.',
                'إدارة طاولات مع سلة على الجانب الأيسر للنُدل العسر على الأجهزة اللوحية. يتضمن خريطة الطاولات ولوحة معلومات العميل ودعم تقسيم الفاتورة.',
                'Left-handed dine-in table management',
                'إدارة طاولات لليد اليسرى',
                $O, 39.99, null,
                ['restaurant', 'left-handed', 'table', 'dine-in'],
                '1.0.0', 'Initial release',
                38, 4.7, 8, true, true, $A, 20),

            $this->l('restaurant_lefty_kitchen_display', 'dark_mode', 'restaurant',
                'FoodTech Arabia', 'Left-Hand Kitchen Display',
                'شاشة مطبخ لليد اليسرى',
                'Kitchen-facing order display with left-side queue and held orders panel for left-handed chefs and expeditors.',
                'شاشة طلبات المطبخ مع قائمة انتظار على الجانب الأيسر ولوحة الطلبات المعلقة للطهاة والمراقبين العسر.',
                'Left-handed kitchen display system',
                'نظام شاشة المطبخ لليد اليسرى',
                $O, 34.99, null,
                ['restaurant', 'left-handed', 'kitchen', 'display'],
                '1.0.0', 'Initial release',
                29, 4.3, 5, false, true, $A, 18),

            // ── Pharmacy Left-Handed ──
            $this->l('pharmacy_lefty_prescription', 'high_contrast', 'pharmacy',
                'HealthTech Solutions', 'Left-Hand Prescription Counter',
                'كاونتر وصفات لليد اليسرى',
                'Pharmacy counter optimized for left-handed pharmacists with cart, patient info, and prescription lookup all on the left panel.',
                'كاونتر صيدلية محسّن للصيادلة العسر مع السلة ومعلومات المريض والبحث عن الوصفات كلها على اللوحة اليسرى.',
                'Left-handed pharmacy prescription counter',
                'كاونتر وصفات صيدلية لليد اليسرى',
                $S, 24.99, $M,
                ['pharmacy', 'left-handed', 'prescription', 'healthcare'],
                '1.0.0', 'Initial release',
                34, 4.8, 7, true, true, $A, 15),

            $this->l('pharmacy_lefty_otc', 'thawani_brand', 'pharmacy',
                'HealthTech Solutions', 'Left-Hand OTC Counter',
                'عداد OTC لليد اليسرى',
                'Over-the-counter pharmacy sales layout for left-handed staff. Fast product lookup with icon-based categories and left-side cart.',
                'تخطيط مبيعات الأدوية بدون وصفة للموظفين العسر. بحث سريع عن المنتجات مع فئات بالأيقونات وسلة على الجانب الأيسر.',
                'Left-handed OTC pharmacy counter',
                'كاونتر صيدلية OTC لليد اليسرى',
                $O, 19.99, null,
                ['pharmacy', 'left-handed', 'otc', 'counter'],
                '1.0.0', 'Initial release',
                28, 4.4, 4, false, true, $A, 12),

            $this->l('pharmacy_lefty_insurance_billing', 'high_contrast', 'pharmacy',
                'HealthTech Solutions', 'Left-Hand Insurance Billing',
                'فواتير تأمين لليد اليسرى',
                'Insurance claim processing pharmacy layout with wider left-side panel for claim data entry, patient records, and recent transactions.',
                'تخطيط صيدلية لمعالجة مطالبات التأمين مع لوحة أعرض على الجانب الأيسر لإدخال بيانات المطالبة وسجلات المرضى والمعاملات الأخيرة.',
                'Left-handed pharmacy insurance billing',
                'فواتير تأمين صيدلية لليد اليسرى',
                $S, 34.99, $M,
                ['pharmacy', 'left-handed', 'insurance', 'billing'],
                '1.0.0', 'Initial release',
                19, 4.6, 3, false, true, $A, 10),

            // ── Bakery Left-Handed ──
            $this->l('bakery_lefty_counter', 'sunset_warmth', 'restaurant',
                'BakeSoft', 'Left-Hand Bakery Counter',
                'كاونتر مخبز لليد اليسرى',
                'Walk-in bakery counter with left-side cart and large product images for left-handed cashiers. Icon categories with gift box and custom cake actions.',
                'كاونتر مخبز مع سلة على الجانب الأيسر وصور كبيرة للمنتجات للكاشير الأعسر. فئات بالأيقونات مع إجراءات علبة الهدايا والكيك المخصص.',
                'Left-handed bakery counter layout',
                'تخطيط كاونتر مخبز لليد اليسرى',
                $O, 24.99, null,
                ['bakery', 'left-handed', 'counter', 'visual'],
                '1.0.0', 'Initial release',
                31, 4.3, 5, false, true, $A, 14),

            $this->l('bakery_lefty_production', 'desert_sand', 'restaurant',
                'BakeSoft', 'Left-Hand Production Queue',
                'قائمة إنتاج لليد اليسرى',
                'Bakery layout with left-side order queue and production tracking for left-handed bakers. Includes held orders display and staff notes.',
                'تخطيط مخبز مع قائمة طلبات على الجانب الأيسر وتتبع الإنتاج للخبازين العسر. يتضمن عرض الطلبات المعلقة وملاحظات الموظفين.',
                'Left-handed bakery production tracking',
                'تتبع إنتاج المخبز لليد اليسرى',
                $O, 29.99, null,
                ['bakery', 'left-handed', 'production', 'queue'],
                '1.0.0', 'Initial release',
                22, 4.5, 4, false, true, $A, 11),

            $this->l('bakery_lefty_cake_builder', 'sunset_warmth', 'restaurant',
                'BakeSoft', 'Left-Hand Cake Builder',
                'منشئ كيك لليد اليسرى',
                'Custom cake order builder with left-side configuration panel for left-handed decorators. Includes customer info and delivery scheduling.',
                'أداة إنشاء طلبات الكيك المخصصة مع لوحة تهيئة على الجانب الأيسر للمزينين العسر. يتضمن معلومات العميل وجدولة التوصيل.',
                'Left-handed cake order builder',
                'منشئ طلبات كيك لليد اليسرى',
                $O, 34.99, null,
                ['bakery', 'left-handed', 'cake', 'custom-order'],
                '1.0.0', 'Initial release',
                18, 4.6, 3, false, true, $A, 8),

            // ── Electronics Left-Handed ──
            $this->l('electronics_lefty_imei', 'midnight_blue', 'electronics',
                'TechRetail Pro', 'Left-Hand IMEI Tracker',
                'تتبع IMEI لليد اليسرى',
                'IMEI/serial scanning layout with left-side cart and customer purchase history for left-handed electronics staff.',
                'تخطيط مسح IMEI/المسلسل مع سلة على الجانب الأيسر وسجل شراء العميل للموظفين العسر.',
                'Left-handed IMEI tracking layout',
                'تخطيط تتبع IMEI لليد اليسرى',
                $S, 19.99, $M,
                ['electronics', 'left-handed', 'imei', 'serial'],
                '1.0.0', 'Initial release',
                42, 4.5, 6, false, true, $A, 16),

            $this->l('electronics_lefty_showroom', 'midnight_blue', 'electronics',
                'TechRetail Pro', 'Left-Hand Electronics Showroom',
                'صالة عرض لليد اليسرى',
                'Large-image electronics showroom with left-side checkout panel for left-handed sales associates. Store branding and comparison-ready grid.',
                'صالة عرض إلكترونيات بصور كبيرة مع لوحة دفع على الجانب الأيسر للبائعين العسر. علامة المتجر وشبكة جاهزة للمقارنة.',
                'Left-handed electronics showroom',
                'صالة عرض إلكترونيات لليد اليسرى',
                $O, 39.99, null,
                ['electronics', 'left-handed', 'showroom', 'visual'],
                '1.0.0', 'Initial release',
                27, 4.4, 4, false, true, $A, 13),

            $this->l('electronics_lefty_repair', 'high_contrast', 'electronics',
                'TechRetail Pro', 'Left-Hand Repair Counter',
                'كاونتر صيانة لليد اليسرى',
                'Repair intake and parts lookup layout with left-side order panel, staff notes, and sidebar category navigation for left-handed technicians.',
                'تخطيط استقبال الصيانة والبحث عن القطع مع لوحة طلبات على الجانب الأيسر وملاحظات الموظفين والتنقل بالشريط الجانبي للفنيين العسر.',
                'Left-handed repair intake counter',
                'كاونتر استقبال صيانة لليد اليسرى',
                $O, 29.99, null,
                ['electronics', 'left-handed', 'repair', 'service'],
                '1.0.0', 'Initial release',
                21, 4.3, 3, false, true, $A, 9),

            // ── Florist Left-Handed ──
            $this->l('florist_lefty_arrangement', 'ocean_breeze', 'services',
                'FloralTech', 'Left-Hand Floral Studio',
                'استوديو زهور لليد اليسرى',
                'Floral arrangement and bouquet builder with left-side cart for left-handed florists. Includes weather widget and store branding.',
                'أداة تنسيق الزهور وبناء الباقات مع سلة على الجانب الأيسر للبائعين العسر. يتضمن أداة الطقس وعلامة المتجر.',
                'Left-handed floral arrangement studio',
                'استوديو تنسيق زهور لليد اليسرى',
                $O, 29.99, null,
                ['florist', 'left-handed', 'arrangement', 'bouquet'],
                '1.0.0', 'Initial release',
                24, 4.5, 4, false, true, $A, 11),

            $this->l('florist_lefty_delivery', 'ocean_breeze', 'services',
                'FloralTech', 'Left-Hand Delivery Hub',
                'مركز توصيل لليد اليسرى',
                'Left-handed delivery management with order tracking and scheduling on the left. Held orders for pending deliveries and customer info panel.',
                'إدارة توصيل لليد اليسرى مع تتبع الطلبات والجدولة على الجانب الأيسر. طلبات معلقة للتوصيلات المعلقة ولوحة معلومات العميل.',
                'Left-handed flower delivery management',
                'إدارة توصيل زهور لليد اليسرى',
                $O, 34.99, null,
                ['florist', 'left-handed', 'delivery', 'scheduling'],
                '1.0.0', 'Initial release',
                17, 4.4, 3, false, true, $A, 8),

            $this->l('florist_lefty_event', 'royal_purple', 'services',
                'FloralTech', 'Left-Hand Event Planner',
                'مخطط مناسبات لليد اليسرى',
                'Event and wedding floral planning with left-side cart, customer notes, and purchase history for left-handed event planners.',
                'تنسيق زهور المناسبات والأعراس مع سلة على الجانب الأيسر وملاحظات العميل وسجل الشراء لمنظمي الفعاليات العسر.',
                'Left-handed event floral planning',
                'تنسيق زهور مناسبات لليد اليسرى',
                $O, 34.99, null,
                ['florist', 'left-handed', 'event', 'wedding'],
                '1.0.0', 'Initial release',
                14, 4.6, 2, false, true, $A, 6),

            // ── Jewelry Left-Handed ──
            $this->l('jewelry_lefty_luxury', 'royal_purple', 'premium',
                'LuxDesign Studio', 'Left-Hand Luxury Counter',
                'كاونتر فخامة لليد اليسرى',
                'Premium jewellery counter with left-side cart, gold rate ticker, store branding, and icon-based category navigation for left-handed jewelers.',
                'كاونتر مجوهرات فاخر مع سلة على الجانب الأيسر وعرض أسعار الذهب وعلامة المتجر والتنقل بالأيقونات للصاغة العسر.',
                'Left-handed luxury jewellery counter',
                'كاونتر مجوهرات فاخر لليد اليسرى',
                $O, 59.99, null,
                ['jewelry', 'left-handed', 'luxury', 'gold-rate'],
                '1.0.0', 'Initial release',
                33, 4.7, 5, true, true, $A, 12),

            $this->l('jewelry_lefty_appraisal', 'royal_purple', 'premium',
                'LuxDesign Studio', 'Left-Hand Appraisal Desk',
                'مكتب تقييم لليد اليسرى',
                'Jewellery appraisal and buyback layout with customer history, gold rate display, and wider left-side panel for left-handed appraisers.',
                'تخطيط تقييم وإعادة شراء المجوهرات مع سجل العميل وعرض سعر الذهب ولوحة أعرض على الجانب الأيسر للمقيّمين العسر.',
                'Left-handed jewellery appraisal desk',
                'مكتب تقييم مجوهرات لليد اليسرى',
                $O, 49.99, null,
                ['jewelry', 'left-handed', 'appraisal', 'buyback'],
                '1.0.0', 'Initial release',
                16, 4.5, 3, false, true, $A, 7),

            // ── Fashion Left-Handed ──
            $this->l('fashion_lefty_boutique', 'light_classic', 'fashion',
                'FashionPOS Studio', 'Left-Hand Boutique',
                'بوتيك لليد اليسرى',
                'Fashion boutique checkout with left-side cart, loyalty points display, large product imagery, and brand-focused layout for left-handed staff.',
                'دفع بوتيك أزياء مع سلة على الجانب الأيسر وعرض نقاط الولاء وصور كبيرة للمنتجات وتخطيط يركز على العلامة للموظفين العسر.',
                'Left-handed fashion boutique checkout',
                'دفع بوتيك أزياء لليد اليسرى',
                $O, 29.99, null,
                ['fashion', 'left-handed', 'boutique', 'visual'],
                '1.0.0', 'Initial release',
                37, 4.4, 5, false, true, $A, 14),

            $this->l('fashion_lefty_fitting', 'light_classic', 'fashion',
                'FashionPOS Studio', 'Left-Hand Fitting Room',
                'غرفة قياس لليد اليسرى',
                'Fitting room management with held items tracking, customer info, and left-side cart for left-handed shop assistants.',
                'إدارة غرفة القياس مع تتبع القطع المحجوزة ومعلومات العميل وسلة على الجانب الأيسر لمساعدي المتجر العسر.',
                'Left-handed fitting room management',
                'إدارة غرفة قياس لليد اليسرى',
                $O, 24.99, null,
                ['fashion', 'left-handed', 'fitting-room', 'held-items'],
                '1.0.0', 'Initial release',
                25, 4.3, 4, false, true, $A, 10),

            $this->l('fashion_lefty_returns', 'high_contrast', 'fashion',
                'FashionPOS Studio', 'Left-Hand Returns Desk',
                'مكتب مرتجعات لليد اليسرى',
                'Fashion return and exchange counter with left-side cart, customer purchase history, and recent transactions lookup for left-handed staff.',
                'كاونتر مرتجعات واستبدال أزياء مع سلة على الجانب الأيسر وسجل شراء العميل والمعاملات الأخيرة للموظفين العسر.',
                'Left-handed fashion returns desk',
                'مكتب مرتجعات أزياء لليد اليسرى',
                $O, 24.99, null,
                ['fashion', 'left-handed', 'returns', 'exchange'],
                '1.0.0', 'Initial release',
                20, 4.2, 3, false, true, $A, 8),

            // ══════════════════════════════════════════════════
            // CREATIVE RIGHT-HANDED LAYOUTS (40 listings)
            // ══════════════════════════════════════════════════

            // ── Grocery Creative ──
            $this->l('grocery_self_checkout', 'light_classic', 'grocery',
                'SpeedCheckout', 'Self-Checkout Kiosk',
                'كشك الدفع الذاتي',
                'Customer-facing self-checkout kiosk with large product tiles, numpad for quantity entry, and card/wallet payment only. Minimal staff intervention needed.',
                'كشك دفع ذاتي للعميل مع بلاطات منتجات كبيرة ولوحة أرقام لإدخال الكمية ودفع بالبطاقة/المحفظة فقط. الحد الأدنى من تدخل الموظفين.',
                'Customer self-checkout kiosk',
                'كشك دفع ذاتي للعملاء',
                $O, 49.99, null,
                ['grocery', 'self-checkout', 'kiosk', 'customer-facing'],
                '1.0.0', 'Initial release',
                156, 4.6, 18, true, true, $A, 35),

            $this->l('grocery_bottom_cart', 'forest_green', 'grocery',
                'RetailMax', 'Bottom Cart Panoramic',
                'سلة سفلية بانورامية',
                'Full-width product grid with cart panel at the bottom — ideal for wide touchscreens and landscape tablets. 6-column product grid maximizes visibility.',
                'شبكة منتجات بعرض كامل مع لوحة السلة في الأسفل — مثالي للشاشات العريضة والأجهزة اللوحية الأفقية. شبكة من 6 أعمدة تعزز الرؤية.',
                'Panoramic layout with bottom cart',
                'تخطيط بانورامي بسلة سفلية',
                $O, 29.99, null,
                ['grocery', 'panoramic', 'widescreen', 'tablet'],
                '1.0.0', 'Initial release',
                78, 4.3, 9, false, true, $A, 30),

            $this->l('grocery_dual_screen', 'dark_mode', 'grocery',
                'SpeedCheckout', 'Dual-Screen Express',
                'شاشة مزدوجة سريعة',
                'Optimized for dual-monitor setup: cashier gets compact barcode-focused list, customer screen shows cart. Auto-submit barcode scanning.',
                'محسّن لإعداد الشاشة المزدوجة: يحصل الكاشير على قائمة مركزة بالباركود والعميل يرى السلة. مسح باركود تلقائي.',
                'Dual-screen express checkout',
                'دفع سريع بشاشة مزدوجة',
                $O, 59.99, null,
                ['grocery', 'dual-screen', 'barcode', 'express'],
                '2.0.0', 'v2.0: Auto-submit barcode, numpad improvement',
                134, 4.7, 22, true, true, $A, 40),

            $this->l('grocery_senior_friendly', 'high_contrast', 'grocery',
                'AccessPOS', 'Senior-Friendly Large Text',
                'نص كبير لكبار السن',
                'Accessibility-focused layout with 1.5× font scaling, extra-large buttons, high contrast theme, and simplified 2-column product grid.',
                'تخطيط مركّز على سهولة الوصول مع تكبير الخط 1.5 مرة وأزرار كبيرة جداً وسمة عالية التباين وشبكة منتجات من عمودين.',
                'Accessible large-text grocery layout',
                'تخطيط بقالة بنص كبير لسهولة الوصول',
                $F, 0, null,
                ['grocery', 'accessible', 'senior', 'large-text', 'free'],
                '1.0.0', 'Initial release',
                234, 4.8, 31, true, true, $A, 45),

            $this->l('grocery_night_shift', 'dark_mode', 'grocery',
                'RetailMax', 'Night Shift Dark Mode',
                'الوضع الليلي',
                'Dark UI grocery layout for night-shift cashiers with reduced eye strain, high-contrast buttons, and full barcode scanning support.',
                'تخطيط بقالة بواجهة داكنة لكاشير الوردية الليلية مع تقليل إجهاد العين وأزرار عالية التباين ودعم كامل لمسح الباركود.',
                'Dark mode grocery for night shifts',
                'وضع داكن بقالة للورديات الليلية',
                $F, 0, null,
                ['grocery', 'dark-mode', 'night-shift', 'free'],
                '1.0.0', 'Initial release',
                189, 4.5, 16, false, true, $A, 38),

            // ── Restaurant Creative ──
            $this->l('restaurant_drive_through', 'dark_mode', 'restaurant',
                'FoodTech Arabia', 'Drive-Through Lane',
                'مسار الطلب من السيارة',
                'Drive-through lane layout with order timer, large menu item buttons, combo selection, and upsell prompts. Optimized for speed and accuracy.',
                'تخطيط مسار الطلب من السيارة مع مؤقت الطلب وأزرار قائمة كبيرة واختيار الوجبات المجمعة وعروض البيع الإضافي. محسّن للسرعة والدقة.',
                'Drive-through order lane',
                'مسار طلبات السيارة',
                $O, 44.99, null,
                ['restaurant', 'drive-through', 'speed', 'combo'],
                '1.0.0', 'Initial release',
                98, 4.6, 14, true, true, $A, 32),

            $this->l('restaurant_buffet_counter', 'sunset_warmth', 'restaurant',
                'FoodTech Arabia', 'Buffet / Weight-Based',
                'بوفيه / حسب الوزن',
                'Buffet-style pricing by weight with integrated scale display, numpad for manual weight entry, and per-item or per-kg pricing modes.',
                'تسعير بوفيه بالوزن مع عرض ميزان متكامل ولوحة أرقام لإدخال الوزن يدوياً وأوضاع تسعير بالقطعة أو بالكيلو.',
                'Buffet and weight-based pricing',
                'تسعير بوفيه وحسب الوزن',
                $O, 34.99, null,
                ['restaurant', 'buffet', 'weight', 'scale'],
                '1.0.0', 'Initial release',
                56, 4.4, 7, false, true, $A, 22),

            $this->l('restaurant_bar_tabs', 'midnight_blue', 'restaurant',
                'FoodTech Arabia', 'Bar Tabs Manager',
                'مدير حسابات البار',
                'Bar and lounge layout with multiple open tabs display, drink-focused categories, split bill, and tab transfer between customers.',
                'تخطيط بار وصالة مع عرض حسابات متعددة مفتوحة وفئات مركزة على المشروبات وتقسيم الفاتورة ونقل الحساب بين العملاء.',
                'Multi-tab bar management layout',
                'تخطيط إدارة حسابات البار المتعددة',
                $O, 39.99, null,
                ['restaurant', 'bar', 'tabs', 'lounge', 'split-bill'],
                '1.0.0', 'Initial release',
                43, 4.5, 6, false, true, $A, 20),

            $this->l('restaurant_catering', 'desert_sand', 'restaurant',
                'FoodTech Arabia', 'Catering & Bulk Orders',
                'التموين والطلبات الكبيرة',
                'Large-quantity catering order layout with sidebar categories, customer info, delivery scheduling, staff notes, and Hijri calendar support.',
                'تخطيط طلبات التموين الكبيرة مع فئات جانبية ومعلومات العميل وجدولة التوصيل وملاحظات الموظفين ودعم التقويم الهجري.',
                'Catering and bulk order management',
                'إدارة التموين والطلبات الكبيرة',
                $O, 44.99, null,
                ['restaurant', 'catering', 'bulk', 'delivery', 'hijri'],
                '1.0.0', 'Initial release',
                35, 4.6, 5, false, true, $A, 16),

            $this->l('restaurant_food_truck', 'sunset_warmth', 'restaurant',
                'SpeedCheckout', 'Food Truck Compact',
                'عربة الطعام المدمجة',
                'Ultra-compact bottom-cart layout for small food truck tablets. Store branding, big product images, and minimal button taps to complete an order.',
                'تخطيط مدمج جداً بسلة سفلية لأجهزة عربات الطعام اللوحية الصغيرة. علامة المتجر وصور منتجات كبيرة وأقل عدد لمسات لإتمام الطلب.',
                'Compact food truck tablet layout',
                'تخطيط مدمج لعربة الطعام اللوحية',
                $F, 0, null,
                ['restaurant', 'food-truck', 'compact', 'tablet', 'free'],
                '1.0.0', 'Initial release',
                212, 4.7, 28, true, true, $A, 42),

            // ── Pharmacy Creative ──
            $this->l('pharmacy_clinical_consultation', 'thawani_brand', 'pharmacy',
                'HealthTech Solutions', 'Clinical Consultation Suite',
                'مجموعة الاستشارة السريرية',
                'Consultation room layout with patient info, prescription history, drug interaction notes, sidebar categories, and stock level indicators.',
                'تخطيط غرفة الاستشارة مع معلومات المريض وسجل الوصفات وملاحظات تفاعل الأدوية وفئات جانبية ومؤشرات مستوى المخزون.',
                'Clinical pharmacy consultation layout',
                'تخطيط استشارة صيدلية سريرية',
                $S, 39.99, $M,
                ['pharmacy', 'consultation', 'clinical', 'patient-management'],
                '1.0.0', 'Initial release',
                62, 4.8, 11, true, true, $A, 28),

            $this->l('pharmacy_drive_through', 'forest_green', 'pharmacy',
                'SpeedCheckout', 'Pharmacy Drive-Through',
                'صيدلية من السيارة',
                'Drive-through pharmacy window with oversized search bar for prescription barcode scanning, compact cart, and rapid insurance/card payment.',
                'نافذة صيدلية للسيارة مع شريط بحث كبير لمسح باركود الوصفة وسلة مدمجة ودفع سريع بالتأمين/البطاقة.',
                'Drive-through pharmacy pickup',
                'صيدلية توصيل من السيارة',
                $O, 34.99, null,
                ['pharmacy', 'drive-through', 'prescription', 'speed'],
                '1.0.0', 'Initial release',
                47, 4.5, 6, false, true, $A, 18),

            $this->l('pharmacy_cosmetics_aisle', 'ocean_breeze', 'pharmacy',
                'RetailMax', 'Cosmetics & Beauty Counter',
                'كاونتر مستحضرات التجميل',
                'Pharmacy beauty section layout with large product images, loyalty points, promotional banners, and icon-based category browsing.',
                'تخطيط قسم التجميل في الصيدلية مع صور كبيرة ونقاط ولاء ولافتات ترويجية وتصفح بالأيقونات.',
                'Pharmacy cosmetics and beauty counter',
                'كاونتر مستحضرات تجميل الصيدلية',
                $O, 24.99, null,
                ['pharmacy', 'cosmetics', 'beauty', 'visual'],
                '1.0.0', 'Initial release',
                73, 4.3, 8, false, true, $A, 22),

            $this->l('pharmacy_veterinary', 'forest_green', 'pharmacy',
                'HealthTech Solutions', 'Veterinary Pharmacy',
                'صيدلية بيطرية',
                'Vet pharmacy layout with animal type icon categories, weight-based dosing reference, staff clinical notes, and prescription label printing.',
                'تخطيط صيدلية بيطرية مع فئات بأيقونات أنواع الحيوانات ومرجع الجرعات بالوزن وملاحظات الموظفين السريرية وطباعة ملصقات الوصفات.',
                'Veterinary pharmacy with dosing support',
                'صيدلية بيطرية مع دعم الجرعات',
                $S, 29.99, $M,
                ['pharmacy', 'veterinary', 'vet', 'animal', 'dosing'],
                '1.0.0', 'Initial release',
                28, 4.6, 4, false, true, $A, 12),

            // ── Bakery Creative ──
            $this->l('bakery_morning_rush', 'sunset_warmth', 'restaurant',
                'SpeedCheckout', 'Morning Rush Express',
                'الذروة الصباحية السريعة',
                'Speed-optimized bakery layout for morning rush. Favorites-first product grid, compact cart, oversized search bar, and minimal taps to checkout.',
                'تخطيط مخبز محسّن للسرعة لذروة الصباح. شبكة منتجات بالمفضلة أولاً وسلة مدمجة وشريط بحث كبير وأقل لمسات للدفع.',
                'Speed-first bakery morning checkout',
                'دفع مخبز سريع صباحي',
                $F, 0, null,
                ['bakery', 'express', 'morning-rush', 'speed', 'free'],
                '1.0.0', 'Initial release',
                167, 4.5, 19, false, true, $A, 35),

            $this->l('bakery_wholesale', 'desert_sand', 'restaurant',
                'BakeSoft', 'Wholesale Bakery Orders',
                'طلبات جملة المخبز',
                'Wholesale bakery layout with sidebar categories, numpad for bulk quantities, customer credit accounts, and invoice printing.',
                'تخطيط مخبز جملة مع فئات جانبية ولوحة أرقام للكميات الكبيرة وحسابات ائتمان العملاء وطباعة الفواتير.',
                'Wholesale bakery with credit accounts',
                'مخبز جملة مع حسابات ائتمان',
                $O, 39.99, null,
                ['bakery', 'wholesale', 'bulk', 'invoice', 'credit'],
                '1.0.0', 'Initial release',
                38, 4.4, 5, false, true, $A, 15),

            $this->l('bakery_display_case', 'light_classic', 'restaurant',
                'BakeSoft', 'Display Case Visual',
                'علبة العرض المرئية',
                'Visually rich bakery layout mimicking a display case with large zoomable product photos, narrow cart, and gift box quick action.',
                'تخطيط مخبز غني بصرياً يحاكي علبة العرض مع صور كبيرة قابلة للتكبير وسلة ضيقة وإجراء سريع لعلبة الهدايا.',
                'Visual bakery display case layout',
                'تخطيط علبة عرض المخبز المرئية',
                $O, 29.99, null,
                ['bakery', 'visual', 'display-case', 'photos'],
                '1.0.0', 'Initial release',
                54, 4.6, 7, false, true, $A, 20),

            $this->l('bakery_cafe_combo', 'sunset_warmth', 'restaurant',
                'BakeSoft', 'Bakery + Café Combo',
                'مخبز + مقهى مدمج',
                'Combined bakery and café layout with dine-in order tracking, staff notes for customizations, and tabbed food/drink categories.',
                'تخطيط مخبز ومقهى مدمج مع تتبع طلبات تناول الطعام وملاحظات الموظفين للتخصيصات وفئات طعام/شراب بعلامات تبويب.',
                'Combined bakery and café layout',
                'تخطيط مخبز ومقهى مدمج',
                $O, 34.99, null,
                ['bakery', 'cafe', 'combo', 'dine-in'],
                '1.0.0', 'Initial release',
                61, 4.5, 8, false, true, $A, 22),

            // ── Electronics Creative ──
            $this->l('electronics_comparison_grid', 'midnight_blue', 'electronics',
                'TechRetail Pro', 'Product Comparison Grid',
                'شبكة مقارنة المنتجات',
                'Side-by-side product comparison layout for smartphones, laptops, and gadgets. Spec-aware grid tiles with compare quick action.',
                'تخطيط مقارنة منتجات جنباً إلى جنب للهواتف والحواسيب والأجهزة. بلاطات شبكية بالمواصفات مع إجراء سريع للمقارنة.',
                'Electronics product comparison grid',
                'شبكة مقارنة منتجات إلكترونيات',
                $O, 34.99, null,
                ['electronics', 'comparison', 'specs', 'grid'],
                '1.0.0', 'Initial release',
                82, 4.5, 11, false, true, $A, 25),

            $this->l('electronics_trade_in', 'high_contrast', 'electronics',
                'TechRetail Pro', 'Trade-In & Buyback Hub',
                'مركز الاستبدال والشراء',
                'Device buyback and trade-in layout with condition grading, IMEI verification, customer purchase history, and cash/transfer payout options.',
                'تخطيط إعادة شراء واستبدال الأجهزة مع تصنيف الحالة والتحقق من IMEI وسجل شراء العميل وخيارات الصرف نقداً/تحويل.',
                'Device trade-in and buyback layout',
                'تخطيط استبدال وإعادة شراء الأجهزة',
                $O, 44.99, null,
                ['electronics', 'trade-in', 'buyback', 'imei', 'condition'],
                '1.0.0', 'Initial release',
                45, 4.6, 6, false, true, $A, 18),

            $this->l('electronics_gaming_corner', 'midnight_blue', 'electronics',
                'RetailMax', 'Gaming Corner',
                'ركن الألعاب',
                'Gaming accessories and console sales layout with hero promotional banner, large visual tiles, loyalty points, and gift card actions.',
                'تخطيط بيع إكسسوارات وأجهزة الألعاب مع لافتة ترويجية كبيرة وبلاطات مرئية ضخمة ونقاط ولاء وإجراءات بطاقات الهدايا.',
                'Gaming accessories and console sales',
                'مبيعات إكسسوارات وأجهزة الألعاب',
                $O, 29.99, null,
                ['electronics', 'gaming', 'console', 'accessories'],
                '1.0.0', 'Initial release',
                97, 4.7, 14, true, true, $A, 30),

            $this->l('electronics_accessory_wall', 'light_classic', 'electronics',
                'SpeedCheckout', 'Accessory Wall Express',
                'جدار الإكسسوارات السريع',
                'Fast-checkout layout for phone cases, chargers, and small accessories. 5-column wide grid, compact cart, and barcode-first scanning.',
                'تخطيط دفع سريع لحافظات الهواتف والشواحن والإكسسوارات الصغيرة. شبكة عريضة من 5 أعمدة وسلة مدمجة ومسح باركود أولاً.',
                'Fast accessory checkout with wide grid',
                'دفع سريع للإكسسوارات بشبكة عريضة',
                $F, 0, null,
                ['electronics', 'accessories', 'express', 'compact', 'free'],
                '1.0.0', 'Initial release',
                143, 4.4, 12, false, true, $A, 32),

            // ── Florist Creative ──
            $this->l('florist_subscription_manager', 'ocean_breeze', 'services',
                'FloralTech', 'Subscription Manager',
                'مدير الاشتراكات',
                'Weekly/monthly flower subscription management with recurring order tracking, active subscription list, and customer renewal scheduling.',
                'إدارة اشتراكات الزهور الأسبوعية/الشهرية مع تتبع الطلبات المتكررة وقائمة الاشتراكات النشطة وجدولة تجديد العملاء.',
                'Flower subscription management',
                'إدارة اشتراكات الزهور',
                $S, 24.99, $M,
                ['florist', 'subscription', 'recurring', 'scheduling'],
                '1.0.0', 'Initial release',
                31, 4.5, 4, false, true, $A, 12),

            $this->l('florist_seasonal_showcase', 'ocean_breeze', 'seasonal',
                'FloralTech', 'Seasonal Floral Showcase',
                'عروض الزهور الموسمية',
                'Seasonal promotion layout with hero banner, weather-aware suggestions, icon-based categories, and gift card quick action.',
                'تخطيط عروض موسمية مع لافتة رئيسية واقتراحات ترتبط بالطقس وفئات بالأيقونات وإجراء سريع لبطاقات الهدايا.',
                'Seasonal flower showcase with weather',
                'عرض زهور موسمي مع الطقس',
                $O, 19.99, null,
                ['florist', 'seasonal', 'weather', 'showcase', 'promo'],
                '1.0.0', 'Initial release',
                48, 4.4, 6, false, true, $A, 16),

            $this->l('florist_garden_center', 'forest_green', 'services',
                'FloralTech', 'Garden Center',
                'مركز الحدائق',
                'Outdoor garden center layout with sidebar plant categories, weather widget, large product images, and delivery scheduling.',
                'تخطيط مركز حدائق خارجي مع فئات نباتات جانبية وأداة الطقس وصور كبيرة للمنتجات وجدولة التوصيل.',
                'Garden center with plant categories',
                'مركز حدائق مع فئات النباتات',
                $O, 29.99, null,
                ['florist', 'garden', 'plants', 'outdoor'],
                '1.0.0', 'Initial release',
                36, 4.3, 5, false, true, $A, 14),

            $this->l('florist_funeral_sympathy', 'light_classic', 'services',
                'FloralTech', 'Funeral & Sympathy',
                'باقات التعزية',
                'Subdued, respectful layout for funeral and sympathy arrangements with delivery scheduling, custom message cards, and holding queue.',
                'تخطيط هادئ ومحترم لباقات التعزية والجنازة مع جدولة التوصيل وبطاقات رسائل مخصصة وقائمة انتظار.',
                'Funeral and sympathy arrangements',
                'ترتيبات الجنازة والتعزية',
                $O, 24.99, null,
                ['florist', 'funeral', 'sympathy', 'delivery'],
                '1.0.0', 'Initial release',
                22, 4.7, 3, false, true, $A, 8),

            // ── Jewelry Creative ──
            $this->l('jewelry_bridal_registry', 'royal_purple', 'premium',
                'LuxDesign Studio', 'Bridal Registry',
                'سجل العرائس',
                'Bridal and engagement ring selection with customer wishlist, gold rate display, sizing notes, and engraving/certificate quick actions.',
                'اختيار خواتم الزفاف والخطوبة مع قائمة أمنيات العميل وعرض سعر الذهب وملاحظات المقاس وإجراءات سريعة للنقش/الشهادة.',
                'Bridal jewellery registry and wishlist',
                'سجل مجوهرات العرائس وقائمة الأمنيات',
                $O, 59.99, null,
                ['jewelry', 'bridal', 'registry', 'engagement', 'engraving'],
                '1.0.0', 'Initial release',
                52, 4.8, 9, true, true, $A, 22),

            $this->l('jewelry_watch_counter', 'midnight_blue', 'premium',
                'LuxDesign Studio', 'Luxury Watch Counter',
                'كاونتر الساعات الفاخرة',
                'Luxury watch showroom counter with store branding, brand-based icon categories, customer loyalty tracking, and warranty registration.',
                'كاونتر صالة عرض ساعات فاخرة مع علامة المتجر وفئات بأيقونات العلامات التجارية وتتبع ولاء العميل وتسجيل الضمان.',
                'Luxury watch showroom counter',
                'كاونتر صالة ساعات فاخرة',
                $O, 69.99, null,
                ['jewelry', 'watches', 'luxury', 'warranty', 'branding'],
                '1.0.0', 'Initial release',
                41, 4.6, 6, false, true, $A, 18),

            $this->l('jewelry_gold_souk', 'desert_sand', 'premium',
                'LuxDesign Studio', 'Gold Souk Traditional',
                'سوق الذهب التقليدي',
                'Traditional gold souk layout with live gold rate display for all karats, weight calculator, numpad, and certificate generation.',
                'تخطيط سوق ذهب تقليدي مع عرض حي لأسعار الذهب لجميع العيارات وآلة حساب الوزن ولوحة أرقام وإنشاء شهادات.',
                'Traditional gold souk with live rates',
                'سوق ذهب تقليدي بأسعار حية',
                $O, 49.99, null,
                ['jewelry', 'gold-souk', 'traditional', 'karat', 'weight'],
                '1.0.0', 'Initial release',
                78, 4.7, 12, true, true, $A, 25),

            $this->l('jewelry_repair_workshop', 'high_contrast', 'services',
                'LuxDesign Studio', 'Jewellery Repair Workshop',
                'ورشة إصلاح المجوهرات',
                'Repair intake and job tracking layout with sidebar categories, customer history, staff notes, active repair queue, and label printing.',
                'تخطيط استقبال وتتبع مهام الإصلاح مع فئات جانبية وسجل العميل وملاحظات الموظفين وقائمة الإصلاحات النشطة وطباعة الملصقات.',
                'Jewellery repair intake and tracking',
                'استقبال وتتبع إصلاح المجوهرات',
                $O, 39.99, null,
                ['jewelry', 'repair', 'workshop', 'job-tracking'],
                '1.0.0', 'Initial release',
                29, 4.4, 4, false, true, $A, 12),

            // ── Fashion Creative ──
            $this->l('fashion_personal_shopper', 'light_classic', 'fashion',
                'FashionPOS Studio', 'Personal Shopper',
                'المتسوق الشخصي',
                'Personal shopping assistant layout with customer preferences, purchase history, loyalty display, staff notes for styling, and large product grid.',
                'تخطيط مساعد تسوق شخصي مع تفضيلات العميل وسجل الشراء وعرض الولاء وملاحظات الموظفين للتنسيق وشبكة منتجات كبيرة.',
                'Personal shopping assistant layout',
                'تخطيط مساعد التسوق الشخصي',
                $O, 39.99, null,
                ['fashion', 'personal-shopper', 'styling', 'loyalty'],
                '1.0.0', 'Initial release',
                64, 4.6, 9, false, true, $A, 22),

            $this->l('fashion_seasonal_sale', 'sunset_warmth', 'seasonal',
                'RetailMax', 'Seasonal Sale Blitz',
                'عروض الموسم',
                'High-volume seasonal sale layout with hero promotional banners, barcode scanning, compact cart, and fast discount application.',
                'تخطيط عروض موسمية لحجم مبيعات عالي مع لافتات ترويجية كبيرة ومسح الباركود وسلة مدمجة وتطبيق خصم سريع.',
                'Seasonal sale high-volume layout',
                'تخطيط عروض موسمية لحجم عالي',
                $O, 19.99, null,
                ['fashion', 'seasonal', 'sale', 'promo', 'high-volume'],
                '1.0.0', 'Initial release',
                156, 4.5, 18, true, true, $A, 35),

            $this->l('fashion_pop_up_shop', 'sunset_warmth', 'fashion',
                'SpeedCheckout', 'Pop-Up Shop Mobile',
                'المتجر المؤقت',
                'Ultra-portable layout for pop-up shops and fashion markets. Bottom cart, store branding, and works perfectly on any tablet in landscape.',
                'تخطيط محمول جداً للمتاجر المؤقتة وأسواق الأزياء. سلة سفلية وعلامة المتجر ويعمل بشكل مثالي على أي جهاز لوحي أفقي.',
                'Portable pop-up shop tablet layout',
                'تخطيط محمول للمتجر المؤقت',
                $F, 0, null,
                ['fashion', 'pop-up', 'portable', 'tablet', 'free'],
                '1.0.0', 'Initial release',
                234, 4.7, 32, true, true, $A, 40),

            $this->l('fashion_vip_lounge', 'royal_purple', 'premium',
                'FashionPOS Studio', 'VIP Lounge Experience',
                'تجربة صالة كبار الشخصيات',
                'Premium VIP shopping experience with store branding, customer history, loyalty rewards, and dedicated high-end aesthetic.',
                'تجربة تسوق VIP فاخرة مع علامة المتجر وسجل العميل ومكافآت الولاء وجمالية راقية مخصصة.',
                'Premium VIP shopping experience',
                'تجربة تسوق VIP فاخرة',
                $O, 69.99, null,
                ['fashion', 'vip', 'luxury', 'premium', 'branding'],
                '1.0.0', 'Initial release',
                47, 4.8, 8, true, true, $A, 20),

            $this->l('fashion_outlet_clearance', 'high_contrast', 'fashion',
                'SpeedCheckout', 'Outlet Clearance',
                'تصفية المنفذ',
                'High-speed outlet checkout with barcode auto-submit, compact list, numpad, and volume discount support — scan and go.',
                'دفع منفذ عالي السرعة مع إرسال تلقائي للباركود وقائمة مدمجة ولوحة أرقام ودعم خصم الكمية — امسح وامضِ.',
                'High-speed outlet scan-and-go',
                'دفع سريع بالمسح والمتابعة',
                $F, 0, null,
                ['fashion', 'outlet', 'clearance', 'barcode', 'free'],
                '1.0.0', 'Initial release',
                178, 4.4, 15, false, true, $A, 33),

            // ── Universal / Cross-Business ──
            $this->l('universal_receipt_preview', 'light_classic', 'retail',
                'Thawani Official', 'Receipt Preview Mode',
                'وضع معاينة الإيصال',
                'Layout with live receipt preview alongside the cart — ideal for staff training, order verification, and customer transparency.',
                'تخطيط مع معاينة حية للإيصال بجانب السلة — مثالي لتدريب الموظفين والتحقق من الطلبات وشفافية العميل.',
                'Live receipt preview training layout',
                'تخطيط تدريبي مع معاينة إيصال حية',
                $F, 0, null,
                ['receipt', 'preview', 'training', 'verification', 'free'],
                '1.0.0', 'Initial release',
                267, 4.6, 24, false, true, $A, 45),

            $this->l('universal_training_mode', 'thawani_brand', 'retail',
                'Thawani Official', 'Training Mode Layout',
                'وضع التدريب',
                'All widgets visible and labeled — store branding, clock, weather, promo banner, loyalty, numpad, customer info, held orders, recent transactions, and more.',
                'جميع الأدوات مرئية ومصنفة — علامة المتجر والساعة والطقس ولافتة العروض والولاء ولوحة الأرقام ومعلومات العميل والطلبات المعلقة والمعاملات الأخيرة والمزيد.',
                'Full-widget training layout for onboarding',
                'تخطيط تدريبي كامل الأدوات للتأهيل',
                $F, 0, null,
                ['training', 'onboarding', 'all-widgets', 'demo', 'free'],
                '1.0.0', 'Initial release',
                345, 4.8, 38, true, true, $A, 50),

            $this->l('universal_numpad_heavy', 'dark_mode', 'retail',
                'AccessPOS', 'Numpad-Heavy Data Entry',
                'إدخال بيانات بلوحة الأرقام',
                'Data-entry focused layout with prominent numpad, search-first design, and compact list view. Perfect for manual price/quantity workflows.',
                'تخطيط مركّز على إدخال البيانات مع لوحة أرقام بارزة وتصميم بحث أولاً وعرض قائمة مدمج. مثالي لسير عمل السعر/الكمية اليدوي.',
                'Numpad-focused data entry layout',
                'تخطيط إدخال بيانات بلوحة أرقام',
                $F, 0, null,
                ['numpad', 'data-entry', 'manual', 'compact', 'free'],
                '1.0.0', 'Initial release',
                112, 4.3, 10, false, true, $A, 28),

            $this->l('universal_minimal_zen', 'light_classic', 'minimal',
                'Thawani Official', 'Minimal Zen',
                'الحد الأدنى زن',
                'Ultra-clean minimal layout — only search, product list, cart, and payment. Zero distractions, zero clutter. The fastest checkout possible.',
                'تخطيط نظيف جداً وبسيط — فقط البحث وقائمة المنتجات والسلة والدفع. صفر إلهاء وصفر فوضى. أسرع دفع ممكن.',
                'Ultra-minimal zero-distraction layout',
                'تخطيط بسيط جداً بدون إلهاء',
                $F, 0, null,
                ['minimal', 'zen', 'clean', 'simple', 'free'],
                '1.0.0', 'Initial release',
                398, 4.9, 52, true, true, $A, 55),

            $this->l('universal_split_screen', 'thawani_brand', 'retail',
                'Thawani Official', 'Split-Screen Dual View',
                'عرض مزدوج مقسم',
                'Split-screen layout with product grid on top and held orders + recent transactions below. Great for comparing products while building orders.',
                'تخطيط شاشة مقسمة مع شبكة منتجات في الأعلى وطلبات معلقة + معاملات أخيرة في الأسفل. ممتاز لمقارنة المنتجات أثناء بناء الطلبات.',
                'Split-screen product and order view',
                'عرض مقسم للمنتجات والطلبات',
                $F, 0, null,
                ['split-screen', 'dual-view', 'comparison', 'free'],
                '1.0.0', 'Initial release',
                156, 4.5, 14, false, true, $A, 35),
        ];
    }

    /**
     * Helper to build a listing array with less repetition.
     */
    private function l(
        string $layoutKey, string $themeSlug, string $catSlug,
        string $publisher, string $title, string $titleAr,
        string $desc, string $descAr,
        string $shortDesc, string $shortDescAr,
        MarketplacePricingType $pricing, float $price, ?SubscriptionInterval $interval,
        array $tags, string $version, string $changelog,
        int $downloads, float $rating, int $reviews,
        bool $featured, bool $verified,
        MarketplaceListingStatus $status, int $daysAgo,
    ): array {
        return [
            '_layout_key'            => $layoutKey,
            '_theme_slug'            => $themeSlug,
            '_category_slug'         => $catSlug,
            'publisher_name'         => $publisher,
            'publisher_avatar_url'   => null,
            'title'                  => $title,
            'title_ar'               => $titleAr,
            'description'            => $desc,
            'description_ar'         => $descAr,
            'short_description'      => $shortDesc,
            'short_description_ar'   => $shortDescAr,
            'preview_images'         => [],
            'pricing_type'           => $pricing,
            'price_amount'           => $price,
            'price_currency'         => 'SAR',
            'subscription_interval'  => $interval,
            'tags'                   => $tags,
            'version'                => $version,
            'changelog'              => $changelog,
            'download_count'         => $downloads,
            'average_rating'         => $rating,
            'review_count'           => $reviews,
            'is_featured'            => $featured,
            'is_verified'            => $verified,
            'status'                 => $status,
            'approved_at'            => $status === MarketplaceListingStatus::Approved ? now()->subDays($daysAgo) : null,
            'published_at'           => $status === MarketplaceListingStatus::Approved ? now()->subDays($daysAgo) : null,
        ];
    }
}
