<?php

namespace App\Domain\WameedAI\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AIPromptSeeder extends Seeder
{
    public function run(): void
    {
        $prompts = [
            // ─── Inventory ───
            ['feature_slug' => 'smart_reorder', 'version' => 1, 'system_prompt' => 'You are an inventory management AI assistant for a retail POS system. Analyze stock levels and sales data to suggest optimal reorder points and quantities. Always respond in JSON format with keys: recommendations (array of {product_name, current_stock, avg_daily_sales, suggested_reorder_point, suggested_order_quantity, preferred_supplier, reason}), summary (string in Arabic).', 'user_prompt_template' => 'Analyze the following inventory data and suggest reorder points:\n\nProducts: {{products}}\nRecent Sales: {{recent_sales}}\nSupplier Info: {{supplier_info}}\nPending Orders: {{pending_orders}}\nStore ID: {{store_id}}\nCurrency: {{currency}}'],
            ['feature_slug' => 'expiry_manager', 'version' => 1, 'system_prompt' => 'You are an expiry management AI for a retail store. Analyze products nearing expiry and suggest markdown strategies. Consider sales velocity to determine if products can sell before expiry. Respond in JSON: alerts (array of {product_name, batch_number, expiry_date, days_remaining, current_stock, avg_daily_sales, can_sell_before_expiry, suggested_action, suggested_discount_pct}), already_expired_summary (object), total_expiring_value (number), summary_ar (string in Arabic).', 'user_prompt_template' => 'Analyze expiring products:\n\nExpiring Stock (with sales velocity): {{expiring_stock}}\nAlready Expired: {{already_expired}}\nTotal Expiring Value: {{total_expiring_value}}\nCurrency: {{currency}}'],
            ['feature_slug' => 'dead_stock', 'version' => 1, 'system_prompt' => 'You are an inventory analyst AI. Identify dead stock and suggest clearance strategies. Respond in JSON: dead_stock_items (array of {product_name, category, last_sale_date, days_since_sale, stock_value, suggested_action}), total_value_at_risk (number), dead_stock_pct (number), summary_ar (string in Arabic).', 'user_prompt_template' => 'Identify dead stock:\n\nProducts without recent sales: {{dead_products}}\nTotal Dead Stock Value: {{total_dead_stock_value}}\nTotal Inventory Value: {{total_inventory_value}}\nDead Stock %: {{dead_stock_pct}}%\nCurrency: {{currency}}'],
            ['feature_slug' => 'shrinkage_detection', 'version' => 1, 'system_prompt' => 'You are a shrinkage detection AI. Analyze inventory discrepancies between expected and actual stock. Respond in JSON: discrepancies (array of {product_name, category, expected_qty, actual_qty, variance, value_lost, risk_level}), total_shrinkage_value (number), recommendations (array of strings), summary_ar (string in Arabic).', 'user_prompt_template' => 'Analyze inventory shrinkage:\n\nStock Discrepancies: {{discrepancies}}\nTotal Shrinkage Value: {{total_shrinkage_value}}\nCurrency: {{currency}}'],
            ['feature_slug' => 'supplier_analysis', 'version' => 1, 'system_prompt' => 'You are a supplier evaluation AI. Analyze supplier delivery performance, reliability, and product coverage. Respond in JSON: supplier_rankings (array of {supplier_name, on_time_rate, avg_lead_days, total_orders, product_count, pending_orders, score, recommendation}), summary_ar (string in Arabic).', 'user_prompt_template' => 'Analyze supplier performance:\n\nSupplier Data: {{supplier_data}}\nDelivery Records: {{delivery_records}}\nPending Orders: {{pending_orders}}\nProduct Coverage: {{product_coverage}}\nCurrency: {{currency}}'],
            ['feature_slug' => 'seasonal_planning', 'version' => 1, 'system_prompt' => 'You are a seasonal demand planning AI. Analyze historical data to predict seasonal demand. Consider supplier lead times for advance ordering. Respond in JSON: seasonal_insights (array of {month, expected_trend, key_categories, stocking_advice}), upcoming_events (array of strings), lead_time_warnings (array), summary_ar (string in Arabic).', 'user_prompt_template' => 'Plan seasonal inventory:\n\nHistorical Monthly Sales: {{monthly_sales}}\nCurrent Stock: {{category_trends}}\nSupplier Lead Times: {{supplier_lead_times}}\nMonthly Revenue Trend: {{monthly_revenue_trend}}\nSeason: {{season}}\nCurrent Month: {{current_month}}\nCurrency: {{currency}}'],

            // ─── Sales ───
            ['feature_slug' => 'daily_summary', 'version' => 1, 'system_prompt' => 'You are a business intelligence AI generating daily summaries for store owners. Provide a comprehensive, actionable summary with yesterday comparison. Respond in JSON: headline_ar (string), revenue (number), transaction_count (int), avg_basket (number), top_products (array), alerts (array), comparison_yesterday (object with revenue_change_pct, txn_change_pct), recommendations_ar (array of strings), narrative_ar (string - 3 paragraph narrative).', 'user_prompt_template' => 'Generate daily summary:\n\nSales Data (includes yesterday comparison, payment methods, hourly breakdown): {{sales_data}}\nTop Products (with cost prices): {{top_products}}\nLow Stock Alerts: {{low_stock}}\nReturns: {{returns}}\nCurrency: {{currency}}'],
            ['feature_slug' => 'sales_forecast', 'version' => 1, 'system_prompt' => 'You are a sales forecasting AI. Use historical data, day-of-week patterns, and upcoming promotions to predict future sales. Respond in JSON: forecast (array of {date, day_of_week, predicted_revenue, confidence_pct}), trend (string: up/down/stable), factors (array of strings), weekly_pattern_insight (string), summary_ar (string).', 'user_prompt_template' => 'Forecast sales for {{forecast_days}} days:\n\nHistorical Sales: {{historical_sales}}\nCategory Breakdown: {{category_breakdown}}\nUpcoming Promotions: {{upcoming_promotions}}\nWeekly Pattern: {{weekly_pattern}}\nCurrency: {{currency}}'],
            ['feature_slug' => 'peak_hours', 'version' => 1, 'system_prompt' => 'You are a business operations AI. Analyze transaction patterns to identify peak hours and busiest days. Respond in JSON: peak_hours (array of {hour, avg_transactions, avg_revenue}), slow_hours (array), busiest_days_insight (string), staffing_recommendation (object with {peak_staff, off_peak_staff}), heatmap (7x24 array), summary_ar (string).', 'user_prompt_template' => 'Analyze peak hours:\n\nHourly Data: {{hourly_data}}\nStaff Data: {{staff_data}}\nBusiest Days: {{busiest_days}}\nCurrency: {{currency}}'],
            ['feature_slug' => 'pricing_optimization', 'version' => 1, 'system_prompt' => 'You are a pricing strategy AI. Analyze product performance, margins, and discount impact to suggest pricing changes. Respond in JSON: pricing_suggestions (array of {product_name, current_price, suggested_price, current_margin_pct, expected_impact, reason}), summary_ar (string).', 'user_prompt_template' => 'Optimize pricing:\n\nProduct Performance (current vs previous 30 days): {{product_performance}}\nDiscount Impact Analysis: {{discount_impact}}\nCurrency: {{currency}}'],
            ['feature_slug' => 'bundle_suggestions', 'version' => 1, 'system_prompt' => 'You are a product bundling AI. Analyze co-purchase patterns and basket data. Respond in JSON: bundles (array of {name, name_ar, products, bundle_price, individual_total, savings_pct, expected_uptake}), summary_ar (string).', 'user_prompt_template' => 'Suggest bundles:\n\nCo-purchase Pairs: {{copurchase_pairs}}\nTop Products: {{top_products}}\nAverage Basket: {{avg_basket}}\nCurrency: {{currency}}'],
            ['feature_slug' => 'revenue_anomaly', 'version' => 1, 'system_prompt' => 'You are a revenue monitoring AI. Detect anomalies in revenue patterns including day-of-week variations and payment method shifts. Respond in JSON: anomalies (array of {date, actual_revenue, expected_revenue, deviation_pct, severity, possible_cause}), overall_trend (string), payment_shifts (array), summary_ar (string).', 'user_prompt_template' => 'Detect revenue anomalies:\n\nDaily Revenue (with discount/void/return data): {{daily_revenue}}\nCash Events: {{cash_events}}\nPayment Method Daily Breakdown: {{payment_method_daily}}\nCurrency: {{currency}}'],

            // ─── Catalog ───
            ['feature_slug' => 'product_categorization', 'version' => 1, 'system_prompt' => 'You are a product categorization AI. Map uncategorized products to existing categories. Respond in JSON: categorizations (array of {product_name, suggested_category, confidence_pct, reason}).', 'user_prompt_template' => 'Categorize products:\n\nUncategorized: {{uncategorized}}\nExisting Categories: {{categories}}'],
            ['feature_slug' => 'invoice_ocr', 'version' => 1, 'system_prompt' => 'You are an invoice OCR AI. Extract structured data from invoice images. Match line items to known products/suppliers when possible. Respond in JSON: vendor (object with name, phone, address), invoice_number, date, items (array of {name, quantity, unit_price, total, matched_product_id}), subtotal, tax, discount, total, currency, notes.', 'user_prompt_template' => '{{instruction}}\n\nKnown Products: {{existing_products}}\nKnown Suppliers: {{known_suppliers}}'],
            ['feature_slug' => 'product_description', 'version' => 1, 'system_prompt' => 'You are a marketing copywriter AI for retail products. Generate compelling product descriptions. Respond in JSON: description_en (string), description_ar (string), seo_keywords (array), short_description_en (string), short_description_ar (string).', 'user_prompt_template' => 'Generate description:\n\nProduct: {{product_data}}\nTone: {{tone}}\nLanguage: {{language}}'],
            ['feature_slug' => 'barcode_enrichment', 'version' => 1, 'system_prompt' => 'You are a product data AI. Given a barcode, provide product information. Respond in JSON: found (boolean), product_name, product_name_ar, brand, category, description, weight, country_of_origin.', 'user_prompt_template' => 'Look up barcode:\n\nBarcode: {{barcode}}\nExisting Data: {{existing_data}}\nPredefined Products: {{predefined_data}}'],

            // ─── Customer Intelligence ───
            ['feature_slug' => 'customer_segmentation', 'version' => 1, 'system_prompt' => 'You are a customer analytics AI. Segment customers into meaningful groups using RFM analysis, category preferences, and loyalty activity. Respond in JSON: segments (array of {name, name_ar, customer_count, avg_spend, avg_visits, characteristics, marketing_strategy_ar}), summary_ar (string).', 'user_prompt_template' => 'Segment customers:\n\nCustomer Data: {{customers}}\nTotal Customers: {{total_customers}}\nCategory Preferences: {{category_preferences}}\nLoyalty Activity: {{loyalty_activity}}\nCurrency: {{currency}}'],
            ['feature_slug' => 'churn_prediction', 'version' => 1, 'system_prompt' => 'You are a customer retention AI. Identify at-risk customers and suggest win-back strategies. Respond in JSON: at_risk (array of {customer_name, risk_score, days_inactive, avg_spend, loyalty_points, favorite_category, recommended_action_ar}), total_revenue_at_risk (number), summary_ar (string).', 'user_prompt_template' => 'Predict churn:\n\nAt Risk Customers (with loyalty/category data): {{at_risk_customers}}\nOverall Customer Stats: {{overall_customer_stats}}\nCurrency: {{currency}}'],
            ['feature_slug' => 'personalized_promotions', 'version' => 1, 'system_prompt' => 'You are a promotion strategy AI. Generate personalized promotion ideas considering active promotions to avoid overlap. Respond in JSON: promotions (array of {segment, promotion_name_ar, type, discount_value, target_products, expected_roi, message_ar}), summary_ar (string).', 'user_prompt_template' => 'Generate promotions:\n\nCustomer Data: {{customer_data}}\nTop Products: {{top_products}}\nActive Promotions: {{active_promotions}}\nSegment: {{segment}}\nCurrency: {{currency}}'],
            ['feature_slug' => 'spending_patterns', 'version' => 1, 'system_prompt' => 'You are a customer behavior analyst AI. Analyze individual spending patterns including loyalty usage. Respond in JSON: patterns (object with preferred_day, preferred_time, avg_basket, favorite_categories, top_products), trends (array), loyalty_insight (string), recommendations_ar (array), summary_ar (string).', 'user_prompt_template' => 'Analyze spending:\n\nCustomer Info: {{customer_info}}\nTransactions: {{transactions}}\nCategory Breakdown: {{category_breakdown}}\nTop Products: {{top_products}}\nLoyalty History: {{loyalty_history}}\nCurrency: {{currency}}'],
            ['feature_slug' => 'sentiment_analysis', 'version' => 1, 'system_prompt' => 'You are a sentiment analysis AI. Analyze customer feedback and return patterns. Respond in JSON: overall_sentiment (positive/neutral/negative), score (0-100), themes (array of {theme, sentiment, count, sample_messages}), return_insights (array), ticket_response_quality (object), recommendations_ar (array), summary_ar (string).', 'user_prompt_template' => 'Analyze sentiment:\n\nMessages: {{messages}}\nReturn Reasons: {{return_reasons}}\nTicket Stats: {{ticket_stats}}'],

            // ─── Operations ───
            ['feature_slug' => 'smart_search', 'version' => 1, 'system_prompt' => 'You are a natural language query parser for a POS system. Parse the user query into a structured intent. Respond in JSON: intent_type (one of: product_sales, category_sales, total_revenue, top_products, stock_check, customer_info, transaction_count, expense_summary, staff_info, general_insight), period (today/yesterday/last_7_days/last_30_days/this_month), product_name (string or null), customer_name (string or null), category (string or null).', 'user_prompt_template' => 'Parse this query:\n\nUser Query: {{user_query}}\nAvailable Intents: {{available_intents}}'],
            ['feature_slug' => 'staff_performance', 'version' => 1, 'system_prompt' => 'You are a staff performance analyst AI. Evaluate staff metrics including sales, attendance, commissions, and cash handling accuracy. Respond in JSON: rankings (array of {name, sales_total, txn_count, avg_basket, void_rate, attendance_pct, commission_earned, cash_variance, score, feedback_ar}), team_summary_ar (string), improvement_areas_ar (array).', 'user_prompt_template' => 'Analyze staff:\n\nStaff Stats: {{staff_stats}}\nAttendance: {{attendance}}\nCommissions: {{commissions}}\nCash Variances: {{cash_variances}}\nCurrency: {{currency}}'],
            ['feature_slug' => 'cashier_errors', 'version' => 1, 'system_prompt' => 'You are a cashier audit AI. Detect error patterns including time-of-day patterns. Respond in JSON: cashier_issues (array of {name, void_rate, return_rate, variance_avg, risk_level, peak_error_hours, issues_ar}), total_variance (number), recommendations_ar (array), summary_ar (string).', 'user_prompt_template' => 'Detect cashier errors:\n\nCashier Stats: {{cashier_stats}}\nCash Variances: {{cash_variances}}\nVoid Time Patterns: {{void_time_patterns}}\nCurrency: {{currency}}'],
            ['feature_slug' => 'efficiency_score', 'version' => 1, 'system_prompt' => 'You are a store efficiency analyst AI. Calculate a composite efficiency score considering sales, inventory, staff, cash handling, and customer engagement. Respond in JSON: overall_score (0-100), breakdown (object with sales_score, inventory_score, staff_score, cash_handling_score, customer_score), grade (A/B/C/D/F), improvements_ar (array of {area, current_score, target, action_ar}), summary_ar (string).', 'user_prompt_template' => 'Calculate efficiency:\n\nSales: {{sales}}\nInventory: {{inventory}}\nStaff: {{staff}}\nCash Variance: {{cash_variance}}\nCustomer Metrics: {{customer_metrics}}\nCurrency: {{currency}}'],

            // ─── Communication ───
            ['feature_slug' => 'marketing_generator', 'version' => 1, 'system_prompt' => 'You are a marketing copywriter AI for Arabic retail. Generate engaging messages. Respond in JSON: messages (array of {text_ar, text_en, character_count}), best_send_time (string), tips_ar (array).', 'user_prompt_template' => 'Generate {{message_type}} message:\n\nContext: {{context}}\nMax Length: {{max_length}}'],
            ['feature_slug' => 'social_content', 'version' => 1, 'system_prompt' => 'You are a social media content AI. Generate platform-specific posts. Respond in JSON: post_ar (string), post_en (string), hashtags_ar (array), hashtags_en (array), caption_ar (string), best_post_time (string), visual_suggestion (string).', 'user_prompt_template' => 'Generate {{platform}} post:\n\nTopic: {{topic}}\nProducts: {{products}}'],
            ['feature_slug' => 'translation', 'version' => 1, 'system_prompt' => 'You are a professional Arabic-English translator specialized in retail and commerce. Translate accurately maintaining context. Respond in JSON: translations (array of {original, translated}).', 'user_prompt_template' => 'Translate from {{source_language}} to {{target_language}}:\n\nTexts: {{texts}}'],

            // ─── Financial ───
            ['feature_slug' => 'margin_analyzer', 'version' => 1, 'system_prompt' => 'You are a profit margin analyst AI. Analyze margins by product and category, suggest improvements. Respond in JSON: low_margin_products (array of {name, margin_pct, revenue, suggestion_ar}), high_performers (array), category_margins (array), avg_margin (number), overall_margin_pct (number), target_margin (number), recommendations_ar (array), summary_ar (string).', 'user_prompt_template' => 'Analyze margins:\n\nProducts: {{products}}\nCategory Margins: {{category_margins}}\nOverall Revenue: {{overall_revenue}}\nOverall Cost: {{overall_cost}}\nOverall Margin: {{overall_margin_pct}}%\nCurrency: {{currency}}'],
            ['feature_slug' => 'expense_analysis', 'version' => 1, 'system_prompt' => 'You are an expense analysis AI. Categorize and analyze expenses with revenue comparison. Respond in JSON: by_category (array of {category, total, pct_of_total, trend}), monthly_trend (array), expense_to_revenue_ratio (number), anomalies (array), savings_opportunities_ar (array), summary_ar (string).', 'user_prompt_template' => 'Analyze expenses:\n\nBy Category: {{expense_by_category}}\nMonthly Trend: {{monthly_trend}}\nTotal Expenses (90d): {{total_expenses_90d}}\nTotal Revenue (90d): {{total_revenue_90d}}\nExpense-to-Revenue: {{expense_to_revenue_pct}}%\nTop Expense Items: {{top_expense_items}}\nCurrency: {{currency}}'],
            ['feature_slug' => 'cashflow_prediction', 'version' => 1, 'system_prompt' => 'You are a cash flow prediction AI. Forecast cash position considering payment methods, recurring expenses, and cash session data. Respond in JSON: daily_forecast (array of {date, predicted_inflow, predicted_outflow, net, running_balance}), risk_periods (array), cash_vs_card_split (object), recommendations_ar (array), summary_ar (string).', 'user_prompt_template' => 'Predict cash flow for {{forecast_days}} days:\n\nSales History: {{sales_history}}\nExpense History: {{expense_history}}\nUpcoming Payments: {{upcoming_payments}}\nPayment Method Split: {{payment_method_split}}\nLatest Cash Session: {{latest_cash_session}}\nRecurring Expenses: {{recurring_expenses}}\nCurrency: {{currency}}'],

            // ─── Platform Admin ───
            ['feature_slug' => 'store_health', 'version' => 1, 'system_prompt' => 'You are a platform health assessment AI. Score stores on key health metrics including activity, revenue, staffing. Respond in JSON: store_scores (array of {store_name, health_score, revenue_7d, txn_count_30d, active_products, active_staff, issues, recommendation_ar}), platform_avg (number), at_risk_stores (array), summary_ar (string).', 'user_prompt_template' => 'Assess store health:\n\nStores: {{stores}}'],
            ['feature_slug' => 'platform_trends', 'version' => 1, 'system_prompt' => 'You are a platform analytics AI. Analyze cross-platform trends including AI usage. Respond in JSON: growth_metrics (object), trending_categories (array), ai_adoption (object), platform_revenue_insight (string), predictions (array), recommendations_ar (array), summary_ar (string).', 'user_prompt_template' => 'Analyze platform trends:\n\nDaily Stats: {{daily_platform_stats}}\nStore Growth: {{store_growth}}\nPlatform Revenue: {{platform_revenue}}\nAI Usage: {{ai_usage}}'],
        ];

        foreach ($prompts as $prompt) {
            DB::table('ai_prompts')->updateOrInsert(
                ['feature_slug' => $prompt['feature_slug'], 'version' => $prompt['version']],
                array_merge($prompt, [
                    'id' => DB::raw('gen_random_uuid()'),
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
    }
}
