<?php

namespace App\Http\Controllers;

use App\Domain\ContentOnboarding\Models\CfdTheme;
use App\Domain\ContentOnboarding\Models\LabelLayoutTemplate;
use App\Domain\ContentOnboarding\Models\ReceiptLayoutTemplate;
use App\Domain\ContentOnboarding\Models\TemplateMarketplaceListing;
use Illuminate\Http\Request;

class TemplatePreviewController extends Controller
{
    /**
     * Public receipt-layout-template preview (standalone HTML, no admin auth).
     * Uses Laravel signed URLs so the link can only be generated by
     * an authenticated API consumer.
     */
    public function receiptTemplate(Request $request, string $id)
    {
        if (! $request->hasValidSignature()) {
            abort(403, 'Invalid or expired preview link.');
        }

        $record = ReceiptLayoutTemplate::findOrFail($id);

        return view('preview.receipt-template', compact('record'));
    }

    /**
     * Public CFD theme preview (standalone HTML, no admin auth).
     */
    public function cfdTheme(Request $request, string $id)
    {
        if (! $request->hasValidSignature()) {
            abort(403, 'Invalid or expired preview link.');
        }

        $record = CfdTheme::findOrFail($id);

        return view('preview.cfd-theme', compact('record'));
    }

    /**
     * Public label layout template preview (standalone HTML, no admin auth).
     */
    public function labelTemplate(Request $request, string $id)
    {
        if (! $request->hasValidSignature()) {
            abort(403, 'Invalid or expired preview link.');
        }

        $record = LabelLayoutTemplate::findOrFail($id);

        return view('preview.label-template', compact('record'));
    }

    /**
     * Public marketplace listing preview (standalone HTML, no admin auth).
     */
    public function marketplaceListing(Request $request, string $id)
    {
        if (! $request->hasValidSignature()) {
            abort(403, 'Invalid or expired preview link.');
        }

        $record = TemplateMarketplaceListing::with(['category'])->findOrFail($id);

        return view('preview.marketplace-listing', compact('record'));
    }
}
